// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H117",
  "number": 117,
  "slug": "next-greater-element-i",
  "title": "Next Greater Element I",
  "category": "Stack",
  "definition": "For each number in nums1, find the next bigger number to its right inside nums2 (or −1).",
  "example": {
    "input": "nums1 = [4,1,2], nums2 = [1,3,4,2]",
    "output": "[-1,3,-1]"
  },
  "approach": "For each number, find it in nums2, then look to its right for the first bigger one.",
  "keyIdea": [
    "Find x in nums2",
    "Scan to the right for a bigger value",
    "If none → −1"
  ],
  "time": "O(n·m)",
  "space": "O(1)",
  "complexityWhy": "Rescans nums2 for each value.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums2",
        "v": [
          1,
          3,
          4,
          2
        ],
        "ok": [
          1
        ],
        "hi": [
          0,
          2
        ],
        "p": {
          "0": "1→3",
          "2": "4→?"
        }
      }
    ],
    "cap": "1's next greater is 3, 4 has none (−1), 2 has none (−1)."
  },
  "better": {
    "name": "Monotonic stack + Map",
    "time": "O(n+m)",
    "space": "O(m)",
    "code": "class Solution {\n  public int[] nextGreaterElement(int[] nums1, int[] nums2) {\n    Map<Integer, Integer> next = new HashMap<>();\n    Deque<Integer> stack = new ArrayDeque<>();         // values waiting for a bigger one\n    for (int num : nums2) {\n      while (!stack.isEmpty() && stack.peek() < num) next.put(stack.pop(), num);\n      stack.push(num);\n    }\n    int[] result = new int[nums1.length];\n    for (int i = 0; i < nums1.length; i++) result[i] = next.getOrDefault(nums1[i], -1);\n    return result;\n  }\n}"
  },
  "code": "class Solution {\n  public int[] nextGreaterElement(int[] nums1, int[] nums2) {\n    int[] result = new int[nums1.length];\n    for (int k = 0; k < nums1.length; k++) {\n      int x = nums1[k], i = 0;\n      while (nums2[i] != x) i++;                       // find x in nums2\n      int answer = -1;\n      for (i = i + 1; i < nums2.length; i++) {\n        if (nums2[i] > x) { answer = nums2[i]; break; }\n      }\n      result[k] = answer;\n    }\n    return result;\n  }\n}",
  "method": "nextGreaterElement",
  "defaultInput": "[4,1,2], [1,3,4,2]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          4,
          1,
          2
        ],
        [
          1,
          3,
          4,
          2
        ]
      ],
      "expected": [
        -1,
        3,
        -1
      ]
    },
    {
      "name": "Two numbers",
      "args": [
        [
          2,
          4
        ],
        [
          1,
          2,
          3,
          4
        ]
      ],
      "expected": [
        3,
        -1
      ]
    },
    {
      "name": "Single number",
      "args": [
        [
          1
        ],
        [
          1
        ]
      ],
      "expected": [
        -1
      ]
    },
    {
      "name": "Big number last",
      "args": [
        [
          1,
          3,
          5,
          2,
          4
        ],
        [
          6,
          5,
          4,
          3,
          2,
          1,
          7
        ]
      ],
      "expected": [
        7,
        7,
        7,
        7,
        7
      ]
    },
    {
      "name": "Empty nums1",
      "args": [
        [],
        [
          1,
          2
        ]
      ],
      "expected": []
    },
    {
      "name": "Mixed",
      "args": [
        [
          3,
          1
        ],
        [
          3,
          2,
          1,
          4
        ]
      ],
      "expected": [
        4,
        4
      ]
    }
  ],
  "challenge": {
    "question": "What is the next greater element in nums2 for each number of nums1?",
    "input": "[5,1], [4,5,2,1,3]",
    "options": [
      "[0,4]",
      "[3,-1]",
      "[-1]",
      "[-1,3]"
    ],
    "answer": 3,
    "explanation": "After 5 in nums2 (2, 1, 3) nothing is bigger → −1. After 1 comes 3, which is bigger → 3. Result: [−1, 3]."
  },
  "memory": {
    "remember": "Scan once, keeping a stack of values\nthat are still waiting for something bigger.",
    "pattern": "Monotonic stack + Map"
  }
};

export default problem;
