// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H058",
  "number": 58,
  "slug": "contains-duplicate",
  "title": "Contains Duplicate",
  "category": "Hashing",
  "definition": "Does any value appear at least twice?",
  "example": {
    "input": "[1,2,3,1]",
    "output": "true"
  },
  "approach": "Put each number in a set. If adding fails, the number was already there.",
  "keyIdea": [
    "Create an empty HashSet",
    "Call add() for each number",
    "add() returns false → duplicate found"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "One pass, O(n) memory.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums",
        "v": [
          1,
          2,
          3,
          1
        ],
        "ok": [
          0,
          3
        ]
      },
      {
        "l": "Set",
        "v": [
          1,
          2,
          3
        ],
        "hi": [
          0,
          1,
          2
        ]
      }
    ],
    "cap": "The second 1 is already in the Set."
  },
  "code": "class Solution {\n  public boolean containsDuplicate(int[] nums) {\n    Set<Integer> seen = new HashSet<>();\n    for (int n : nums) {\n      if (!seen.add(n)) return true;                   // add() is false if already there\n    }\n    return false;\n  }\n}",
  "method": "containsDuplicate",
  "defaultInput": "[1,2,3,1]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          1
        ]
      ],
      "expected": true
    },
    {
      "name": "All distinct",
      "args": [
        [
          1,
          2,
          3,
          4
        ]
      ],
      "expected": false
    },
    {
      "name": "Empty",
      "args": [
        []
      ],
      "expected": false
    },
    {
      "name": "Single",
      "args": [
        [
          1
        ]
      ],
      "expected": false
    },
    {
      "name": "Far apart",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          6,
          1
        ]
      ],
      "expected": true
    },
    {
      "name": "Negatives",
      "args": [
        [
          -1,
          -1
        ]
      ],
      "expected": true
    }
  ],
  "challenge": {
    "question": "Does the array contain a duplicate?",
    "input": "[4,8,15,16,23,42,8]",
    "options": [
      "true",
      "false"
    ],
    "answer": 0,
    "explanation": "8 appears twice — the Set already holds it when we reach the second 8."
  },
  "memory": {
    "remember": "A Set answers \"seen before?\"\nin O(1).",
    "pattern": "Set: have I seen this?"
  }
};

export default problem;
