// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H086",
  "number": 86,
  "slug": "number-of-islands",
  "title": "Number of Islands",
  "category": "Graph",
  "definition": "Count groups of connected land cells ('1') in a grid.",
  "example": {
    "input": "4×5 grid of \"1\" and \"0\"",
    "output": "3"
  },
  "approach": "Find a land cell, then flood-fill every connected land cell so it isn't counted twice. Each flood-fill = one island.",
  "keyIdea": [
    "Scan every cell",
    "On unvisited land: count++ and flood (DFS) its island",
    "Mark visited cells"
  ],
  "time": "O(m·n)",
  "space": "O(m·n)",
  "complexityWhy": "Every cell is visited once; recursion can get deep.",
  "figure": {
    "k": "grid",
    "v": [
      [
        1,
        1,
        0,
        0,
        0
      ],
      [
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        1,
        1
      ]
    ],
    "ok": [
      [
        0,
        0
      ],
      [
        0,
        1
      ],
      [
        1,
        0
      ],
      [
        1,
        1
      ]
    ],
    "hi": [
      [
        2,
        2
      ]
    ],
    "bl": [
      [
        3,
        3
      ],
      [
        3,
        4
      ]
    ],
    "cap": "Three colours = three islands."
  },
  "code": "class Solution {\n  private char[][] grid;\n  private boolean[][] visited;\n  public int numIslands(char[][] grid) {\n    this.grid = grid;\n    visited = new boolean[grid.length][grid[0].length];\n    int islands = 0;\n    for (int r = 0; r < grid.length; r++) {\n      for (int c = 0; c < grid[0].length; c++) {\n        if (grid[r][c] == '1' && !visited[r][c]) { islands++; flood(r, c); }\n      }\n    }\n    return islands;\n  }\n  private void flood(int r, int c) {\n    if (r < 0 || c < 0 || r >= grid.length || c >= grid[0].length) return;   // outside the grid\n    if (grid[r][c] == '0' || visited[r][c]) return;                           // water or already done\n    visited[r][c] = true;\n    flood(r + 1, c); flood(r - 1, c); flood(r, c + 1); flood(r, c - 1);\n  }\n}",
  "method": "numIslands",
  "defaultInput": "[\"11000\",\"11000\",\"00100\",\"00011\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          "11000",
          "11000",
          "00100",
          "00011"
        ]
      ],
      "expected": 3
    },
    {
      "name": "No land",
      "args": [
        [
          "000",
          "000"
        ]
      ],
      "expected": 0
    },
    {
      "name": "One big island",
      "args": [
        [
          "111",
          "111"
        ]
      ],
      "expected": 1
    },
    {
      "name": "Diagonals don't connect",
      "args": [
        [
          "10",
          "01"
        ]
      ],
      "expected": 2
    },
    {
      "name": "Single cell",
      "args": [
        [
          "1"
        ]
      ],
      "expected": 1
    },
    {
      "name": "Checkerboard",
      "args": [
        [
          "101",
          "010",
          "101"
        ]
      ],
      "expected": 5
    }
  ],
  "challenge": {
    "question": "How many islands are there?",
    "input": "[\"11011\",\"11000\",\"00100\",\"00011\"]",
    "options": [
      "8",
      "4",
      "6",
      "2"
    ],
    "answer": 1,
    "explanation": "Land cells that touch up, down, left or right form one island: the top-left block, the top-right pair, the single middle cell and the bottom-right pair → 4."
  },
  "memory": {
    "remember": "Find a '1', flood the whole island,\ncount one — repeat.",
    "pattern": "Flood Fill (DFS) per Island"
  }
};

export default problem;
