// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H145",
  "number": 145,
  "slug": "k-closest-points-to-origin",
  "title": "K Closest Points to Origin",
  "category": "Heap / Priority Queue",
  "definition": "Return the k points closest to (0, 0).",
  "example": {
    "input": "[[3,3],[5,-1],[-2,4]], k = 2",
    "output": "[[3,3],[-2,4]]"
  },
  "approach": "Keep a max-heap of size k ordered by distance. If it grows past k, remove the farthest point.",
  "keyIdea": [
    "dist = x² + y² (no square root needed)",
    "Add each point to a max-heap",
    "Size > k → remove the farthest",
    "The heap holds the k closest points"
  ],
  "time": "O(n log k)",
  "space": "O(k)",
  "complexityWhy": "n pushes, each O(log k).",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "point",
        "v": [
          "(3,3)",
          "(5,-1)",
          "(-2,4)"
        ]
      },
      {
        "l": "dist²",
        "v": [
          18,
          26,
          20
        ],
        "ok": [
          0,
          2
        ],
        "no": [
          1
        ]
      }
    ],
    "cap": "Keep the two smallest distances."
  },
  "code": "class Solution {\n  public int[][] kClosest(int[][] points, int k) {\n    PriorityQueue<int[]> heap = new PriorityQueue<>((a, b) -> dist(b) - dist(a));   // max-heap by distance\n    for (int[] p : points) {\n      heap.add(p);\n      if (heap.size() > k) heap.poll();                       // throw away the farthest\n    }\n    int[][] result = new int[k][];\n    for (int i = 0; i < k; i++) result[i] = heap.poll();\n    return result;\n  }\n  private int dist(int[] p) { return p[0] * p[0] + p[1] * p[1]; }\n}",
  "method": "kClosest",
  "unordered": true,
  "defaultInput": "[[3,3],[5,-1],[-2,4]], 2",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            3,
            3
          ],
          [
            5,
            -1
          ],
          [
            -2,
            4
          ]
        ],
        2
      ],
      "expected": [
        [
          -2,
          4
        ],
        [
          3,
          3
        ]
      ]
    },
    {
      "name": "One of two",
      "args": [
        [
          [
            1,
            3
          ],
          [
            -2,
            2
          ]
        ],
        1
      ],
      "expected": [
        [
          -2,
          2
        ]
      ]
    },
    {
      "name": "Both points",
      "args": [
        [
          [
            0,
            1
          ],
          [
            1,
            0
          ]
        ],
        2
      ],
      "expected": [
        [
          0,
          1
        ],
        [
          1,
          0
        ]
      ]
    },
    {
      "name": "Single point",
      "args": [
        [
          [
            1,
            1
          ]
        ],
        1
      ],
      "expected": [
        [
          1,
          1
        ]
      ]
    },
    {
      "name": "Pick the nearest",
      "args": [
        [
          [
            2,
            2
          ],
          [
            1,
            1
          ],
          [
            3,
            3
          ]
        ],
        1
      ],
      "expected": [
        [
          1,
          1
        ]
      ]
    },
    {
      "name": "With the origin",
      "args": [
        [
          [
            0,
            0
          ],
          [
            5,
            5
          ],
          [
            1,
            2
          ]
        ],
        2
      ],
      "expected": [
        [
          1,
          2
        ],
        [
          0,
          0
        ]
      ]
    }
  ],
  "challenge": {
    "question": "Which point is closest to the origin?",
    "input": "[[3,4],[1,1],[-2,0]], 1",
    "options": [
      "[[1,1]]",
      "[[3,4]]",
      "[[-2,0]]",
      "[[1,1],[-2,0]]"
    ],
    "answer": 0,
    "explanation": "Squared distances: (3,4) → 25, (1,1) → 2, (−2,0) → 4. The smallest is (1,1)."
  },
  "memory": {
    "remember": "Keep a max-heap of the k closest points —\nthe farthest of them sits on top, ready to be kicked out.",
    "pattern": "Max-heap of size k"
  }
};

export default problem;
