// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H101",
  "number": 101,
  "slug": "reverse-a-linked-list",
  "title": "Reverse a Linked List",
  "category": "Linked List",
  "definition": "Reverse a singly linked list.",
  "example": {
    "input": "1 → 2 → 3 → 4 → 5",
    "output": "5 → 4 → 3 → 2 → 1"
  },
  "approach": "Walk along the list and flip every arrow so it points backwards.",
  "keyIdea": [
    "prev = null, curr = head",
    "Save curr.next",
    "Point curr.next at prev",
    "Move prev and curr forward"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass, no extra memory.",
  "figure": [
    {
      "k": "list",
      "v": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "k": "list",
      "v": [
        5,
        4,
        3,
        2,
        1
      ],
      "ok": [
        0,
        1,
        2,
        3,
        4
      ],
      "cap": "Every arrow now points the other way."
    }
  ],
  "code": "class Solution {\n  public ListNode reverseList(ListNode head) {\n    ListNode prev = null, curr = head;\n    while (curr != null) {\n      ListNode next = curr.next;   // remember the rest\n      curr.next = prev;            // flip the arrow\n      prev = curr;                 // step forward\n      curr = next;\n    }\n    return prev;\n  }\n}",
  "method": "reverseList",
  "defaultInput": "[1,2,3,4,5]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        5,
        4,
        3,
        2,
        1
      ]
    },
    {
      "name": "Empty list",
      "args": [
        []
      ],
      "expected": null
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "Two nodes",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": [
        2,
        1
      ]
    },
    {
      "name": "Equal values",
      "args": [
        [
          3,
          3,
          3
        ]
      ],
      "expected": [
        3,
        3,
        3
      ]
    },
    {
      "name": "Three nodes",
      "args": [
        [
          10,
          20,
          30
        ]
      ],
      "expected": [
        30,
        20,
        10
      ]
    }
  ],
  "challenge": {
    "question": "What does the list look like after reversing it?",
    "input": "[10,20,30,40]",
    "options": [
      "[30,40,20,10]",
      "[30,20,10,40]",
      "[40,30,20,10]",
      "[41,31,21,11]"
    ],
    "answer": 2,
    "explanation": "Every pointer is flipped so each node points to the one before it: 40 → 30 → 20 → 10."
  },
  "memory": {
    "remember": "Keep prev, curr, next:\nflip curr.next = prev, then step forward.",
    "pattern": "Flip each pointer (in place)"
  }
};

export default problem;
