// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H008",
  "number": 8,
  "slug": "3sum",
  "title": "3Sum",
  "category": "Arrays",
  "definition": "Find all unique triplets that add up to 0.",
  "example": {
    "input": "[-1,0,1,2,-1,-4]",
    "output": "[[-1,-1,2],[-1,0,1]]"
  },
  "approach": "Pick one number, then the problem becomes Pair Sum on the rest of the sorted array.",
  "keyIdea": [
    "Sort the array",
    "Try every triple with three loops",
    "Use a Set to skip repeated triples"
  ],
  "time": "O(n³)",
  "space": "O(n)",
  "complexityWhy": "Three nested loops over all triples.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "sorted",
        "v": [
          -4,
          -1,
          -1,
          0,
          1,
          2
        ],
        "ok": [
          1,
          2,
          5
        ],
        "p": {
          "1": "i",
          "2": "L",
          "5": "R"
        }
      }
    ],
    "cap": "Fix i = −1, then L + R must equal +1: −1 + 2 ✓"
  },
  "better": {
    "name": "Sort + two pointers",
    "time": "O(n²)",
    "space": "O(1)",
    "code": "class Solution {\n  public List<List<Integer>> threeSum(int[] nums) {\n    Arrays.sort(nums);\n    List<List<Integer>> result = new ArrayList<>();\n    for (int i = 0; i < nums.length - 2; i++) {\n      if (i > 0 && nums[i] == nums[i - 1]) continue;   // skip repeats\n      int left = i + 1, right = nums.length - 1;\n      while (left < right) {\n        int sum = nums[i] + nums[left] + nums[right];\n        if (sum == 0) {\n          result.add(Arrays.asList(nums[i], nums[left], nums[right]));\n          while (left < right && nums[left] == nums[left + 1]) left++;\n          while (left < right && nums[right] == nums[right - 1]) right--;\n          left++; right--;\n        } else if (sum < 0) left++;\n        else right--;\n      }\n    }\n    return result;\n  }\n}"
  },
  "code": "class Solution {\n  public List<List<Integer>> threeSum(int[] nums) {\n    Arrays.sort(nums);\n    Set<String> seen = new HashSet<>();\n    List<List<Integer>> result = new ArrayList<>();\n    for (int i = 0; i < nums.length; i++) {\n      for (int j = i + 1; j < nums.length; j++) {\n        for (int k = j + 1; k < nums.length; k++) {\n          if (nums[i] + nums[j] + nums[k] == 0) {\n            String key = nums[i] + \",\" + nums[j] + \",\" + nums[k];\n            if (seen.add(key)) result.add(Arrays.asList(nums[i], nums[j], nums[k]));\n          }\n        }\n      }\n    }\n    return result;\n  }\n}",
  "method": "threeSum",
  "defaultInput": "[-1,0,1,2,-1,-4]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          -1,
          0,
          1,
          2,
          -1,
          -4
        ]
      ],
      "expected": [
        [
          -1,
          -1,
          2
        ],
        [
          -1,
          0,
          1
        ]
      ]
    },
    {
      "name": "No triplet",
      "args": [
        [
          1,
          2,
          3
        ]
      ],
      "expected": []
    },
    {
      "name": "All zeros",
      "args": [
        [
          0,
          0,
          0,
          0
        ]
      ],
      "expected": [
        [
          0,
          0,
          0
        ]
      ]
    },
    {
      "name": "Duplicates",
      "args": [
        [
          -2,
          0,
          0,
          2,
          2
        ]
      ],
      "expected": [
        [
          -2,
          0,
          2
        ]
      ]
    },
    {
      "name": "Too short",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": []
    },
    {
      "name": "Mixed",
      "args": [
        [
          -4,
          -2,
          -2,
          0,
          1,
          2,
          2,
          3,
          4
        ]
      ],
      "expected": [
        [
          -4,
          0,
          4
        ],
        [
          -4,
          1,
          3
        ],
        [
          -4,
          2,
          2
        ],
        [
          -2,
          -2,
          4
        ],
        [
          -2,
          0,
          2
        ]
      ]
    }
  ],
  "challenge": {
    "question": "How many different triplets add up to 0?",
    "input": "[-2,0,1,1,2]",
    "options": [
      "0",
      "1",
      "2",
      "4"
    ],
    "answer": 2,
    "explanation": "Sorted: [-2,0,1,1,2]. The triplets are (−2, 0, 2) and (−2, 1, 1) — repeated triplets are skipped, so the answer is 2."
  },
  "memory": {
    "remember": "Sort, fix one number,\nthen squeeze the other two.",
    "pattern": "Sort + Two Pointers"
  }
};

export default problem;
