// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H074",
  "number": 74,
  "slug": "invert-binary-tree",
  "title": "Invert Binary Tree",
  "category": "Trees",
  "definition": "Swap left and right children everywhere.",
  "example": {
    "input": "[4,2,7,1,3,6,9]",
    "output": "[4,7,2,9,6,3,1]"
  },
  "approach": "Swap a node's two children, then do the same for both subtrees.",
  "keyIdea": [
    "Empty → return null",
    "Swap left and right",
    "Recurse on both children"
  ],
  "time": "O(n)",
  "space": "O(h)",
  "complexityWhy": "Every node is visited once.",
  "figure": [
    {
      "k": "tree",
      "v": [
        4,
        2,
        7,
        1,
        3,
        6,
        9
      ]
    },
    {
      "k": "tree",
      "v": [
        4,
        7,
        2,
        9,
        6,
        3,
        1
      ],
      "ok": [
        7,
        2
      ],
      "cap": "Mirror image of the original."
    }
  ],
  "code": "class Solution {\n  public TreeNode invertTree(TreeNode root) {\n    if (root == null) return null;\n    TreeNode left = invertTree(root.left);     // invert the subtrees first\n    TreeNode right = invertTree(root.right);\n    root.left = right;                         // then swap them\n    root.right = left;\n    return root;\n  }\n}",
  "method": "invertTree",
  "defaultInput": "[4,2,7,1,3,6,9]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          4,
          2,
          7,
          1,
          3,
          6,
          9
        ]
      ],
      "expected": [
        4,
        7,
        2,
        9,
        6,
        3,
        1
      ]
    },
    {
      "name": "Empty tree",
      "args": [
        []
      ],
      "expected": null
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "Left child only",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": [
        1,
        null,
        2
      ]
    },
    {
      "name": "Small tree",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        1,
        3,
        2,
        null,
        null,
        5,
        4
      ]
    },
    {
      "name": "Right chain",
      "args": [
        [
          1,
          null,
          2,
          null,
          3
        ]
      ],
      "expected": [
        1,
        2,
        null,
        3
      ]
    }
  ],
  "challenge": {
    "question": "What does the inverted tree look like (level order)?",
    "input": "[1,2,3,4,5]",
    "options": [
      "[1,3,2,null,null,5,4]",
      "[3,2,null,null,5,4,1]",
      "[4,5,null,null,2,3,1]",
      "[1,3,2,null,null,5]"
    ],
    "answer": 0,
    "explanation": "Swap the children at every node: 1's children become 3 and 2, and 2's children become 5 and 4 → [1,3,2,null,null,5,4]."
  },
  "memory": {
    "remember": "Swap the two children,\nthen invert both subtrees.",
    "pattern": "Recursive Swap"
  }
};

export default problem;
