// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H016",
  "number": 16,
  "slug": "find-second-largest-smallest-element",
  "title": "Find Second Largest / Second Smallest Element",
  "category": "Arrays",
  "definition": "Return the second smallest and second largest distinct values.",
  "example": {
    "input": "[4,1,9,7,9,1]",
    "output": "second min 4, second max 7"
  },
  "approach": "Remove duplicates, sort, and take the second value from each end.",
  "keyIdea": [
    "Remove duplicates with a Set",
    "Sort the unique values",
    "Take index 1 and length − 2"
  ],
  "time": "O(n log n)",
  "space": "O(n)",
  "complexityWhy": "Sorting dominates.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "unique",
        "v": [
          1,
          4,
          7,
          9
        ],
        "hi": [
          1,
          2
        ],
        "ok": [
          0,
          3
        ],
        "p": {
          "0": "min",
          "1": "2nd min",
          "2": "2nd max",
          "3": "max"
        }
      }
    ],
    "cap": "Duplicates removed and sorted: the 2nd values are the answer."
  },
  "better": {
    "name": "Single pass with 4 variables",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int[] secondMinMax(int[] nums) {\n    int min1 = Integer.MAX_VALUE, min2 = Integer.MAX_VALUE;\n    int max1 = Integer.MIN_VALUE, max2 = Integer.MIN_VALUE;\n    for (int n : nums) {\n      if (n < min1) { min2 = min1; min1 = n; }\n      else if (n > min1 && n < min2) min2 = n;\n      if (n > max1) { max2 = max1; max1 = n; }\n      else if (n < max1 && n > max2) max2 = n;\n    }\n    return new int[]{min2, max2};\n  }\n}"
  },
  "code": "class Solution {\n  public int[] secondMinMax(int[] nums) {\n    TreeSet<Integer> set = new TreeSet<>();            // sorted, no duplicates\n    for (int n : nums) set.add(n);\n    List<Integer> unique = new ArrayList<>(set);\n    return new int[]{unique.get(1), unique.get(unique.size() - 2)};\n  }\n}",
  "method": "secondMinMax",
  "defaultInput": "[4,1,9,7,9,1]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          4,
          1,
          9,
          7,
          9,
          1
        ]
      ],
      "expected": [
        4,
        7
      ]
    },
    {
      "name": "Distinct",
      "args": [
        [
          5,
          3,
          8,
          1
        ]
      ],
      "expected": [
        3,
        5
      ]
    },
    {
      "name": "Two values",
      "args": [
        [
          2,
          7
        ]
      ],
      "expected": [
        7,
        2
      ]
    },
    {
      "name": "Duplicated max",
      "args": [
        [
          9,
          9,
          5
        ]
      ],
      "expected": [
        9,
        5
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          -2,
          -8,
          -5,
          -1
        ]
      ],
      "expected": [
        -5,
        -2
      ]
    },
    {
      "name": "Sorted",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        2,
        4
      ]
    }
  ],
  "challenge": {
    "question": "What are the second smallest and second largest values? (second min, second max)",
    "input": "[6,2,9,4,9,2]",
    "options": [
      "[6,4]",
      "[4]",
      "[4,6]",
      "[5,7]"
    ],
    "answer": 2,
    "explanation": "Duplicates don't count: the distinct values are 2, 4, 6, 9, so the second smallest is 4 and the second largest is 6."
  },
  "memory": {
    "remember": "\"Second\" means second distinct value —\nignore the duplicates.",
    "pattern": "Track the Top Two Values"
  }
};

export default problem;
