// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H114",
  "number": 114,
  "slug": "min-stack",
  "title": "Min Stack",
  "category": "Stack",
  "definition": "A stack with push, pop, top and getMin.",
  "example": {
    "input": "push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()",
    "output": "-3, 0, -2"
  },
  "approach": "Store, with every value, the smallest value at or below it. Then getMin() is just a peek.",
  "keyIdea": [
    "Each entry = {value, min so far}",
    "push: min = the smaller of the value and the current min",
    "pop restores the old min automatically"
  ],
  "time": "O(1) all",
  "space": "O(n)",
  "complexityWhy": "Every operation is O(1).",
  "figure": {
    "k": "stack",
    "s": [
      {
        "l": "[value, min]",
        "v": [
          "-2,-2",
          "0,-2",
          "-3,-3"
        ],
        "hi": [
          2
        ]
      }
    ],
    "cap": "Every entry remembers the minimum beneath it."
  },
  "code": "class MinStack {\n  private final Deque<int[]> stack = new ArrayDeque<>();   // each entry: {value, minSoFar}\n  public void push(int x) {\n    int min = stack.isEmpty() ? x : Math.min(x, getMin());\n    stack.push(new int[]{x, min});\n  }\n  public void pop() { stack.pop(); }                       // the old min is restored automatically\n  public int top() { return stack.peek()[0]; }\n  public int getMin() { return stack.peek()[1]; }\n}",
  "method": "MinStack",
  "defaultInput": "[], [[\"push\",-2],[\"push\",0],[\"push\",-3],[\"getMin\"],[\"pop\"],[\"top\"],[\"getMin\"]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [],
        [
          [
            "push",
            -2
          ],
          [
            "push",
            0
          ],
          [
            "push",
            -3
          ],
          [
            "getMin"
          ],
          [
            "pop"
          ],
          [
            "top"
          ],
          [
            "getMin"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        -3,
        null,
        0,
        -2
      ]
    },
    {
      "name": "Single value",
      "args": [
        [],
        [
          [
            "push",
            7
          ],
          [
            "top"
          ],
          [
            "getMin"
          ]
        ]
      ],
      "expected": [
        null,
        7,
        7
      ]
    },
    {
      "name": "Minimum after pops",
      "args": [
        [],
        [
          [
            "push",
            3
          ],
          [
            "push",
            1
          ],
          [
            "push",
            2
          ],
          [
            "pop"
          ],
          [
            "pop"
          ],
          [
            "getMin"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        null,
        null,
        3
      ]
    },
    {
      "name": "Equal minimums",
      "args": [
        [],
        [
          [
            "push",
            2
          ],
          [
            "push",
            2
          ],
          [
            "pop"
          ],
          [
            "getMin"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        2
      ]
    },
    {
      "name": "Increasing pushes",
      "args": [
        [],
        [
          [
            "push",
            1
          ],
          [
            "push",
            2
          ],
          [
            "push",
            3
          ],
          [
            "getMin"
          ],
          [
            "top"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        1,
        3
      ]
    },
    {
      "name": "Decreasing pushes",
      "args": [
        [],
        [
          [
            "push",
            3
          ],
          [
            "push",
            2
          ],
          [
            "push",
            1
          ],
          [
            "getMin"
          ],
          [
            "pop"
          ],
          [
            "getMin"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        1,
        null,
        2
      ]
    }
  ],
  "challenge": {
    "question": "After push(5), push(3), push(7), push(3) and pop() — what does getMin() return?",
    "input": "[], [[\"push\",5],[\"push\",3],[\"push\",7],[\"push\",3],[\"pop\"],[\"getMin\"]]",
    "options": [
      "4",
      "2",
      "5",
      "3"
    ],
    "answer": 3,
    "explanation": "The minimum 3 was pushed twice. Each entry remembers 'the minimum so far', so popping one 3 still leaves the older 3 — getMin() is 3."
  },
  "memory": {
    "remember": "Store (value, minimum so far) on every push —\nthe minimum survives pops.",
    "pattern": "Store [value, min so far] pairs"
  }
};

export default problem;
