// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H133",
  "number": 133,
  "slug": "coin-change-number-of-ways",
  "title": "Coin Change — Number of Ways",
  "category": "Dynamic Programming",
  "definition": "Count combinations of coins (unlimited) that make the amount.",
  "example": {
    "input": "amount = 5, coins [1,2,5]",
    "output": "4"
  },
  "approach": "dp[a] = number of ways to make a. Put the coins in the OUTER loop so each combination is counted once.",
  "keyIdea": [
    "dp[0] = 1",
    "For each coin",
    "For a from coin to amount: dp[a] += dp[a − coin]"
  ],
  "time": "O(amount·coins)",
  "space": "O(amount)",
  "complexityWhy": "amount × number of coins.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "amount",
        "v": [
          0,
          1,
          2,
          3,
          4,
          5
        ]
      },
      {
        "l": "ways",
        "v": [
          1,
          1,
          2,
          2,
          3,
          4
        ],
        "ok": [
          5
        ]
      }
    ],
    "cap": "5 = 5 · 2+2+1 · 2+1+1+1 · 1+1+1+1+1"
  },
  "code": "class Solution {\n  public int change(int amount, int[] coins) {\n    int[] dp = new int[amount + 1];                         // dp[a]: number of ways to make a\n    dp[0] = 1;\n    for (int coin : coins) {                                // coins in the OUTER loop -> combinations\n      for (int a = coin; a <= amount; a++) {\n        dp[a] += dp[a - coin];\n      }\n    }\n    return dp[amount];\n  }\n}",
  "method": "change",
  "defaultInput": "5, [1,2,5]",
  "tests": [
    {
      "name": "Example",
      "args": [
        5,
        [
          1,
          2,
          5
        ]
      ],
      "expected": 4
    },
    {
      "name": "Impossible",
      "args": [
        3,
        [
          2
        ]
      ],
      "expected": 0
    },
    {
      "name": "One coin",
      "args": [
        10,
        [
          10
        ]
      ],
      "expected": 1
    },
    {
      "name": "Zero amount",
      "args": [
        0,
        [
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Single coin kind",
      "args": [
        5,
        [
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Four coin kinds",
      "args": [
        10,
        [
          2,
          5,
          3,
          6
        ]
      ],
      "expected": 5
    }
  ],
  "challenge": {
    "question": "In how many different ways can you make 10 from coins 2, 5, 3 and 6 (order doesn't matter)?",
    "input": "10, [2,5,3,6]",
    "options": [
      "2",
      "5",
      "4",
      "3"
    ],
    "answer": 1,
    "explanation": "2+2+2+2+2, 2+2+3+3, 2+2+6, 2+3+5 and 5+5 → 5 combinations."
  },
  "memory": {
    "remember": "Loop over the coins on the OUTSIDE —\nthat counts combinations, not orderings.",
    "pattern": "1-D DP over coins"
  }
};

export default problem;
