// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H122",
  "number": 122,
  "slug": "house-robber",
  "title": "House Robber",
  "category": "Dynamic Programming",
  "definition": "Rob houses in a row for the most money without robbing two neighbours.",
  "example": {
    "input": "[2,7,9,3,1]",
    "output": "12  (2 + 9 + 1)"
  },
  "approach": "At each house choose: skip it (keep the best so far) or rob it (best from two houses ago + this house).",
  "keyIdea": [
    "prev = best two houses ago, curr = best one house ago",
    "next = max(curr, prev + money)",
    "Slide the pair forward"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass, two variables.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "houses",
        "v": [
          2,
          7,
          9,
          3,
          1
        ],
        "ok": [
          0,
          2,
          4
        ],
        "no": [
          1,
          3
        ]
      },
      {
        "l": "best so far",
        "v": [
          2,
          7,
          11,
          11,
          12
        ],
        "ok": [
          4
        ]
      }
    ],
    "cap": "Rob houses 1, 3 and 5 → 2 + 9 + 1 = 12."
  },
  "code": "class Solution {\n  public int rob(int[] nums) {\n    int prev = 0, curr = 0;                                // best loot two houses ago / one house ago\n    for (int n : nums) {\n      int next = Math.max(curr, prev + n);                 // skip this house, or rob it\n      prev = curr;\n      curr = next;\n    }\n    return curr;\n  }\n}",
  "method": "rob",
  "defaultInput": "[2,7,9,3,1]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          2,
          7,
          9,
          3,
          1
        ]
      ],
      "expected": 12
    },
    {
      "name": "Alternating",
      "args": [
        [
          1,
          2,
          3,
          1
        ]
      ],
      "expected": 4
    },
    {
      "name": "Single house",
      "args": [
        [
          5
        ]
      ],
      "expected": 5
    },
    {
      "name": "Skip the middle two",
      "args": [
        [
          2,
          1,
          1,
          2
        ]
      ],
      "expected": 4
    },
    {
      "name": "Big ends",
      "args": [
        [
          10,
          1,
          1,
          10
        ]
      ],
      "expected": 20
    },
    {
      "name": "Empty street",
      "args": [
        []
      ],
      "expected": 0
    }
  ],
  "challenge": {
    "question": "What is the most you can rob (never two neighbouring houses)?",
    "input": "[2,1,1,2]",
    "options": [
      "4",
      "8",
      "5",
      "3"
    ],
    "answer": 0,
    "explanation": "Robbing the first and the last house gives 2 + 2 = 4. Any pair of neighbours is blocked, so nothing beats it."
  },
  "memory": {
    "remember": "At each house: rob it (and skip the last) or skip it —\nkeep the better of the two.",
    "pattern": "Two rolling variables"
  }
};

export default problem;
