// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H042",
  "number": 42,
  "slug": "counting-sort",
  "title": "Counting Sort",
  "category": "Sorting Algorithms",
  "definition": "Sort small non-negative integers by counting occurrences.",
  "example": {
    "input": "[4,2,2,8,3,3,1]",
    "output": "[1,2,2,3,3,4,8]"
  },
  "approach": "Instead of comparing, just count how many 1s, 2s, 3s… there are, then write them out in order.",
  "keyIdea": [
    "Make a count array up to the max value",
    "count[x]++ for each number",
    "Write each value count[x] times"
  ],
  "time": "O(n + k)",
  "space": "O(k)",
  "complexityWhy": "k = largest value. Great when k is small.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums",
        "v": [
          4,
          2,
          2,
          8,
          3,
          3,
          1
        ]
      },
      {
        "l": "count",
        "v": [
          0,
          1,
          2,
          2,
          1,
          0,
          0,
          0,
          1
        ],
        "ix": 1,
        "hi": [
          1,
          2,
          3,
          4,
          8
        ]
      },
      {
        "l": "sorted",
        "v": [
          1,
          2,
          2,
          3,
          3,
          4,
          8
        ],
        "ok": [
          0,
          1,
          2,
          3,
          4,
          5,
          6
        ]
      }
    ],
    "cap": "count[3] = 2 means two 3s. Index = value."
  },
  "code": "class Solution {\n  public int[] countingSort(int[] arr) {\n    int max = 0;\n    for (int n : arr) max = Math.max(max, n);\n    int[] count = new int[max + 1];\n    for (int n : arr) count[n]++;                      // tally\n    int[] result = new int[arr.length];\n    int k = 0;\n    for (int value = 0; value <= max; value++) {\n      for (int times = 0; times < count[value]; times++) result[k++] = value;\n    }\n    return result;\n  }\n}",
  "method": "countingSort",
  "defaultInput": "[4,2,2,8,3,3,1]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          4,
          2,
          2,
          8,
          3,
          3,
          1
        ]
      ],
      "expected": [
        1,
        2,
        2,
        3,
        3,
        4,
        8
      ]
    },
    {
      "name": "Already sorted",
      "args": [
        [
          1,
          2,
          3,
          4
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          3
        ]
      ],
      "expected": [
        3
      ]
    },
    {
      "name": "All same",
      "args": [
        [
          2,
          2,
          2
        ]
      ],
      "expected": [
        2,
        2,
        2
      ]
    },
    {
      "name": "With zero",
      "args": [
        [
          0,
          3,
          0,
          1
        ]
      ],
      "expected": [
        0,
        0,
        1,
        3
      ]
    },
    {
      "name": "Reversed",
      "args": [
        [
          5,
          4,
          3,
          2,
          1
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5
      ]
    }
  ],
  "challenge": {
    "question": "For [4,2,2,8,3,3,1], what is count[3] — the number of 3s?",
    "input": "[4,2,2,8,3,3,1]",
    "options": [
      "1",
      "2",
      "3",
      "0"
    ],
    "answer": 1,
    "explanation": "The value 3 appears twice, so count[3] = 2 — the array index is the value itself."
  },
  "memory": {
    "remember": "Count each value,\nthen write it back that many times.",
    "pattern": "Count → Rewrite"
  }
};

export default problem;
