// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H146",
  "number": 146,
  "slug": "smallest-range-covering-elements-from-k-lists",
  "title": "Smallest Range Covering Elements from K Lists",
  "category": "Heap / Priority Queue",
  "definition": "Find the smallest range [a, b] that contains at least one number from each sorted list.",
  "example": {
    "input": "[[4,10,15,24,26],[0,9,12,20],[5,18,22,30]]",
    "output": "[20,24]"
  },
  "approach": "Put every number in one sorted list (remember which list it came from) and slide a window until it touches every list.",
  "keyIdea": [
    "Merge all numbers with their list id and sort",
    "Slide a window; count how many lists are covered",
    "Shrink from the left while all lists are still covered"
  ],
  "time": "O(N log N)",
  "space": "O(N)",
  "complexityWhy": "N = total numbers. Sorting everything.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "list 1",
        "v": [
          4,
          10,
          15,
          24,
          26
        ],
        "ok": [
          3
        ]
      },
      {
        "l": "list 2",
        "v": [
          0,
          9,
          12,
          20
        ],
        "ok": [
          3
        ]
      },
      {
        "l": "list 3",
        "v": [
          5,
          18,
          22,
          30
        ],
        "ok": [
          2
        ]
      }
    ],
    "cap": "24, 20 and 22 are the closest trio → range [20, 24]."
  },
  "better": {
    "name": "Min-heap holding one element per list",
    "time": "O(N log k)",
    "space": "O(k)",
    "code": "class Solution {\n  public int[] smallestRange(List<List<Integer>> nums) {\n    PriorityQueue<int[]> heap = new PriorityQueue<>((a, b) -> Integer.compare(a[0], b[0]));   // {value, list, index}\n    int max = Integer.MIN_VALUE;\n    for (int i = 0; i < nums.size(); i++) {\n      int v = nums.get(i).get(0);\n      heap.add(new int[]{v, i, 0});\n      max = Math.max(max, v);\n    }\n    int[] best = {heap.peek()[0], max};\n    while (true) {\n      int[] top = heap.poll();                                // current minimum\n      int value = top[0], i = top[1], j = top[2];\n      if (max - value < best[1] - best[0]) best = new int[]{value, max};\n      if (j + 1 == nums.get(i).size()) break;                 // a list ran out -> can't cover all\n      int next = nums.get(i).get(j + 1);\n      heap.add(new int[]{next, i, j + 1});\n      max = Math.max(max, next);\n    }\n    return best;\n  }\n}"
  },
  "code": "class Solution {\n  public int[] smallestRange(List<List<Integer>> nums) {\n    List<int[]> pairs = new ArrayList<>();                    // {value, which list}\n    for (int id = 0; id < nums.size(); id++)\n      for (int v : nums.get(id)) pairs.add(new int[]{v, id});\n    pairs.sort((a, b) -> Integer.compare(a[0], b[0]));\n    int[] count = new int[nums.size()];\n    int covered = 0, left = 0;\n    int[] best = {0, Integer.MAX_VALUE};\n    for (int right = 0; right < pairs.size(); right++) {\n      if (count[pairs.get(right)[1]]++ == 0) covered++;\n      while (covered == nums.size()) {                        // window touches every list\n        int lo = pairs.get(left)[0], hi = pairs.get(right)[0];\n        if (hi - lo < best[1] - best[0]) best = new int[]{lo, hi};\n        if (--count[pairs.get(left)[1]] == 0) covered--;\n        left++;\n      }\n    }\n    return best;\n  }\n}",
  "method": "smallestRange",
  "defaultInput": "[[4,10,15,24,26],[0,9,12,20],[5,18,22,30]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            4,
            10,
            15,
            24,
            26
          ],
          [
            0,
            9,
            12,
            20
          ],
          [
            5,
            18,
            22,
            30
          ]
        ]
      ],
      "expected": [
        20,
        24
      ]
    },
    {
      "name": "Same lists",
      "args": [
        [
          [
            1,
            2,
            3
          ],
          [
            1,
            2,
            3
          ],
          [
            1,
            2,
            3
          ]
        ]
      ],
      "expected": [
        1,
        1
      ]
    },
    {
      "name": "One number each",
      "args": [
        [
          [
            1
          ],
          [
            2
          ],
          [
            3
          ]
        ]
      ],
      "expected": [
        1,
        3
      ]
    },
    {
      "name": "Repeated values",
      "args": [
        [
          [
            10,
            10
          ],
          [
            11,
            11
          ]
        ]
      ],
      "expected": [
        10,
        11
      ]
    },
    {
      "name": "Two lists",
      "args": [
        [
          [
            1,
            5
          ],
          [
            2,
            6
          ]
        ]
      ],
      "expected": [
        1,
        2
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          [
            -5,
            0
          ],
          [
            3,
            4
          ]
        ]
      ],
      "expected": [
        0,
        3
      ]
    }
  ],
  "challenge": {
    "question": "What is the smallest range that contains at least one number from every list?",
    "input": "[[1,5,9],[4,7],[2,8]]",
    "options": [
      "[7]",
      "[9,7]",
      "[7,9]",
      "[8,10]"
    ],
    "answer": 2,
    "explanation": "[7,9] contains 7 (second list), 8 (third list) and 9 (first list). Its width is 2, and no narrower range touches all three lists."
  },
  "memory": {
    "remember": "Hold one number per list in a min-heap;\nthe range is the heap's min to the biggest number seen.",
    "pattern": "Min-heap holding one element per list"
  }
};

export default problem;
