// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H014",
  "number": 14,
  "slug": "find-common-elements-between-two-arrays",
  "title": "Find Common Elements Between Two Arrays",
  "category": "Arrays",
  "definition": "Return the values that appear in both arrays.",
  "example": {
    "input": "[1,2,2,3,4], [2,2,4,6]",
    "output": "[2,4]"
  },
  "approach": "Put the second array in a HashSet so lookups are instant. Then check each number of the first array.",
  "keyIdea": [
    "Put array b in a HashSet",
    "For each number in a: is it in the set?",
    "Add it to the result (a LinkedHashSet skips repeats)"
  ],
  "time": "O(n+m)",
  "space": "O(n+m)",
  "complexityWhy": "Set lookups are O(1).",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "a",
        "v": [
          1,
          2,
          2,
          3,
          4
        ],
        "ok": [
          1,
          2,
          4
        ]
      },
      {
        "l": "b",
        "v": [
          2,
          2,
          4,
          6
        ],
        "ok": [
          0,
          1,
          2
        ]
      },
      {
        "l": "both",
        "v": [
          2,
          4
        ],
        "ok": [
          0,
          1
        ]
      }
    ],
    "cap": "Green values appear in both arrays."
  },
  "code": "class Solution {\n  public List<Integer> commonElements(int[] a, int[] b) {\n    Set<Integer> inB = new HashSet<>();                // O(1) lookups\n    for (int x : b) inB.add(x);\n    Set<Integer> result = new LinkedHashSet<>();       // keeps order, no repeats\n    for (int x : a) if (inB.contains(x)) result.add(x);\n    return new ArrayList<>(result);\n  }\n}",
  "method": "commonElements",
  "defaultInput": "[1,2,2,3,4], [2,2,4,6]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          2,
          3,
          4
        ],
        [
          2,
          2,
          4,
          6
        ]
      ],
      "expected": [
        2,
        4
      ]
    },
    {
      "name": "No overlap",
      "args": [
        [
          1,
          2
        ],
        [
          3,
          4
        ]
      ],
      "expected": []
    },
    {
      "name": "Identical",
      "args": [
        [
          1,
          2,
          3
        ],
        [
          1,
          2,
          3
        ]
      ],
      "expected": [
        1,
        2,
        3
      ]
    },
    {
      "name": "Empty",
      "args": [
        [],
        [
          1
        ]
      ],
      "expected": []
    },
    {
      "name": "Repeats",
      "args": [
        [
          5,
          5,
          5
        ],
        [
          5
        ]
      ],
      "expected": [
        5
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          -1,
          0,
          2
        ],
        [
          2,
          -1,
          9
        ]
      ],
      "expected": [
        -1,
        2
      ]
    }
  ],
  "challenge": {
    "question": "Which values appear in both arrays?",
    "input": "[4,9,5,9], [9,4,9,8,4]",
    "options": [
      "[9,4]",
      "[4]",
      "[4,9]",
      "[5,10]"
    ],
    "answer": 2,
    "explanation": "4 and 9 are in both arrays. Each common value is reported once, using a Set for instant lookups."
  },
  "memory": {
    "remember": "Put one array in a Set —\nlookups are instant.",
    "pattern": "Set lookup"
  }
};

export default problem;
