// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H082",
  "number": 82,
  "slug": "insert-delete-in-bst",
  "title": "Insert & Delete in BST",
  "category": "Trees",
  "definition": "Insert a value and delete a value while keeping BST order.",
  "example": {
    "input": "[5,3,6,2,4,null,7]: insert 1, delete 3",
    "output": "[5,4,6,2,null,null,7,1]"
  },
  "approach": "Go left if smaller, right if bigger. To delete a node with two children, replace it with the smallest value in its right subtree.",
  "keyIdea": [
    "Insert: walk down and attach at a null spot",
    "Delete: 0 or 1 child → replace with the child",
    "2 children → copy the inorder successor, delete it"
  ],
  "time": "O(h)",
  "space": "O(h)",
  "complexityWhy": "h = height. O(log n) if balanced, O(n) if skewed.",
  "figure": [
    {
      "k": "tree",
      "v": [
        5,
        3,
        6,
        2,
        4,
        null,
        7,
        1
      ],
      "hi": [
        1
      ],
      "cap": "After inserting 1."
    },
    {
      "k": "tree",
      "v": [
        5,
        4,
        6,
        2,
        null,
        null,
        7,
        1
      ],
      "ok": [
        4
      ],
      "cap": "After deleting 3: its successor 4 takes its place."
    }
  ],
  "code": "class Solution {\n  public TreeNode insertIntoBST(TreeNode root, int val) {\n    if (root == null) return new TreeNode(val);\n    if (val < root.val) root.left = insertIntoBST(root.left, val);\n    else root.right = insertIntoBST(root.right, val);\n    return root;\n  }\n  public TreeNode deleteNode(TreeNode root, int key) {\n    if (root == null) return null;\n    if (key < root.val) root.left = deleteNode(root.left, key);\n    else if (key > root.val) root.right = deleteNode(root.right, key);\n    else {\n      if (root.left == null) return root.right;         // 0 or 1 child\n      if (root.right == null) return root.left;\n      TreeNode successor = root.right;                  // 2 children: smallest of the right side\n      while (successor.left != null) successor = successor.left;\n      root.val = successor.val;\n      root.right = deleteNode(root.right, successor.val);\n    }\n    return root;\n  }\n}",
  "method": "Solution",
  "defaultInput": "[], [[\"insertIntoBST\",[5,3,6,2,4,null,7],1],[\"deleteNode\",[5,3,6,2,4,null,7],3]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [],
        [
          [
            "insertIntoBST",
            [
              5,
              3,
              6,
              2,
              4,
              null,
              7
            ],
            1
          ],
          [
            "deleteNode",
            [
              5,
              3,
              6,
              2,
              4,
              null,
              7
            ],
            3
          ]
        ]
      ],
      "expected": [
        [
          5,
          3,
          6,
          2,
          4,
          null,
          7,
          1
        ],
        [
          5,
          4,
          6,
          2,
          null,
          null,
          7
        ]
      ]
    },
    {
      "name": "Insert into an empty tree",
      "args": [
        [],
        [
          [
            "insertIntoBST",
            [],
            7
          ]
        ]
      ],
      "expected": [
        [
          7
        ]
      ]
    },
    {
      "name": "Delete a leaf",
      "args": [
        [],
        [
          [
            "deleteNode",
            [
              5,
              3,
              6,
              2,
              4
            ],
            2
          ]
        ]
      ],
      "expected": [
        [
          5,
          3,
          6,
          null,
          4
        ]
      ]
    },
    {
      "name": "Delete a node with one child",
      "args": [
        [],
        [
          [
            "deleteNode",
            [
              5,
              3,
              6,
              2
            ],
            3
          ]
        ]
      ],
      "expected": [
        [
          5,
          2,
          6
        ]
      ]
    },
    {
      "name": "Delete a node with two children",
      "args": [
        [],
        [
          [
            "deleteNode",
            [
              5,
              3,
              6,
              2,
              4,
              null,
              7
            ],
            5
          ]
        ]
      ],
      "expected": [
        [
          6,
          3,
          7,
          2,
          4
        ]
      ]
    },
    {
      "name": "Delete a missing value",
      "args": [
        [],
        [
          [
            "deleteNode",
            [
              5,
              3,
              6
            ],
            10
          ]
        ]
      ],
      "expected": [
        [
          5,
          3,
          6
        ]
      ]
    }
  ],
  "challenge": {
    "question": "After inserting 5, what does the tree look like (level order)?",
    "input": "[], [[\"insertIntoBST\",[4,2,7,1,3],5]]",
    "options": [
      "[4,2,7,1,3,5]",
      "[1,2,3,4,5,7]",
      "[5,3,1,7,2,4]",
      "[4,2,7,1,3]"
    ],
    "answer": 0,
    "explanation": "5 > 4 → go right; 5 < 7 → go left; 7's left side is empty, so 5 goes there: [4,2,7,1,3,5]."
  },
  "memory": {
    "remember": "Insert: walk left or right to an empty spot.\nDelete: replace with the smallest on the right.",
    "pattern": "BST Insert / Delete (Inorder Successor)"
  }
};

export default problem;
