// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H036",
  "number": 36,
  "slug": "bubble-sort",
  "title": "Bubble Sort",
  "category": "Sorting Algorithms",
  "definition": "Repeatedly swap neighbours that are out of order.",
  "example": {
    "input": "[5,2,9,1,5,6]",
    "output": "[1,2,5,5,6,9]"
  },
  "approach": "Repeatedly swap neighbours that are in the wrong order. The biggest value bubbles to the end on every pass. If a pass swaps nothing, stop.",
  "keyIdea": [
    "Compare each neighbouring pair",
    "Swap if left > right",
    "After each pass the largest value is in place",
    "No swaps in a pass → sorted, stop"
  ],
  "time": "O(n) best, O(n²) worst",
  "space": "O(1)",
  "complexityWhy": "On sorted input the early stop makes it O(n).",
  "figure": {
    "k": "bars",
    "r": [
      {
        "l": "start",
        "v": [
          5,
          2,
          9,
          1,
          5,
          6
        ]
      },
      {
        "l": "pass 1",
        "v": [
          2,
          5,
          1,
          5,
          6,
          9
        ],
        "ok": [
          5
        ]
      },
      {
        "l": "pass 2",
        "v": [
          2,
          1,
          5,
          5,
          6,
          9
        ],
        "ok": [
          4,
          5
        ]
      },
      {
        "l": "done",
        "v": [
          1,
          2,
          5,
          5,
          6,
          9
        ],
        "ok": [
          0,
          1,
          2,
          3,
          4,
          5
        ]
      }
    ],
    "h": 44,
    "cap": "The biggest value moves to the right each pass."
  },
  "code": "class Solution {\n  public int[] bubbleSort(int[] arr) {\n    for (int pass = 0; pass < arr.length - 1; pass++) {\n      boolean swapped = false;\n      for (int i = 0; i < arr.length - 1 - pass; i++) {\n        if (arr[i] > arr[i + 1]) {\n          int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;\n          swapped = true;\n        }\n      }\n      if (!swapped) break;                             // already sorted -> stop\n    }\n    return arr;\n  }\n}",
  "method": "bubbleSort",
  "defaultInput": "[5,2,9,1,5,6]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          5,
          2,
          9,
          1,
          5,
          6
        ]
      ],
      "expected": [
        1,
        2,
        5,
        5,
        6,
        9
      ]
    },
    {
      "name": "Already sorted",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "name": "Reversed",
      "args": [
        [
          5,
          4,
          3,
          2,
          1
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          7
        ]
      ],
      "expected": [
        7
      ]
    },
    {
      "name": "Empty",
      "args": [
        []
      ],
      "expected": []
    },
    {
      "name": "Duplicates",
      "args": [
        [
          3,
          3,
          1,
          1,
          2,
          2
        ]
      ],
      "expected": [
        1,
        1,
        2,
        2,
        3,
        3
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          0,
          -3,
          8,
          -1
        ]
      ],
      "expected": [
        -3,
        -1,
        0,
        8
      ]
    }
  ],
  "challenge": {
    "question": "After the first pass, what does the array look like?",
    "input": "[5,2,9,1,5,6]",
    "options": [
      "[5,2,9,1,5,6]",
      "[2,5,1,5,6,9]",
      "[2,1,5,5,6,9]",
      "[1,2,5,5,6,9]"
    ],
    "answer": 1,
    "explanation": "Pass 1 swaps neighbours left to right, carrying the biggest value (9) all the way to the end: [2,5,1,5,6,9]."
  },
  "memory": {
    "remember": "Each pass floats the biggest value\nto the right.",
    "pattern": "Early exit when a pass makes no swaps"
  }
};

export default problem;
