// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H098",
  "number": 98,
  "slug": "floyd-warshall",
  "title": "Floyd–Warshall (All-Pairs Shortest Path)",
  "category": "Graph",
  "definition": "Shortest distance between every pair of nodes.",
  "example": {
    "input": "4 nodes: 0→1 (5), 0→3 (10), 1→2 (3), 2→3 (1)",
    "output": "4×4 distance matrix"
  },
  "approach": "Try every node k as a stop-over: if i → k → j is shorter than i → j, update it.",
  "keyIdea": [
    "dist[i][j] = edge weight, 0 on the diagonal, ∞ otherwise",
    "For each k, for each i, for each j",
    "dist[i][k] + dist[k][j] < dist[i][j] → update"
  ],
  "time": "O(V³)",
  "space": "O(V²)",
  "complexityWhy": "Three nested loops over V.",
  "figure": {
    "k": "grid",
    "v": [
      [
        0,
        5,
        8,
        9
      ],
      [
        "∞",
        0,
        3,
        4
      ],
      [
        "∞",
        "∞",
        0,
        1
      ],
      [
        "∞",
        "∞",
        "∞",
        0
      ]
    ],
    "hi": [
      [
        0,
        3
      ]
    ],
    "cap": "0 → 3 costs 9 through 1 and 2, cheaper than the direct edge (10)."
  },
  "code": "class Solution {\n  public int[][] allPairs(int n, int[][] edges) {\n    final int INF = Integer.MAX_VALUE;\n    int[][] dist = new int[n][n];\n    for (int[] row : dist) Arrays.fill(row, INF);\n    for (int i = 0; i < n; i++) dist[i][i] = 0;\n    for (int[] e : edges) dist[e[0]][e[1]] = Math.min(dist[e[0]][e[1]], e[2]);\n    for (int k = 0; k < n; k++) {                      // allow node k as a stop-over\n      for (int i = 0; i < n; i++) {\n        for (int j = 0; j < n; j++) {\n          if (dist[i][k] != INF && dist[k][j] != INF && dist[i][k] + dist[k][j] < dist[i][j]) {\n            dist[i][j] = dist[i][k] + dist[k][j];\n          }\n        }\n      }\n    }\n    return dist;\n  }\n}",
  "method": "allPairs",
  "defaultInput": "4, [[0,1,5],[0,3,10],[1,2,3],[2,3,1]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        4,
        [
          [
            0,
            1,
            5
          ],
          [
            0,
            3,
            10
          ],
          [
            1,
            2,
            3
          ],
          [
            2,
            3,
            1
          ]
        ]
      ],
      "expected": [
        [
          0,
          5,
          8,
          9
        ],
        [
          2147483647,
          0,
          3,
          4
        ],
        [
          2147483647,
          2147483647,
          0,
          1
        ],
        [
          2147483647,
          2147483647,
          2147483647,
          0
        ]
      ]
    },
    {
      "name": "Single node",
      "args": [
        1,
        []
      ],
      "expected": [
        [
          0
        ]
      ]
    },
    {
      "name": "Two nodes",
      "args": [
        2,
        [
          [
            0,
            1,
            3
          ]
        ]
      ],
      "expected": [
        [
          0,
          3
        ],
        [
          2147483647,
          0
        ]
      ]
    },
    {
      "name": "A cycle",
      "args": [
        3,
        [
          [
            0,
            1,
            1
          ],
          [
            1,
            2,
            1
          ],
          [
            2,
            0,
            1
          ]
        ]
      ],
      "expected": [
        [
          0,
          1,
          2
        ],
        [
          2,
          0,
          1
        ],
        [
          1,
          2,
          0
        ]
      ]
    },
    {
      "name": "Parallel edges",
      "args": [
        2,
        [
          [
            0,
            1,
            5
          ],
          [
            0,
            1,
            2
          ]
        ]
      ],
      "expected": [
        [
          0,
          2
        ],
        [
          2147483647,
          0
        ]
      ]
    },
    {
      "name": "Negative edge",
      "args": [
        3,
        [
          [
            0,
            1,
            2
          ],
          [
            1,
            2,
            -1
          ]
        ]
      ],
      "expected": [
        [
          0,
          2,
          1
        ],
        [
          2147483647,
          0,
          -1
        ],
        [
          2147483647,
          2147483647,
          0
        ]
      ]
    }
  ],
  "challenge": {
    "question": "What is the shortest distance from node 0 to node 3?",
    "input": "4, [[0,1,5],[0,3,10],[1,2,3],[2,3,1]]",
    "options": [
      "18",
      "12",
      "9",
      "7"
    ],
    "answer": 2,
    "explanation": "The direct edge 0→3 costs 10, but 0→1→2→3 costs 5 + 3 + 1 = 9."
  },
  "memory": {
    "remember": "Allow node k as a stop-over for every pair (i, j):\nthree nested loops.",
    "pattern": "Floyd–Warshall (3 nested loops)"
  }
};

export default problem;
