// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H028",
  "number": 28,
  "slug": "longest-repeating-character-replacement",
  "title": "Longest Repeating Character Replacement",
  "category": "Strings",
  "definition": "You may change at most k letters. Find the longest stretch made of one repeated letter.",
  "example": {
    "input": "s = \"AABABBA\", k = 1",
    "output": "4"
  },
  "approach": "A window is fine if (window size − count of its most common letter) ≤ k, because we can replace the rest.",
  "keyIdea": [
    "For each start, expand right",
    "Track counts and the most common letter",
    "Stop when replacements needed > k"
  ],
  "time": "O(n²)",
  "space": "O(1)",
  "complexityWhy": "Every start expands forward.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "A",
          "A",
          "B",
          "A",
          "B",
          "B",
          "A"
        ],
        "ok": [
          0,
          1,
          3
        ],
        "no": [
          2
        ],
        "br": [
          [
            0,
            3,
            "AABA → 4"
          ]
        ]
      }
    ],
    "cap": "Change one B to A → AAAA (length 4)."
  },
  "better": {
    "name": "Sliding window",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int characterReplacement(String s, int k) {\n    int[] count = new int[26];                          // letters A-Z\n    int left = 0, maxFreq = 0, best = 0;\n    for (int right = 0; right < s.length(); right++) {\n      maxFreq = Math.max(maxFreq, ++count[s.charAt(right) - 'A']);\n      while (right - left + 1 - maxFreq > k) {          // too many replacements\n        count[s.charAt(left) - 'A']--;\n        left++;\n      }\n      best = Math.max(best, right - left + 1);\n    }\n    return best;\n  }\n}"
  },
  "code": "class Solution {\n  public int characterReplacement(String s, int k) {\n    int best = 0;\n    for (int start = 0; start < s.length(); start++) {\n      int[] count = new int[26];\n      int maxFreq = 0;\n      for (int end = start; end < s.length(); end++) {\n        maxFreq = Math.max(maxFreq, ++count[s.charAt(end) - 'A']);\n        int size = end - start + 1;\n        if (size - maxFreq <= k) best = Math.max(best, size);\n        else break;                                     // needs more than k changes\n      }\n    }\n    return best;\n  }\n}",
  "method": "characterReplacement",
  "defaultInput": "\"AABABBA\", 1",
  "tests": [
    {
      "name": "Example",
      "args": [
        "AABABBA",
        1
      ],
      "expected": 4
    },
    {
      "name": "k = 0",
      "args": [
        "AABBB",
        0
      ],
      "expected": 3
    },
    {
      "name": "Replace all",
      "args": [
        "ABCD",
        3
      ],
      "expected": 4
    },
    {
      "name": "Single",
      "args": [
        "A",
        0
      ],
      "expected": 1
    },
    {
      "name": "Already same",
      "args": [
        "AAAA",
        2
      ],
      "expected": 4
    },
    {
      "name": "Alternating",
      "args": [
        "ABAB",
        2
      ],
      "expected": 4
    }
  ],
  "challenge": {
    "question": "What is the longest same-letter run after at most k replacements?",
    "input": "\"AAABBCB\", 2",
    "options": [
      "5",
      "6",
      "2",
      "3"
    ],
    "answer": 0,
    "explanation": "The window \"AAABB\" has 3 A's; replacing the 2 B's (k = 2) gives a run of 5 A's."
  },
  "memory": {
    "remember": "A window is valid while\nsize − (most common letter) ≤ k.",
    "pattern": "Sliding Window + Max Frequency"
  }
};

export default problem;
