// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H127",
  "number": 127,
  "slug": "longest-common-subsequence",
  "title": "Longest Common Subsequence (LCS)",
  "category": "Dynamic Programming",
  "definition": "Length of the longest sequence of letters that appears in both strings in the same order (gaps allowed).",
  "example": {
    "input": "\"abcde\", \"ace\"",
    "output": "3  (ace)"
  },
  "approach": "Compare the first letters. If equal, count 1 and move both on. If not, try skipping a letter from either string.",
  "keyIdea": [
    "Equal letters → 1 + LCS(rest, rest)",
    "Different → max(skip a letter of a, skip a letter of b)"
  ],
  "time": "O(2^(m+n))",
  "space": "O(m+n)",
  "complexityWhy": "Overlapping sub-problems.",
  "figure": {
    "k": "grid",
    "v": [
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        1,
        1,
        1
      ],
      [
        0,
        1,
        1,
        1
      ],
      [
        0,
        1,
        2,
        2
      ],
      [
        0,
        1,
        2,
        2
      ],
      [
        0,
        1,
        2,
        3
      ]
    ],
    "rl": [
      "",
      "a",
      "b",
      "c",
      "d",
      "e"
    ],
    "cl": [
      "",
      "a",
      "c",
      "e"
    ],
    "ok": [
      [
        5,
        3
      ]
    ],
    "cap": "Rows = abcde, columns = ace. The bottom-right cell is the answer."
  },
  "better": {
    "name": "DP table with two rolling rows",
    "time": "O(m·n)",
    "space": "O(n)",
    "code": "class Solution {\n  public int longestCommonSubsequence(String a, String b) {\n    int[] prev = new int[b.length() + 1], curr = new int[b.length() + 1];\n    for (int i = 1; i <= a.length(); i++) {\n      for (int j = 1; j <= b.length(); j++) {\n        if (a.charAt(i - 1) == b.charAt(j - 1)) curr[j] = prev[j - 1] + 1;\n        else curr[j] = Math.max(prev[j], curr[j - 1]);\n      }\n      int[] t = prev; prev = curr; curr = t;                // last row becomes the previous row\n    }\n    return prev[b.length()];\n  }\n}"
  },
  "code": "class Solution {\n  public int longestCommonSubsequence(String a, String b) {\n    return lcs(a, b, a.length(), b.length());\n  }\n  private int lcs(String a, String b, int i, int j) {      // using the first i / j letters\n    if (i == 0 || j == 0) return 0;\n    if (a.charAt(i - 1) == b.charAt(j - 1)) return 1 + lcs(a, b, i - 1, j - 1);    // letters match\n    return Math.max(lcs(a, b, i - 1, j), lcs(a, b, i, j - 1));                     // drop a letter from a or b\n  }\n}",
  "method": "longestCommonSubsequence",
  "defaultInput": "\"abcde\", \"ace\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "abcde",
        "ace"
      ],
      "expected": 3
    },
    {
      "name": "Identical",
      "args": [
        "abc",
        "abc"
      ],
      "expected": 3
    },
    {
      "name": "Nothing in common",
      "args": [
        "abc",
        "def"
      ],
      "expected": 0
    },
    {
      "name": "Empty string",
      "args": [
        "",
        "abc"
      ],
      "expected": 0
    },
    {
      "name": "Classic",
      "args": [
        "AGGTAB",
        "GXTXAYB"
      ],
      "expected": 4
    },
    {
      "name": "Repeated letters",
      "args": [
        "aaaa",
        "aa"
      ],
      "expected": 2
    }
  ],
  "challenge": {
    "question": "What is the length of the longest common subsequence?",
    "input": "\"abcde\", \"bdxe\"",
    "options": [
      "3",
      "1",
      "5",
      "2"
    ],
    "answer": 0,
    "explanation": "\"bde\" appears in both strings in the same order (b, d, e), so the length is 3."
  },
  "memory": {
    "remember": "Matching letters extend the diagonal;\notherwise take the better of up or left.",
    "pattern": "2-D DP on Two Strings"
  }
};

export default problem;
