// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H064",
  "number": 64,
  "slug": "find-minimum-in-rotated-sorted-array",
  "title": "Find Minimum in Rotated Sorted Array",
  "category": "Binary Search",
  "definition": "Find the smallest element of a rotated sorted array.",
  "example": {
    "input": "[4,5,6,7,0,1,2]",
    "output": "0"
  },
  "approach": "Compare mid with the last element. If mid is bigger, the minimum is on the right; otherwise it is at mid or on the left.",
  "keyIdea": [
    "lo = 0, hi = n − 1",
    "nums[mid] > nums[hi] → lo = mid + 1",
    "Otherwise hi = mid",
    "When lo == hi that is the minimum"
  ],
  "time": "O(log n)",
  "space": "O(1)",
  "complexityWhy": "Binary search on the rotation point.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          4,
          5,
          6,
          7,
          0,
          1,
          2
        ],
        "no": [
          3
        ],
        "ok": [
          4
        ],
        "p": {
          "3": "drop",
          "4": "min"
        }
      }
    ],
    "cap": "Compare mid with the right end to know which side holds the drop."
  },
  "code": "class Solution {\n  public int findMin(int[] nums) {\n    int lo = 0, hi = nums.length - 1;\n    while (lo < hi) {\n      int mid = lo + (hi - lo) / 2;\n      if (nums[mid] > nums[hi]) lo = mid + 1;   // minimum is on the right\n      else hi = mid;                            // mid could be the minimum\n    }\n    return nums[lo];\n  }\n}",
  "method": "findMin",
  "defaultInput": "[4,5,6,7,0,1,2]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          4,
          5,
          6,
          7,
          0,
          1,
          2
        ]
      ],
      "expected": 0
    },
    {
      "name": "Not rotated",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": 1
    },
    {
      "name": "Rotated once",
      "args": [
        [
          2,
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Single element",
      "args": [
        [
          7
        ]
      ],
      "expected": 7
    },
    {
      "name": "Minimum at the end",
      "args": [
        [
          3,
          4,
          5,
          1,
          2
        ]
      ],
      "expected": 1
    },
    {
      "name": "Large rotation",
      "args": [
        [
          11,
          13,
          15,
          17,
          1,
          2,
          3
        ]
      ],
      "expected": 1
    }
  ],
  "challenge": {
    "question": "What is the minimum value?",
    "input": "[5,6,7,8,9,1,2,3]",
    "options": [
      "2",
      "4",
      "0",
      "1"
    ],
    "answer": 3,
    "explanation": "The smallest value sits right after the drop: after 9 comes 1, so the minimum is 1."
  },
  "memory": {
    "remember": "Compare the middle with the right end —\nthe minimum is on the side that drops.",
    "pattern": "Binary search on the drop point"
  }
};

export default problem;
