// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H037",
  "number": 37,
  "slug": "selection-sort",
  "title": "Selection Sort",
  "category": "Sorting Algorithms",
  "definition": "Repeatedly pick the smallest remaining value.",
  "example": {
    "input": "[5,2,9,1,5,6]",
    "output": "[1,2,5,5,6,9]"
  },
  "approach": "Find the smallest number and put it first. Then find the smallest of the rest and put it second. And so on.",
  "keyIdea": [
    "For position i, find the minimum in arr[i..]",
    "Swap it into position i",
    "Move to i + 1"
  ],
  "time": "O(n²)",
  "space": "O(1)",
  "complexityWhy": "Always scans the whole unsorted part. Only n swaps.",
  "figure": {
    "k": "bars",
    "r": [
      {
        "l": "start",
        "v": [
          5,
          2,
          9,
          1,
          5,
          6
        ]
      },
      {
        "l": "step 1",
        "v": [
          1,
          2,
          9,
          5,
          5,
          6
        ],
        "ok": [
          0
        ]
      },
      {
        "l": "step 2",
        "v": [
          1,
          2,
          9,
          5,
          5,
          6
        ],
        "ok": [
          0,
          1
        ]
      },
      {
        "l": "step 3",
        "v": [
          1,
          2,
          5,
          9,
          5,
          6
        ],
        "ok": [
          0,
          1,
          2
        ]
      }
    ],
    "h": 44,
    "cap": "The sorted part grows from the left."
  },
  "code": "class Solution {\n  public int[] selectionSort(int[] arr) {\n    for (int i = 0; i < arr.length - 1; i++) {\n      int minIndex = i;\n      for (int j = i + 1; j < arr.length; j++) {\n        if (arr[j] < arr[minIndex]) minIndex = j;      // new smallest\n      }\n      int temp = arr[i]; arr[i] = arr[minIndex]; arr[minIndex] = temp;\n    }\n    return arr;\n  }\n}",
  "method": "selectionSort",
  "defaultInput": "[5,2,9,1,5,6]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          5,
          2,
          9,
          1,
          5,
          6
        ]
      ],
      "expected": [
        1,
        2,
        5,
        5,
        6,
        9
      ]
    },
    {
      "name": "Already sorted",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "name": "Reversed",
      "args": [
        [
          5,
          4,
          3,
          2,
          1
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          7
        ]
      ],
      "expected": [
        7
      ]
    },
    {
      "name": "Empty",
      "args": [
        []
      ],
      "expected": []
    },
    {
      "name": "Duplicates",
      "args": [
        [
          3,
          3,
          1,
          1,
          2,
          2
        ]
      ],
      "expected": [
        1,
        1,
        2,
        2,
        3,
        3
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          0,
          -3,
          8,
          -1
        ]
      ],
      "expected": [
        -3,
        -1,
        0,
        8
      ]
    }
  ],
  "challenge": {
    "question": "After step 1 (position 0 is fixed), what does the array look like?",
    "input": "[5,2,9,1,5,6]",
    "options": [
      "[5,2,9,1,5,6]",
      "[1,2,9,5,5,6]",
      "[1,2,5,9,5,6]",
      "[1,2,5,5,6,9]"
    ],
    "answer": 1,
    "explanation": "The smallest value (1) is found and swapped into position 0, swapping places with the 5: [1,2,9,5,5,6]."
  },
  "memory": {
    "remember": "Pick the minimum of what's left,\nswap it to the front.",
    "pattern": "Select the Minimum"
  }
};

export default problem;
