// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H034",
  "number": 34,
  "slug": "find-all-anagrams-in-a-string",
  "title": "Find All Anagrams in a String",
  "category": "Strings",
  "definition": "Find every start position where a rearrangement (anagram) of p appears inside s.",
  "example": {
    "input": "s = \"cbaebabacd\", p = \"abc\"",
    "output": "[0,6]"
  },
  "approach": "Slide a window of p's length across s. Keep letter counts for the window and compare them with p's counts.",
  "keyIdea": [
    "Count the letters of p",
    "Add the new letter and remove the old one",
    "Counts are equal → record the start index"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass. Comparing 26 counters is O(1).",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "c",
          "b",
          "a",
          "e",
          "b",
          "a",
          "b",
          "a",
          "c",
          "d"
        ],
        "ok": [
          0,
          1,
          2
        ],
        "br": [
          [
            0,
            2,
            "cba"
          ]
        ]
      },
      {
        "v": [
          "c",
          "b",
          "a",
          "e",
          "b",
          "a",
          "b",
          "a",
          "c",
          "d"
        ],
        "ok": [
          6,
          7,
          8
        ],
        "br": [
          [
            6,
            8,
            "bac"
          ]
        ]
      }
    ],
    "cap": "Windows at index 0 and 6 are anagrams of abc."
  },
  "code": "class Solution {\n  public List<Integer> findAnagrams(String s, String p) {\n    List<Integer> result = new ArrayList<>();\n    int[] need = new int[26], have = new int[26];\n    for (char ch : p.toCharArray()) need[ch - 'a']++;\n    for (int i = 0; i < s.length(); i++) {\n      have[s.charAt(i) - 'a']++;                                    // letter enters\n      if (i >= p.length()) have[s.charAt(i - p.length()) - 'a']--;  // letter leaves\n      if (i >= p.length() - 1 && same(have, need)) result.add(i - p.length() + 1);\n    }\n    return result;\n  }\n  private boolean same(int[] a, int[] b) {\n    for (int i = 0; i < 26; i++) if (a[i] != b[i]) return false;\n    return true;\n  }\n}",
  "method": "findAnagrams",
  "defaultInput": "\"cbaebabacd\", \"abc\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "cbaebabacd",
        "abc"
      ],
      "expected": [
        0,
        6
      ]
    },
    {
      "name": "No match",
      "args": [
        "abc",
        "xyz"
      ],
      "expected": []
    },
    {
      "name": "Whole string",
      "args": [
        "ab",
        "ab"
      ],
      "expected": [
        0
      ]
    },
    {
      "name": "p longer",
      "args": [
        "a",
        "ab"
      ],
      "expected": []
    },
    {
      "name": "Overlapping",
      "args": [
        "abab",
        "ab"
      ],
      "expected": [
        0,
        1,
        2
      ]
    },
    {
      "name": "Single letters",
      "args": [
        "aaaa",
        "aa"
      ],
      "expected": [
        0,
        1,
        2
      ]
    }
  ],
  "challenge": {
    "question": "At which start indices does an anagram of p begin?",
    "input": "\"abxaba\", \"ab\"",
    "options": [
      "[0,3,4]",
      "[3,0,4]",
      "[1,4,5]",
      "[4,3,0]"
    ],
    "answer": 0,
    "explanation": "Windows of length 2 starting at 0 (\"ab\"), 3 (\"ab\") and 4 (\"ba\") are anagrams of \"ab\"."
  },
  "memory": {
    "remember": "Slide a fixed window and compare\nits letter counts with p.",
    "pattern": "Sliding window with letter counts"
  }
};

export default problem;
