// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H012",
  "number": 12,
  "slug": "find-duplicate-number",
  "title": "Find Duplicate Number",
  "category": "Arrays",
  "definition": "An array has n+1 numbers, each between 1 and n. One number appears more than once. Find it.",
  "example": {
    "input": "[1,3,4,2,2]",
    "output": "2"
  },
  "approach": "If you've seen a number before, it's the duplicate. A Set remembers what we've seen.",
  "keyIdea": [
    "Create an empty Set",
    "Check each number: seen before?",
    "If yes, that's the duplicate"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "One pass, but the Set uses extra memory.",
  "figure": {
    "k": "list",
    "v": [
      0,
      1,
      3,
      2,
      4
    ],
    "cyc": 3,
    "hi": [
      3
    ],
    "cap": "index → value forms a linked list. The cycle entrance (2) is the duplicate."
  },
  "better": {
    "name": "Floyd's cycle detection (no extra space)",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int findDuplicate(int[] nums) {\n    // treat index -> nums[index] as a linked list with a cycle\n    int slow = nums[0], fast = nums[0];\n    do { slow = nums[slow]; fast = nums[nums[fast]]; } while (slow != fast);\n    slow = nums[0];                        // restart one pointer\n    while (slow != fast) { slow = nums[slow]; fast = nums[fast]; }\n    return slow;                           // cycle entrance = duplicate\n  }\n}"
  },
  "code": "class Solution {\n  public int findDuplicate(int[] nums) {\n    Set<Integer> seen = new HashSet<>();\n    for (int n : nums) {\n      if (!seen.add(n)) return n;          // add() is false if it was already there\n    }\n    return -1;\n  }\n}",
  "method": "findDuplicate",
  "defaultInput": "[1,3,4,2,2]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          3,
          4,
          2,
          2
        ]
      ],
      "expected": 2
    },
    {
      "name": "Tiny",
      "args": [
        [
          1,
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Duplicate first",
      "args": [
        [
          3,
          1,
          3,
          4,
          2
        ]
      ],
      "expected": 3
    },
    {
      "name": "Everything repeated",
      "args": [
        [
          2,
          2,
          2,
          2,
          2
        ]
      ],
      "expected": 2
    },
    {
      "name": "Repeated three times",
      "args": [
        [
          2,
          5,
          9,
          6,
          9,
          3,
          8,
          9,
          7,
          1
        ]
      ],
      "expected": 9
    },
    {
      "name": "Duplicate at the end",
      "args": [
        [
          1,
          4,
          2,
          3,
          4
        ]
      ],
      "expected": 4
    }
  ],
  "challenge": {
    "question": "Which number is repeated?",
    "input": "[2,5,3,4,5,1]",
    "options": [
      "3",
      "7",
      "5",
      "4"
    ],
    "answer": 2,
    "explanation": "5 appears twice. The Set already contains 5 the second time we see it — that's the duplicate."
  },
  "memory": {
    "remember": "A Set remembers what you've seen —\nthe first repeat is the answer.",
    "pattern": "Seen-before Check (HashSet)"
  }
};

export default problem;
