// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H137",
  "number": 137,
  "slug": "palindrome-partitioning-ii",
  "title": "Palindrome Partitioning II",
  "category": "Dynamic Programming",
  "definition": "Minimum cuts so every piece is a palindrome.",
  "example": {
    "input": "\"aab\"",
    "output": "1  (aa | b)"
  },
  "approach": "Try every palindromic first piece, then solve the rest. Count one cut per piece.",
  "keyIdea": [
    "Try each prefix that is a palindrome",
    "cuts = 1 + cuts(rest)",
    "Keep the smallest"
  ],
  "time": "O(2ⁿ·n)",
  "space": "O(n)",
  "complexityWhy": "Overlapping sub-problems and repeated palindrome checks.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "a",
          "a",
          "b"
        ],
        "ok": [
          0,
          1
        ],
        "hi": [
          2
        ],
        "br": [
          [
            0,
            1,
            "aa"
          ],
          [
            2,
            2,
            "b"
          ]
        ]
      }
    ],
    "cap": "One cut between aa and b."
  },
  "better": {
    "name": "DP + expand around centres",
    "time": "O(n²)",
    "space": "O(n)",
    "code": "class Solution {\n  public int minCut(String s) {\n    int n = s.length();\n    int[] cuts = new int[n];                                // cuts[i]: fewest cuts for s[0..i]\n    for (int i = 0; i < n; i++) cuts[i] = i;                // worst case: cut between every letter\n    for (int center = 0; center < n; center++) {\n      for (int odd = 0; odd < 2; odd++) {                   // odd and even length palindromes\n        int l = center, r = center + odd;\n        while (l >= 0 && r < n && s.charAt(l) == s.charAt(r)) {\n          cuts[r] = Math.min(cuts[r], l == 0 ? 0 : cuts[l - 1] + 1);\n          l--; r++;\n        }\n      }\n    }\n    return cuts[n - 1];\n  }\n}"
  },
  "code": "class Solution {\n  public int minCut(String s) { return cut(s, 0); }\n  private int cut(String s, int start) {\n    if (isPalindrome(s, start, s.length() - 1)) return 0;   // the rest is already a palindrome\n    int best = Integer.MAX_VALUE;\n    for (int end = start; end < s.length() - 1; end++) {\n      if (isPalindrome(s, start, end)) best = Math.min(best, 1 + cut(s, end + 1));   // cut after 'end'\n    }\n    return best;\n  }\n  private boolean isPalindrome(String s, int l, int r) {\n    while (l < r) if (s.charAt(l++) != s.charAt(r--)) return false;\n    return true;\n  }\n}",
  "method": "minCut",
  "defaultInput": "\"aab\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "aab"
      ],
      "expected": 1
    },
    {
      "name": "Single letter",
      "args": [
        "a"
      ],
      "expected": 0
    },
    {
      "name": "Two letters",
      "args": [
        "ab"
      ],
      "expected": 1
    },
    {
      "name": "Already a palindrome",
      "args": [
        "aaaa"
      ],
      "expected": 0
    },
    {
      "name": "Odd palindrome",
      "args": [
        "abcba"
      ],
      "expected": 0
    },
    {
      "name": "No repeats",
      "args": [
        "abcd"
      ],
      "expected": 3
    }
  ],
  "challenge": {
    "question": "What is the minimum number of cuts to split \"abccbc\" into palindromes?",
    "input": "\"abccbc\"",
    "options": [
      "5",
      "2",
      "0",
      "4"
    ],
    "answer": 1,
    "explanation": "\"a\" | \"bccb\" | \"c\" — two cuts. One cut isn't enough because no split leaves two palindromes."
  },
  "memory": {
    "remember": "dp[i] = fewest cuts for the first i letters;\ntry every palindrome that ends at i.",
    "pattern": "Palindrome Table + Minimum Cuts"
  }
};

export default problem;
