// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H073",
  "number": 73,
  "slug": "diameter-of-binary-tree",
  "title": "Diameter of Binary Tree",
  "category": "Trees",
  "definition": "Length (in edges) of the longest path between any two nodes.",
  "example": {
    "input": "[1,2,3,4,5]",
    "output": "3"
  },
  "approach": "The longest path through a node = height(left) + height(right). While computing heights, remember the best value seen.",
  "keyIdea": [
    "height(null) = 0",
    "For each node: left + right = path through it",
    "Update best, return 1 + max(left, right)"
  ],
  "time": "O(n)",
  "space": "O(h)",
  "complexityWhy": "One pass over the tree.",
  "figure": {
    "k": "tree",
    "v": [
      1,
      2,
      3,
      4,
      5
    ],
    "ok": [
      4,
      2,
      1,
      3
    ],
    "cap": "Longest path 4 → 2 → 1 → 3 = 3 edges."
  },
  "code": "class Solution {\n  private int best;\n  public int diameterOfBinaryTree(TreeNode root) {\n    best = 0;\n    height(root);\n    return best;\n  }\n  private int height(TreeNode node) {\n    if (node == null) return 0;\n    int left = height(node.left), right = height(node.right);\n    best = Math.max(best, left + right);   // longest path bending here\n    return 1 + Math.max(left, right);\n  }\n}",
  "method": "diameterOfBinaryTree",
  "defaultInput": "[1,2,3,4,5]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": 3
    },
    {
      "name": "Two nodes",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": 1
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": 0
    },
    {
      "name": "Left chain",
      "args": [
        [
          1,
          2,
          null,
          3,
          null,
          4
        ]
      ],
      "expected": 3
    },
    {
      "name": "Path through a child",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          null,
          null,
          6
        ]
      ],
      "expected": 4
    },
    {
      "name": "Balanced",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          6,
          7
        ]
      ],
      "expected": 4
    }
  ],
  "challenge": {
    "question": "What is the diameter (longest path, counted in edges)?",
    "input": "[1,2,3,4,5,null,null,6]",
    "options": [
      "8",
      "7",
      "5",
      "4"
    ],
    "answer": 3,
    "explanation": "The longest path 6 → 4 → 2 → 1 → 3 has 4 edges. (It doesn't have to pass through the root, but here it does.)"
  },
  "memory": {
    "remember": "At every node: left height + right height.\nKeep the biggest.",
    "pattern": "One DFS: compute height and update the answer"
  }
};

export default problem;
