// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H092",
  "number": 92,
  "slug": "topological-sort",
  "title": "Topological Sort (Kahn's Algorithm / BFS)",
  "category": "Graph",
  "definition": "Order the nodes so every edge u → v has u before v.",
  "example": {
    "input": "n = 4, edges [[0,1],[0,2],[1,3],[2,3]]",
    "output": "[0,1,2,3]"
  },
  "approach": "Kahn's algorithm: repeatedly take a node that has no incoming edges left.",
  "keyIdea": [
    "Count each node's incoming edges (indegree)",
    "Queue all nodes with indegree 0",
    "Poll a node, add it to the order, lower its neighbours' indegree",
    "Fewer than n nodes in the order → cycle"
  ],
  "time": "O(V + E)",
  "space": "O(V)",
  "complexityWhy": "Each node and edge once.",
  "figure": {
    "k": "graph",
    "n": 4,
    "e": [
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ]
    ],
    "d": true,
    "pos": [
      [
        5,
        0
      ],
      [
        1,
        3
      ],
      [
        9,
        3
      ],
      [
        5,
        6
      ]
    ],
    "ok": [
      0
    ],
    "cap": "Node 0 has in-degree 0, so it goes first."
  },
  "code": "class Solution {\n  public int[] topoSort(int n, int[][] edges) {\n    List<List<Integer>> graph = new ArrayList<>();\n    for (int i = 0; i < n; i++) graph.add(new ArrayList<>());\n    int[] indegree = new int[n];\n    for (int[] e : edges) { graph.get(e[0]).add(e[1]); indegree[e[1]]++; }\n    Queue<Integer> queue = new ArrayDeque<>();\n    for (int i = 0; i < n; i++) if (indegree[i] == 0) queue.add(i);\n    int[] order = new int[n];\n    int count = 0;\n    while (!queue.isEmpty()) {\n      int node = queue.poll();\n      order[count++] = node;\n      for (int next : graph.get(node)) {\n        if (--indegree[next] == 0) queue.add(next);      // all its prerequisites are done\n      }\n    }\n    return count == n ? order : new int[0];              // fewer than n -> cycle\n  }\n}",
  "method": "topoSort",
  "defaultInput": "4, [[0,1],[0,2],[1,3],[2,3]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        4,
        [
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            1,
            3
          ],
          [
            2,
            3
          ]
        ]
      ],
      "expected": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "name": "Classic example",
      "args": [
        6,
        [
          [
            5,
            2
          ],
          [
            5,
            0
          ],
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            2,
            3
          ],
          [
            3,
            1
          ]
        ]
      ],
      "expected": [
        4,
        5,
        2,
        0,
        3,
        1
      ]
    },
    {
      "name": "No edges",
      "args": [
        3,
        []
      ],
      "expected": [
        0,
        1,
        2
      ]
    },
    {
      "name": "A chain",
      "args": [
        3,
        [
          [
            2,
            1
          ],
          [
            1,
            0
          ]
        ]
      ],
      "expected": [
        2,
        1,
        0
      ]
    },
    {
      "name": "A cycle",
      "args": [
        3,
        [
          [
            0,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            0
          ]
        ]
      ],
      "expected": []
    },
    {
      "name": "Single node",
      "args": [
        1,
        []
      ],
      "expected": [
        0
      ]
    }
  ],
  "challenge": {
    "question": "What order does Kahn's algorithm produce?",
    "input": "6, [[5,2],[5,0],[4,0],[4,1],[2,3],[3,1]]",
    "options": [
      "[5,2,0,3,1,4]",
      "[4,5,2,0,3,1]",
      "[5,4,2,0,3,1]",
      "[0,1,2,3,4,5]"
    ],
    "answer": 1,
    "explanation": "Start with the nodes nobody points to (4 and 5). Removing them frees 2 and 0, then 3, then 1 → [4,5,2,0,3,1]."
  },
  "memory": {
    "remember": "Repeatedly take a node with no incoming edges —\nthat order is a valid topological sort.",
    "pattern": "Kahn's algorithm with a queue"
  }
};

export default problem;
