// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H116",
  "number": 116,
  "slug": "infix-to-postfix",
  "title": "Infix to Postfix Conversion",
  "category": "Stack",
  "definition": "Convert a normal expression like a+b*c into postfix form (abc*+).",
  "example": {
    "input": "\"(a+b)*c\"",
    "output": "\"ab+c*\""
  },
  "approach": "Letters go straight to the output. Operators wait on a stack until an operator of lower priority arrives.",
  "keyIdea": [
    "Operands → output",
    "Operator: pop higher/equal priority ones first, then push",
    "( push, ) pop until ("
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "Each character is pushed and popped at most once.",
  "figure": {
    "k": "flow",
    "s": [
      "a → output: a",
      "+ → stack: +",
      "b → output: ab",
      "* → stack: + *",
      "c → output: abc",
      "!end: pop all → abc*+"
    ],
    "cap": "Example a+b*c. * binds tighter, so it stays above +."
  },
  "code": "class Solution {\n  public String infixToPostfix(String expr) {\n    StringBuilder output = new StringBuilder();\n    Deque<Character> stack = new ArrayDeque<>();\n    for (char ch : expr.toCharArray()) {\n      if (Character.isLetterOrDigit(ch)) {\n        output.append(ch);                                   // operand\n      } else if (ch == '(') {\n        stack.push(ch);\n      } else if (ch == ')') {\n        while (stack.peek() != '(') output.append(stack.pop());\n        stack.pop();                                         // discard \"(\"\n      } else {                                               // operator\n        while (!stack.isEmpty() && stack.peek() != '(' &&\n               (priority(stack.peek()) > priority(ch) ||\n                (priority(stack.peek()) == priority(ch) && ch != '^'))) {\n          output.append(stack.pop());\n        }\n        stack.push(ch);\n      }\n    }\n    while (!stack.isEmpty()) output.append(stack.pop());\n    return output.toString();\n  }\n  private int priority(char op) {\n    if (op == '+' || op == '-') return 1;\n    if (op == '*' || op == '/') return 2;\n    return 3;                                                // ^\n  }\n}",
  "method": "infixToPostfix",
  "defaultInput": "\"(a+b)*c\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "(a+b)*c"
      ],
      "expected": "ab+c*"
    },
    {
      "name": "Precedence",
      "args": [
        "a+b*c"
      ],
      "expected": "abc*+"
    },
    {
      "name": "Single operand",
      "args": [
        "a"
      ],
      "expected": "a"
    },
    {
      "name": "Multiply first",
      "args": [
        "a*b+c"
      ],
      "expected": "ab*c+"
    },
    {
      "name": "Two groups",
      "args": [
        "(a+b)*(c-d)"
      ],
      "expected": "ab+cd-*"
    },
    {
      "name": "Left to right",
      "args": [
        "a-b-c"
      ],
      "expected": "ab-c-"
    }
  ],
  "challenge": {
    "question": "What is the postfix form of a+b*c-d?",
    "input": "\"a+b*c-d\"",
    "options": [
      "\"*+-abcd\"",
      "\"-d+*cba\"",
      "\"abc*+d-a\"",
      "\"abc*+d-\""
    ],
    "answer": 3,
    "explanation": "* binds tighter than + and −, so b*c comes first: abc*, then add a: abc*+, then subtract d: abc*+d−."
  },
  "memory": {
    "remember": "Operands go straight to the output;\noperators wait on a stack until a weaker one arrives.",
    "pattern": "Operator Stack with Precedence"
  }
};

export default problem;
