// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H120",
  "number": 120,
  "slug": "maximal-rectangle-in-binary-matrix",
  "title": "Maximal Rectangle in Binary Matrix",
  "category": "Stack",
  "definition": "Largest rectangle containing only 1s.",
  "example": {
    "input": "4×5 matrix of \"0\" / \"1\"",
    "output": "6"
  },
  "approach": "Build a histogram from each row (how many 1s stack up in each column) and reuse Largest Rectangle in Histogram.",
  "keyIdea": [
    "For each row update column heights",
    "Height resets to 0 on a \"0\"",
    "Run the histogram solution on the heights"
  ],
  "time": "O(m·n²)",
  "space": "O(n)",
  "complexityWhy": "Each row runs an O(n²) histogram.",
  "figure": {
    "k": "grid",
    "v": [
      [
        1,
        0,
        1,
        0,
        0
      ],
      [
        1,
        0,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1,
        1
      ],
      [
        1,
        0,
        0,
        1,
        0
      ]
    ],
    "ok": [
      [
        1,
        2
      ],
      [
        1,
        3
      ],
      [
        1,
        4
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ]
    ],
    "cap": "The best rectangle of 1s is 2 rows × 3 columns = 6."
  },
  "better": {
    "name": "Histogram per row with a stack",
    "time": "O(m·n)",
    "space": "O(n)",
    "code": "class Solution {\n  public int maximalRectangle(char[][] matrix) {\n    if (matrix.length == 0) return 0;\n    int cols = matrix[0].length;\n    int[] heights = new int[cols];\n    int best = 0;\n    for (char[] row : matrix) {\n      for (int c = 0; c < cols; c++) heights[c] = (row[c] == '1') ? heights[c] + 1 : 0;\n      Deque<Integer> stack = new ArrayDeque<>();\n      for (int i = 0; i <= cols; i++) {\n        int h = (i == cols) ? 0 : heights[i];\n        while (!stack.isEmpty() && heights[stack.peek()] > h) {\n          int height = heights[stack.pop()];\n          int width = stack.isEmpty() ? i : i - stack.peek() - 1;\n          best = Math.max(best, height * width);\n        }\n        stack.push(i);\n      }\n    }\n    return best;\n  }\n}"
  },
  "code": "class Solution {\n  public int maximalRectangle(char[][] matrix) {\n    if (matrix.length == 0) return 0;\n    int cols = matrix[0].length;\n    int[] heights = new int[cols];\n    int best = 0;\n    for (char[] row : matrix) {\n      for (int c = 0; c < cols; c++) {\n        heights[c] = (row[c] == '1') ? heights[c] + 1 : 0;   // stack of 1s\n      }\n      best = Math.max(best, largestRectangleArea(heights));\n    }\n    return best;\n  }\n  private int largestRectangleArea(int[] heights) {          // simple expand version\n    int best = 0;\n    for (int i = 0; i < heights.length; i++) {\n      int left = i, right = i;\n      while (left > 0 && heights[left - 1] >= heights[i]) left--;\n      while (right < heights.length - 1 && heights[right + 1] >= heights[i]) right++;\n      best = Math.max(best, heights[i] * (right - left + 1));\n    }\n    return best;\n  }\n}",
  "method": "maximalRectangle",
  "defaultInput": "[\"10100\",\"10111\",\"11111\",\"10010\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          "10100",
          "10111",
          "11111",
          "10010"
        ]
      ],
      "expected": 6
    },
    {
      "name": "Single zero",
      "args": [
        [
          "0"
        ]
      ],
      "expected": 0
    },
    {
      "name": "Single one",
      "args": [
        [
          "1"
        ]
      ],
      "expected": 1
    },
    {
      "name": "All zeros",
      "args": [
        [
          "00",
          "00"
        ]
      ],
      "expected": 0
    },
    {
      "name": "Full square",
      "args": [
        [
          "11",
          "11"
        ]
      ],
      "expected": 4
    },
    {
      "name": "A column",
      "args": [
        [
          "1",
          "1",
          "1"
        ]
      ],
      "expected": 3
    }
  ],
  "challenge": {
    "question": "What is the area of the largest rectangle containing only 1s?",
    "input": "[\"0110\",\"1111\",\"1111\"]",
    "options": [
      "8",
      "9",
      "6",
      "7"
    ],
    "answer": 0,
    "explanation": "The last two rows are all 1s: a rectangle 2 rows × 4 columns = 8."
  },
  "memory": {
    "remember": "Treat each row as a histogram of heights —\nsolve the largest rectangle for every row.",
    "pattern": "Histogram per row with a stack"
  }
};

export default problem;
