// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H033",
  "number": 33,
  "slug": "longest-common-prefix",
  "title": "Longest Common Prefix",
  "category": "Strings",
  "definition": "Longest starting text shared by all strings.",
  "example": {
    "input": "[\"flower\",\"flow\",\"flight\"]",
    "output": "\"fl\""
  },
  "approach": "Compare the strings column by column. Stop at the first column where any word differs.",
  "keyIdea": [
    "Take the first word as the model",
    "For each position i check all words",
    "Mismatch or a word ended → return the prefix so far"
  ],
  "time": "O(S)",
  "space": "O(1)",
  "complexityWhy": "At most the length of the shortest word.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "flower",
        "v": [
          "f",
          "l",
          "o",
          "w",
          "e",
          "r"
        ],
        "ok": [
          0,
          1
        ]
      },
      {
        "l": "flow",
        "v": [
          "f",
          "l",
          "o",
          "w"
        ],
        "ok": [
          0,
          1
        ]
      },
      {
        "l": "flight",
        "v": [
          "f",
          "l",
          "i",
          "g",
          "h",
          "t"
        ],
        "ok": [
          0,
          1
        ],
        "no": [
          2
        ]
      }
    ],
    "cap": "Stop at the first column where a letter differs."
  },
  "code": "class Solution {\n  public String longestCommonPrefix(String[] strs) {\n    for (int i = 0; i < strs[0].length(); i++) {\n      for (String word : strs) {\n        if (i == word.length() || word.charAt(i) != strs[0].charAt(i)) return strs[0].substring(0, i);\n      }\n    }\n    return strs[0];\n  }\n}",
  "method": "longestCommonPrefix",
  "defaultInput": "[\"flower\",\"flow\",\"flight\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          "flower",
          "flow",
          "flight"
        ]
      ],
      "expected": "fl"
    },
    {
      "name": "No prefix",
      "args": [
        [
          "dog",
          "racecar",
          "car"
        ]
      ],
      "expected": ""
    },
    {
      "name": "Single",
      "args": [
        [
          "abc"
        ]
      ],
      "expected": "abc"
    },
    {
      "name": "Identical",
      "args": [
        [
          "ab",
          "ab"
        ]
      ],
      "expected": "ab"
    },
    {
      "name": "One empty",
      "args": [
        [
          "",
          "b"
        ]
      ],
      "expected": ""
    },
    {
      "name": "Whole shortest",
      "args": [
        [
          "ab",
          "abc",
          "abcd"
        ]
      ],
      "expected": "ab"
    }
  ],
  "challenge": {
    "question": "What is the longest common prefix?",
    "input": "[\"interview\",\"internet\",\"internal\"]",
    "options": [
      "\"inter\"",
      "\"inte\"",
      "\"interi\"",
      "\"retni\""
    ],
    "answer": 0,
    "explanation": "All three start with \"inter\"; at the 6th letter they differ (v, n, n)."
  },
  "memory": {
    "remember": "Scan column by column,\nstop at the first mismatch.",
    "pattern": "Vertical scan (column by column)"
  }
};

export default problem;
