// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H094",
  "number": 94,
  "slug": "alien-dictionary",
  "title": "Alien Dictionary (Topological Sort)",
  "category": "Graph",
  "definition": "Words are sorted in an alien language. Recover the letter order.",
  "example": {
    "input": "[\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]",
    "output": "\"wertf\""
  },
  "approach": "Comparing neighbouring words shows the first different letter: that pair gives a rule 'a comes before b'. Then order the letters by these rules.",
  "keyIdea": [
    "Compare adjacent words → rules (edges)",
    "Repeatedly pick a letter with no unmet rule",
    "If none can be picked → cycle → \"\""
  ],
  "time": "O(C² + total letters)",
  "space": "O(C)",
  "complexityWhy": "C = distinct letters. Rescans letters for each pick.",
  "figure": {
    "k": "graph",
    "n": 5,
    "e": [
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        4
      ]
    ],
    "d": true,
    "pos": [
      [
        0,
        3
      ],
      [
        2.5,
        3
      ],
      [
        5,
        3
      ],
      [
        7.5,
        3
      ],
      [
        10,
        3
      ]
    ],
    "lab": [
      "w",
      "e",
      "r",
      "t",
      "f"
    ],
    "cap": "wrt/wrf → t<f · wrf/er → w<e · er/ett → r<t · ett/rftt → e<r"
  },
  "better": {
    "name": "Kahn's algorithm on the letter graph",
    "time": "O(C + total letters)",
    "space": "O(C)",
    "code": "class Solution {\n  public String alienOrder(String[] words) {\n    Map<Character, Set<Character>> graph = new LinkedHashMap<>();\n    Map<Character, Integer> indegree = new LinkedHashMap<>();\n    for (String w : words) {\n      for (char ch : w.toCharArray()) {\n        graph.putIfAbsent(ch, new HashSet<>());\n        indegree.putIfAbsent(ch, 0);\n      }\n    }\n    for (int i = 0; i + 1 < words.length; i++) {\n      String a = words[i], b = words[i + 1];\n      if (a.length() > b.length() && isPrefix(b, a)) return \"\";\n      for (int j = 0; j < Math.min(a.length(), b.length()); j++) {\n        char x = a.charAt(j), y = b.charAt(j);\n        if (x != y) {\n          if (graph.get(x).add(y)) indegree.put(y, indegree.get(y) + 1);\n          break;\n        }\n      }\n    }\n    Queue<Character> queue = new ArrayDeque<>();\n    for (Map.Entry<Character, Integer> e : indegree.entrySet()) if (e.getValue() == 0) queue.add(e.getKey());\n    StringBuilder order = new StringBuilder();\n    while (!queue.isEmpty()) {\n      char ch = queue.poll();\n      order.append(ch);\n      for (char next : graph.get(ch)) {\n        indegree.put(next, indegree.get(next) - 1);\n        if (indegree.get(next) == 0) queue.add(next);\n      }\n    }\n    return order.length() == graph.size() ? order.toString() : \"\";\n  }\n  private boolean isPrefix(String small, String big) {       // does big start with small?\n    for (int i = 0; i < small.length(); i++) if (small.charAt(i) != big.charAt(i)) return false;\n    return true;\n  }\n}"
  },
  "code": "class Solution {\n  public String alienOrder(String[] words) {\n    Set<Character> letterSet = new LinkedHashSet<>();\n    for (String w : words) for (char ch : w.toCharArray()) letterSet.add(ch);\n    List<Character> letters = new ArrayList<>(letterSet);            // order of first appearance\n    Map<Character, Set<Character>> before = new HashMap<>();         // letter -> letters that must come earlier\n    for (char ch : letters) before.put(ch, new HashSet<>());\n    for (int i = 0; i + 1 < words.length; i++) {\n      String a = words[i], b = words[i + 1];\n      if (a.length() > b.length() && isPrefix(b, a)) return \"\";     // invalid: \"abc\" before \"ab\"\n      for (int j = 0; j < Math.min(a.length(), b.length()); j++) {\n        if (a.charAt(j) != b.charAt(j)) { before.get(b.charAt(j)).add(a.charAt(j)); break; }\n      }\n    }\n    Set<Character> done = new HashSet<>();\n    StringBuilder order = new StringBuilder();\n    while (order.length() < letters.size()) {\n      Character pick = null;\n      for (char ch : letters) {\n        if (!done.contains(ch) && allDone(before.get(ch), done)) { pick = ch; break; }\n      }\n      if (pick == null) return \"\";                                   // cycle\n      done.add(pick);\n      order.append(pick);\n    }\n    return order.toString();\n  }\n  private boolean isPrefix(String small, String big) {       // does big start with small?\n    for (int i = 0; i < small.length(); i++) if (small.charAt(i) != big.charAt(i)) return false;\n    return true;\n  }\n  private boolean allDone(Set<Character> rules, Set<Character> done) {\n    for (char ch : rules) if (!done.contains(ch)) return false;\n    return true;\n  }\n}",
  "method": "alienOrder",
  "defaultInput": "[\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          "wrt",
          "wrf",
          "er",
          "ett",
          "rftt"
        ]
      ],
      "expected": "wertf"
    },
    {
      "name": "Two letters",
      "args": [
        [
          "z",
          "x"
        ]
      ],
      "expected": "zx"
    },
    {
      "name": "Contradiction",
      "args": [
        [
          "z",
          "x",
          "z"
        ]
      ],
      "expected": ""
    },
    {
      "name": "Single word",
      "args": [
        [
          "abc"
        ]
      ],
      "expected": "abc"
    },
    {
      "name": "Classic example",
      "args": [
        [
          "baa",
          "abcd",
          "abca",
          "cab",
          "cad"
        ]
      ],
      "expected": "bdac"
    },
    {
      "name": "Prefix after longer word",
      "args": [
        [
          "abc",
          "ab"
        ]
      ],
      "expected": ""
    }
  ],
  "challenge": {
    "question": "What is the letter order of the alien language?",
    "input": "[\"baa\",\"abcd\",\"abca\",\"cab\",\"cad\"]",
    "options": [
      "\"bdacb\"",
      "\"bdac\"",
      "\"bda\"",
      "\"dac\""
    ],
    "answer": 1,
    "explanation": "Comparing neighbouring words gives b < a, d < a, a < c and b < d → the order is b, d, a, c."
  },
  "memory": {
    "remember": "Compare neighbouring words: the first different letters\ngive a rule 'x comes before y' — then sort topologically.",
    "pattern": "Kahn's algorithm on the letter graph"
  }
};

export default problem;
