// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H071",
  "number": 71,
  "slug": "level-order-traversal",
  "title": "Level Order Traversal (BFS)",
  "category": "Trees",
  "definition": "Return node values level by level.",
  "example": {
    "input": "[3,9,20,null,null,15,7]",
    "output": "[[3],[9,20],[15,7]]"
  },
  "approach": "Use a queue. Process one whole level at a time by looping over the current queue size.",
  "keyIdea": [
    "Queue starts with the root",
    "size = number of nodes on this level",
    "Poll each, record its value, add its children",
    "Repeat until the queue is empty"
  ],
  "time": "O(n)",
  "space": "O(w)",
  "complexityWhy": "Each node is visited once.",
  "figure": {
    "k": "tree",
    "v": [
      3,
      9,
      20,
      null,
      null,
      15,
      7
    ],
    "cap": "Level 0: 3 · Level 1: 9, 20 · Level 2: 15, 7"
  },
  "code": "class Solution {\n  public List<List<Integer>> levelOrder(TreeNode root) {\n    List<List<Integer>> result = new ArrayList<>();\n    if (root == null) return result;\n    Queue<TreeNode> queue = new ArrayDeque<>();\n    queue.add(root);\n    while (!queue.isEmpty()) {\n      int size = queue.size();                 // nodes on this level\n      List<Integer> level = new ArrayList<>();\n      for (int i = 0; i < size; i++) {\n        TreeNode node = queue.poll();\n        level.add(node.val);\n        if (node.left != null) queue.add(node.left);\n        if (node.right != null) queue.add(node.right);\n      }\n      result.add(level);\n    }\n    return result;\n  }\n}",
  "method": "levelOrder",
  "defaultInput": "[3,9,20,null,null,15,7]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          9,
          20,
          null,
          null,
          15,
          7
        ]
      ],
      "expected": [
        [
          3
        ],
        [
          9,
          20
        ],
        [
          15,
          7
        ]
      ]
    },
    {
      "name": "Empty tree",
      "args": [
        []
      ],
      "expected": []
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": [
        [
          1
        ]
      ]
    },
    {
      "name": "Left chain",
      "args": [
        [
          1,
          2,
          null,
          3
        ]
      ],
      "expected": [
        [
          1
        ],
        [
          2
        ],
        [
          3
        ]
      ]
    },
    {
      "name": "Full tree",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          6,
          7
        ]
      ],
      "expected": [
        [
          1
        ],
        [
          2,
          3
        ],
        [
          4,
          5,
          6,
          7
        ]
      ]
    },
    {
      "name": "Right chain",
      "args": [
        [
          1,
          null,
          2,
          null,
          3
        ]
      ],
      "expected": [
        [
          1
        ],
        [
          2
        ],
        [
          3
        ]
      ]
    }
  ],
  "challenge": {
    "question": "What does the level-order traversal return?",
    "input": "[1,2,3,4,null,null,5]",
    "options": [
      "[[1],[2,3]]",
      "[[4,5],[2,3],[1]]",
      "[[1],[3,2],[5,4]]",
      "[[1],[2,3],[4,5]]"
    ],
    "answer": 3,
    "explanation": "Level 0: 1 · level 1: 2, 3 · level 2: 4, 5 — one list per level, left to right."
  },
  "memory": {
    "remember": "Use a queue and process\none whole level at a time.",
    "pattern": "BFS — process one level at a time"
  }
};

export default problem;
