// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H052",
  "number": 52,
  "slug": "prime-factorization",
  "title": "Prime Factorization",
  "category": "Math & Number Theory",
  "definition": "Break n into prime factors.",
  "example": {
    "input": "n = 360",
    "output": "[2,2,2,3,3,5]"
  },
  "approach": "Divide by 2, 3, 4… as long as it divides. Stop at √n; if something bigger than 1 is left, it is prime.",
  "keyIdea": [
    "d from 2 while d × d ≤ n",
    "While n % d == 0: record d and n /= d",
    "n > 1 left → it is a prime factor"
  ],
  "time": "O(√n)",
  "space": "O(log n)",
  "complexityWhy": "At most √n steps.",
  "figure": {
    "k": "flow",
    "s": [
      "360 ÷ 2 = 180  ÷ 2 = 90  ÷ 2 = 45",
      "45 ÷ 3 = 15  ÷ 3 = 5",
      "!5 is prime → [2, 2, 2, 3, 3, 5]"
    ],
    "cap": "Divide out each factor completely before moving to the next."
  },
  "code": "class Solution {\n  public List<Integer> primeFactors(int n) {\n    List<Integer> factors = new ArrayList<>();\n    for (long d = 2; d * d <= n; d++) {                         // only up to sqrt(n)\n      while (n % d == 0) {\n        factors.add((int) d);\n        n /= d;\n      }\n    }\n    if (n > 1) factors.add(n);                                  // what is left over is itself prime\n    return factors;\n  }\n}",
  "method": "primeFactors",
  "defaultInput": "360",
  "tests": [
    {
      "name": "Example",
      "args": [
        360
      ],
      "expected": [
        2,
        2,
        2,
        3,
        3,
        5
      ]
    },
    {
      "name": "A prime",
      "args": [
        13
      ],
      "expected": [
        13
      ]
    },
    {
      "name": "Power of two",
      "args": [
        64
      ],
      "expected": [
        2,
        2,
        2,
        2,
        2,
        2
      ]
    },
    {
      "name": "One",
      "args": [
        1
      ],
      "expected": []
    },
    {
      "name": "Two primes",
      "args": [
        91
      ],
      "expected": [
        7,
        13
      ]
    },
    {
      "name": "Larger",
      "args": [
        9999
      ],
      "expected": [
        3,
        3,
        11,
        101
      ]
    }
  ],
  "challenge": {
    "question": "What are the prime factors of 84 (smallest first)?",
    "input": "84",
    "options": [
      "[3,3,4,8]",
      "[2,2,3]",
      "[2,2,3,7]",
      "[2,3,7,2]"
    ],
    "answer": 2,
    "explanation": "84 = 2 × 2 × 3 × 7: divide out 2 twice, then 3, and what is left (7) is prime."
  },
  "memory": {
    "remember": "Divide out each factor fully;\nwhat's left (> 1) is prime.",
    "pattern": "Stop at √n; leftover is prime"
  }
};

export default problem;
