// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H055",
  "number": 55,
  "slug": "subarray-with-given-sum-k",
  "title": "Subarray with Given Sum K (find the subarray)",
  "category": "Hashing",
  "definition": "Find a subarray whose sum equals k. Return its start and end index.",
  "example": {
    "input": "[1,2,3,7,5], k = 12",
    "output": "[1,3]  (2+3+7)"
  },
  "approach": "A running (prefix) sum finds the subarray fast: if the prefix sum before it was sum − k, the numbers in between add up to k.",
  "keyIdea": [
    "Map: prefix sum → index (start with 0 → −1)",
    "Add each number to the running sum",
    "Is sum − k in the map? The subarray lies between",
    "Store the current prefix sum"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "One pass with a HashMap.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums",
        "v": [
          1,
          2,
          3,
          7,
          5
        ],
        "ok": [
          1,
          2,
          3
        ],
        "br": [
          [
            1,
            3,
            "sum 12"
          ]
        ]
      },
      {
        "l": "prefix",
        "v": [
          1,
          3,
          6,
          13,
          18
        ],
        "hi": [
          0,
          3
        ],
        "p": {
          "0": "1",
          "3": "13"
        }
      }
    ],
    "cap": "13 − 12 = 1 was a prefix earlier → the numbers in between sum to 12."
  },
  "code": "class Solution {\n  public int[] subarrayWithSum(int[] nums, int k) {\n    Map<Integer, Integer> seen = new HashMap<>();      // prefix sum -> index\n    seen.put(0, -1);\n    int sum = 0;\n    for (int i = 0; i < nums.length; i++) {\n      sum += nums[i];\n      if (seen.containsKey(sum - k)) return new int[]{seen.get(sum - k) + 1, i};\n      seen.put(sum, i);\n    }\n    return new int[]{-1, -1};\n  }\n}",
  "method": "subarrayWithSum",
  "defaultInput": "[1,2,3,7,5], 12",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          7,
          5
        ],
        12
      ],
      "expected": [
        1,
        3
      ]
    },
    {
      "name": "Whole array",
      "args": [
        [
          1,
          2,
          3
        ],
        6
      ],
      "expected": [
        0,
        2
      ]
    },
    {
      "name": "Single element",
      "args": [
        [
          4,
          5,
          6
        ],
        5
      ],
      "expected": [
        1,
        1
      ]
    },
    {
      "name": "At the start",
      "args": [
        [
          2,
          3,
          9
        ],
        5
      ],
      "expected": [
        0,
        1
      ]
    },
    {
      "name": "Longer",
      "args": [
        [
          1,
          4,
          20,
          3,
          10,
          5
        ],
        33
      ],
      "expected": [
        2,
        4
      ]
    },
    {
      "name": "Last elements",
      "args": [
        [
          9,
          1,
          2,
          3
        ],
        6
      ],
      "expected": [
        1,
        3
      ]
    }
  ],
  "challenge": {
    "question": "Which start and end indices give the sum? (start, end)",
    "input": "[3,4,1,7,2], 12",
    "options": [
      "[2,4]",
      "[1]",
      "[1,3]",
      "[3,1]"
    ],
    "answer": 2,
    "explanation": "Prefix sums are 3, 7, 8, 15, 17. At index 3 the prefix 15 minus 12 = 3 was seen at index 0, so the subarray starts at 1 and ends at 3."
  },
  "memory": {
    "remember": "A subarray sum is prefix[j] − prefix[i];\na Map finds i instantly.",
    "pattern": "Prefix sum + Map"
  }
};

export default problem;
