// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H139",
  "number": 139,
  "slug": "implement-a-min-heap",
  "title": "Implement a Min Heap (Java has PriorityQueue; here is how it works)",
  "category": "Heap / Priority Queue",
  "definition": "Push any value and always pop the smallest one fast. In real code use java.util.PriorityQueue (it is a min-heap).",
  "example": {
    "input": "push 5,3,8,1,9,2 then pop everything",
    "output": "1,2,3,5,8,9"
  },
  "approach": "Keep a list sorted from smallest to largest. A push finds the right spot and inserts the value there. The smallest item is always at the front.",
  "keyIdea": [
    "push: find the spot and insert the value",
    "pop: remove the first item (the smallest)",
    "peek: look at the first item"
  ],
  "time": "push O(n), pop O(n)",
  "space": "O(n)",
  "complexityWhy": "Finding the spot and shifting items costs O(n) per push, and removing the front shifts everything.",
  "figure": [
    {
      "k": "tree",
      "v": [
        1,
        3,
        2,
        5,
        9,
        8
      ],
      "hi": [
        1
      ],
      "cap": "Every parent is smaller than its children."
    },
    {
      "k": "arr",
      "r": [
        {
          "l": "array",
          "v": [
            1,
            3,
            2,
            5,
            9,
            8
          ],
          "ix": 1,
          "p": {
            "0": "min"
          }
        }
      ],
      "cap": "Stored in a plain array: children of i are at 2i+1 and 2i+2."
    }
  ],
  "better": {
    "name": "Binary heap stored in an array (what PriorityQueue does inside)",
    "time": "push O(log n), pop O(log n)",
    "space": "O(n)",
    "code": "class MinHeap {\n  private int[] heap = new int[16];               // parent of i is (i-1)/2, children 2i+1 and 2i+2\n  private int size = 0;\n  public int size() { return size; }\n  public int peek() { return heap[0]; }\n  public void push(int value) {\n    if (size == heap.length) {                    // full: move everything into a bigger array\n      int[] bigger = new int[size * 2];\n      for (int k = 0; k < size; k++) bigger[k] = heap[k];\n      heap = bigger;\n    }\n    heap[size] = value;\n    int i = size++;\n    while (i > 0) {                               // sift UP while smaller than the parent\n      int parent = (i - 1) / 2;\n      if (heap[i] >= heap[parent]) break;\n      swap(i, parent);\n      i = parent;\n    }\n  }\n  public int pop() {\n    int top = heap[0];\n    heap[0] = heap[--size];                       // move the last item to the top\n    int i = 0;\n    while (true) {                                // sift DOWN\n      int smallest = i, l = 2 * i + 1, r = 2 * i + 2;\n      if (l < size && heap[l] < heap[smallest]) smallest = l;\n      if (r < size && heap[r] < heap[smallest]) smallest = r;\n      if (smallest == i) break;\n      swap(i, smallest);\n      i = smallest;\n    }\n    return top;\n  }\n  private void swap(int a, int b) { int t = heap[a]; heap[a] = heap[b]; heap[b] = t; }\n}"
  },
  "code": "class MinHeap {\n  private final List<Integer> items = new ArrayList<>();\n  public int size() { return items.size(); }\n  public int peek() { return items.get(0); }\n  public void push(int value) {\n    int i = 0;\n    while (i < items.size() && items.get(i) < value) i++;   // find the spot\n    items.add(i, value);                                    // insert there\n  }\n  public int pop() { return items.remove(0); }\n}",
  "method": "MinHeap",
  "defaultInput": "[], [[\"push\",5],[\"push\",3],[\"push\",8],[\"push\",1],[\"push\",9],[\"push\",2],[\"pop\"],[\"pop\"],[\"pop\"],[\"pop\"],[\"pop\"],[\"pop\"]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [],
        [
          [
            "push",
            5
          ],
          [
            "push",
            3
          ],
          [
            "push",
            8
          ],
          [
            "push",
            1
          ],
          [
            "push",
            9
          ],
          [
            "push",
            2
          ],
          [
            "pop"
          ],
          [
            "pop"
          ],
          [
            "pop"
          ],
          [
            "pop"
          ],
          [
            "pop"
          ],
          [
            "pop"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        2,
        3,
        5,
        8,
        9
      ]
    },
    {
      "name": "Single value",
      "args": [
        [],
        [
          [
            "push",
            7
          ],
          [
            "peek"
          ],
          [
            "pop"
          ],
          [
            "size"
          ]
        ]
      ],
      "expected": [
        null,
        7,
        7,
        0
      ]
    },
    {
      "name": "Peek does not remove",
      "args": [
        [],
        [
          [
            "push",
            4
          ],
          [
            "push",
            2
          ],
          [
            "peek"
          ],
          [
            "peek"
          ],
          [
            "size"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        2,
        2,
        2
      ]
    },
    {
      "name": "Duplicates",
      "args": [
        [],
        [
          [
            "push",
            2
          ],
          [
            "push",
            2
          ],
          [
            "push",
            1
          ],
          [
            "pop"
          ],
          [
            "pop"
          ],
          [
            "pop"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        1,
        2,
        2
      ]
    },
    {
      "name": "Negative numbers",
      "args": [
        [],
        [
          [
            "push",
            -1
          ],
          [
            "push",
            -5
          ],
          [
            "push",
            3
          ],
          [
            "pop"
          ],
          [
            "peek"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        -5,
        -1
      ]
    },
    {
      "name": "Size changes",
      "args": [
        [],
        [
          [
            "push",
            1
          ],
          [
            "push",
            2
          ],
          [
            "size"
          ],
          [
            "pop"
          ],
          [
            "size"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        2,
        1,
        1
      ]
    }
  ],
  "challenge": {
    "question": "After push(4), push(1), push(3) and pop() — what does peek() return?",
    "input": "[], [[\"push\",4],[\"push\",1],[\"push\",3],[\"pop\"],[\"peek\"]]",
    "options": [
      "6",
      "3",
      "1",
      "5"
    ],
    "answer": 1,
    "explanation": "pop() removes the smallest value (1). The smallest of the rest is 3, so peek() returns 3."
  },
  "memory": {
    "remember": "A min-heap always hands you\nthe smallest element first.",
    "pattern": "Min-Heap: Smallest Out First"
  }
};

export default problem;
