// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H141",
  "number": 141,
  "slug": "kth-largest-element-in-array",
  "title": "Kth Largest Element in Array",
  "category": "Heap / Priority Queue",
  "definition": "Return the kth largest value.",
  "example": {
    "input": "[3,2,1,5,6,4], k = 2",
    "output": "5"
  },
  "approach": "Keep a min-heap of the k largest numbers. The smallest number in that heap is the kth largest.",
  "keyIdea": [
    "Add each number to a min-heap",
    "Heap bigger than k → remove the smallest",
    "The top of the heap is the answer"
  ],
  "time": "O(n log k)",
  "space": "O(k)",
  "complexityWhy": "n pushes, each O(log k).",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums",
        "v": [
          3,
          2,
          1,
          5,
          6,
          4
        ]
      },
      {
        "l": "heap k=2",
        "v": [
          5,
          6
        ],
        "ok": [
          0
        ],
        "p": {
          "0": "answer"
        }
      }
    ],
    "cap": "The heap keeps the 2 largest; its smallest (5) is the 2nd largest."
  },
  "code": "class Solution {\n  public int findKthLargest(int[] nums, int k) {\n    PriorityQueue<Integer> heap = new PriorityQueue<>();      // min-heap of the k largest so far\n    for (int n : nums) {\n      heap.add(n);\n      if (heap.size() > k) heap.poll();                       // drop the smallest of them\n    }\n    return heap.peek();                                       // smallest of the k largest = kth largest\n  }\n}",
  "method": "findKthLargest",
  "defaultInput": "[3,2,1,5,6,4], 2",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          2,
          1,
          5,
          6,
          4
        ],
        2
      ],
      "expected": 5
    },
    {
      "name": "With repeats",
      "args": [
        [
          3,
          2,
          3,
          1,
          2,
          4,
          5,
          5,
          6
        ],
        4
      ],
      "expected": 4
    },
    {
      "name": "Single number",
      "args": [
        [
          1
        ],
        1
      ],
      "expected": 1
    },
    {
      "name": "Two numbers",
      "args": [
        [
          2,
          1
        ],
        2
      ],
      "expected": 1
    },
    {
      "name": "All equal",
      "args": [
        [
          7,
          7,
          7
        ],
        2
      ],
      "expected": 7
    },
    {
      "name": "Negatives",
      "args": [
        [
          -1,
          -5,
          -3
        ],
        1
      ],
      "expected": -1
    }
  ],
  "challenge": {
    "question": "What is the 3rd largest value?",
    "input": "[9,4,7,1,8], 3",
    "options": [
      "9",
      "7",
      "6",
      "14"
    ],
    "answer": 1,
    "explanation": "Sorted from the largest: 9, 8, 7, … — the 3rd largest is 7."
  },
  "memory": {
    "remember": "Keep a min-heap of the k biggest —\nits top is the k-th largest.",
    "pattern": "Min-heap of size k"
  }
};

export default problem;
