// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H105",
  "number": 105,
  "slug": "merge-two-sorted-lists",
  "title": "Merge Two Sorted Lists",
  "category": "Linked List",
  "definition": "Merge two sorted linked lists into one sorted list.",
  "example": {
    "input": "1→2→4 and 1→3→4",
    "output": "1→1→2→3→4→4"
  },
  "approach": "Use a dummy node. Repeatedly attach the smaller front node of the two lists.",
  "keyIdea": [
    "Create a dummy head and a tail pointer",
    "Attach the smaller of l1 and l2",
    "Move that list forward",
    "Attach the leftover list"
  ],
  "time": "O(n+m)",
  "space": "O(1)",
  "complexityWhy": "One pass. It relinks the existing nodes.",
  "figure": [
    {
      "k": "list",
      "v": [
        1,
        2,
        4
      ]
    },
    {
      "k": "list",
      "v": [
        1,
        3,
        4
      ]
    },
    {
      "k": "list",
      "v": [
        1,
        1,
        2,
        3,
        4,
        4
      ],
      "ok": [
        0,
        1,
        2,
        3,
        4,
        5
      ]
    }
  ],
  "code": "class Solution {\n  public ListNode mergeTwoLists(ListNode l1, ListNode l2) {\n    ListNode dummy = new ListNode(0), tail = dummy;\n    while (l1 != null && l2 != null) {\n      if (l1.val <= l2.val) { tail.next = l1; l1 = l1.next; }\n      else { tail.next = l2; l2 = l2.next; }\n      tail = tail.next;\n    }\n    tail.next = (l1 != null) ? l1 : l2;    // attach the leftovers\n    return dummy.next;\n  }\n}",
  "method": "mergeTwoLists",
  "defaultInput": "[1,2,4], [1,3,4]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          4
        ],
        [
          1,
          3,
          4
        ]
      ],
      "expected": [
        1,
        1,
        2,
        3,
        4,
        4
      ]
    },
    {
      "name": "Both empty",
      "args": [
        [],
        []
      ],
      "expected": null
    },
    {
      "name": "One empty",
      "args": [
        [],
        [
          0
        ]
      ],
      "expected": [
        0
      ]
    },
    {
      "name": "One value vs three",
      "args": [
        [
          5
        ],
        [
          1,
          2,
          4
        ]
      ],
      "expected": [
        1,
        2,
        4,
        5
      ]
    },
    {
      "name": "Equal values",
      "args": [
        [
          1,
          1,
          1
        ],
        [
          1,
          1
        ]
      ],
      "expected": [
        1,
        1,
        1,
        1,
        1
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          -3,
          0,
          9
        ],
        [
          -2,
          5
        ]
      ],
      "expected": [
        -3,
        -2,
        0,
        5,
        9
      ]
    }
  ],
  "challenge": {
    "question": "What is the merged list?",
    "input": "[1,3,5], [2,4,6]",
    "options": [
      "[6,5,4,3,2,1]",
      "[2,1,3,4,5,6]",
      "[1,2,3,4,5,6]",
      "[2,3,4,5,6,7]"
    ],
    "answer": 2,
    "explanation": "Always attach the smaller of the two front nodes: 1, 2, 3, 4, 5, 6."
  },
  "memory": {
    "remember": "A dummy head removes the special case\nfor the very first node.",
    "pattern": "Re-link nodes with a dummy head"
  }
};

export default problem;
