// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H088",
  "number": 88,
  "slug": "clone-graph",
  "title": "Clone Graph",
  "category": "Graph",
  "definition": "Make a deep copy of a connected undirected graph.",
  "example": {
    "input": "square graph 1–2–3–4–1",
    "output": "new nodes with the same connections"
  },
  "approach": "DFS with a map old → copy. Register the copy before visiting the neighbours so cycles do not loop forever.",
  "keyIdea": [
    "Already copied? Return the copy",
    "Make a copy and store it in the map",
    "Copy every neighbour recursively"
  ],
  "time": "O(V + E)",
  "space": "O(V)",
  "complexityWhy": "Each node and edge once.",
  "figure": {
    "k": "graph",
    "n": 4,
    "e": [
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        0
      ]
    ],
    "pos": [
      [
        1,
        0
      ],
      [
        9,
        0
      ],
      [
        9,
        6
      ],
      [
        1,
        6
      ]
    ],
    "lab": [
      1,
      2,
      3,
      4
    ],
    "cap": "Every original node gets exactly one copy."
  },
  "code": "class Node {\n  public int val;\n  public List<Node> neighbors = new ArrayList<>();\n  public Node(int val) { this.val = val; }\n}\nclass Solution {\n  private final Map<Node, Node> copies = new HashMap<>();\n  public Node cloneGraph(Node node) {\n    if (node == null) return null;\n    if (copies.containsKey(node)) return copies.get(node);   // already cloned\n    Node copy = new Node(node.val);\n    copies.put(node, copy);                                  // register BEFORE visiting neighbours\n    for (Node nb : node.neighbors) copy.neighbors.add(cloneGraph(nb));\n    return copy;\n  }\n}",
  "method": "cloneGraph",
  "defaultInput": "[[2,4],[1,3],[2,4],[1,3]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            2,
            4
          ],
          [
            1,
            3
          ],
          [
            2,
            4
          ],
          [
            1,
            3
          ]
        ]
      ],
      "expected": [
        [
          2,
          4
        ],
        [
          1,
          3
        ],
        [
          2,
          4
        ],
        [
          1,
          3
        ]
      ]
    },
    {
      "name": "Single node",
      "args": [
        [
          []
        ]
      ],
      "expected": [
        []
      ]
    },
    {
      "name": "Two nodes",
      "args": [
        [
          [
            2
          ],
          [
            1
          ]
        ]
      ],
      "expected": [
        [
          2
        ],
        [
          1
        ]
      ]
    },
    {
      "name": "Triangle",
      "args": [
        [
          [
            2,
            3
          ],
          [
            1,
            3
          ],
          [
            1,
            2
          ]
        ]
      ],
      "expected": [
        [
          2,
          3
        ],
        [
          1,
          3
        ],
        [
          1,
          2
        ]
      ]
    },
    {
      "name": "Star",
      "args": [
        [
          [
            2,
            3,
            4
          ],
          [
            1
          ],
          [
            1
          ],
          [
            1
          ]
        ]
      ],
      "expected": [
        [
          2,
          3,
          4
        ],
        [
          1
        ],
        [
          1
        ],
        [
          1
        ]
      ]
    },
    {
      "name": "Empty graph",
      "args": [
        []
      ],
      "expected": null
    }
  ],
  "challenge": {
    "question": "How many edges does the cloned graph have?",
    "input": "[[2,3],[1,3,4],[1,2],[2]]",
    "options": [
      "6",
      "4",
      "7",
      "2"
    ],
    "answer": 1,
    "explanation": "The clone keeps every connection: 1–2, 1–3, 2–3 and 2–4 → 4 edges (each edge appears twice in the adjacency lists)."
  },
  "memory": {
    "remember": "Register the copy BEFORE visiting neighbours —\nthe Map stops infinite loops.",
    "pattern": "One DFS with a Map of copies"
  }
};

export default problem;
