// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H134",
  "number": 134,
  "slug": "best-time-to-buy-and-sell-stock-with-cooldown",
  "title": "Best Time to Buy and Sell Stock with Cooldown (State-Machine DP)",
  "category": "Dynamic Programming",
  "definition": "Unlimited transactions, but you must rest one day after selling.",
  "example": {
    "input": "[1,2,3,0,2]",
    "output": "3"
  },
  "approach": "Each day you are either holding a stock or not. Try every choice (buy, sell, wait) and keep the best total.",
  "keyIdea": [
    "State = (day, holding?)",
    "Holding: sell (then skip a day) or wait",
    "Not holding: buy or wait"
  ],
  "time": "O(2ⁿ)",
  "space": "O(n)",
  "complexityWhy": "Tries every combination of actions.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "price",
        "v": [
          1,
          2,
          3,
          0,
          2
        ],
        "p": {
          "0": "buy",
          "1": "sell",
          "2": "rest",
          "3": "buy",
          "4": "sell"
        },
        "ok": [
          0,
          1,
          3,
          4
        ]
      }
    ],
    "cap": "Buy 1, sell 2, rest, buy 0, sell 2 → 1 + 2 = 3."
  },
  "better": {
    "name": "Three-state machine (hold / sold / rest)",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int maxProfit(int[] prices) {\n    int hold = Integer.MIN_VALUE / 2;                       // best profit while holding a stock\n    int sold = 0;                                           // best profit right after selling today\n    int rest = 0;                                           // best profit while holding nothing\n    for (int p : prices) {\n      int prevSold = sold;\n      sold = hold + p;                                      // sell today\n      hold = Math.max(hold, rest - p);                      // keep holding, or buy today\n      rest = Math.max(rest, prevSold);                      // cooldown ended\n    }\n    return Math.max(sold, rest);\n  }\n}"
  },
  "code": "class Solution {\n  public int maxProfit(int[] prices) { return dfs(prices, 0, false); }\n  private int dfs(int[] prices, int i, boolean holding) {\n    if (i >= prices.length) return 0;\n    int rest = dfs(prices, i + 1, holding);                 // do nothing today\n    if (holding) return Math.max(rest, prices[i] + dfs(prices, i + 2, false));   // sell (then 1 day cooldown)\n    return Math.max(rest, -prices[i] + dfs(prices, i + 1, true));                // buy\n  }\n}",
  "method": "maxProfit",
  "defaultInput": "[1,2,3,0,2]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          0,
          2
        ]
      ],
      "expected": 3
    },
    {
      "name": "Single day",
      "args": [
        [
          1
        ]
      ],
      "expected": 0
    },
    {
      "name": "Two days up",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": 1
    },
    {
      "name": "Two days down",
      "args": [
        [
          2,
          1
        ]
      ],
      "expected": 0
    },
    {
      "name": "Rising",
      "args": [
        [
          1,
          2,
          4
        ]
      ],
      "expected": 3
    },
    {
      "name": "Zig-zag",
      "args": [
        [
          6,
          1,
          6,
          4,
          3,
          0,
          2
        ]
      ],
      "expected": 7
    }
  ],
  "challenge": {
    "question": "What is the maximum profit (you must rest one day after selling)?",
    "input": "[1,4,2,7]",
    "options": [
      "3",
      "6",
      "4",
      "8"
    ],
    "answer": 1,
    "explanation": "Buy at 1 and sell at 7 for a profit of 6. Selling at 4 first would force a rest day and leave less."
  },
  "memory": {
    "remember": "Three states each day: holding, just sold, resting —\nmove between them.",
    "pattern": "State Machine: Hold / Sold / Rest"
  }
};

export default problem;
