// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H130",
  "number": 130,
  "slug": "01-knapsack",
  "title": "0/1 Knapsack",
  "category": "Dynamic Programming",
  "definition": "Pick items (each once) to maximise value without exceeding the weight limit.",
  "example": {
    "input": "weights [1,3,4,5], values [1,4,5,7], capacity 7",
    "output": "9"
  },
  "approach": "dp[c] = best value with capacity c. For each item go from a big capacity down to a small one, so the item is used only once.",
  "keyIdea": [
    "dp array of size capacity + 1",
    "For each item, c from capacity down to its weight",
    "dp[c] = max(dp[c], dp[c − weight] + value)"
  ],
  "time": "O(n·W)",
  "space": "O(W)",
  "complexityWhy": "n items × capacity W.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "weight",
        "v": [
          1,
          3,
          4,
          5
        ],
        "ok": [
          1,
          2
        ]
      },
      {
        "l": "value",
        "v": [
          1,
          4,
          5,
          7
        ],
        "ok": [
          1,
          2
        ]
      }
    ],
    "cap": "Take weights 3 and 4 (total 7) → value 4 + 5 = 9."
  },
  "code": "class Solution {\n  public int knapsack(int[] weights, int[] values, int capacity) {\n    int[] dp = new int[capacity + 1];                       // dp[c]: best value with capacity c\n    for (int i = 0; i < weights.length; i++) {\n      for (int c = capacity; c >= weights[i]; c--) {        // backwards: each item used once\n        dp[c] = Math.max(dp[c], dp[c - weights[i]] + values[i]);\n      }\n    }\n    return dp[capacity];\n  }\n}",
  "method": "knapsack",
  "defaultInput": "[1,3,4,5], [1,4,5,7], 7",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          3,
          4,
          5
        ],
        [
          1,
          4,
          5,
          7
        ],
        7
      ],
      "expected": 9
    },
    {
      "name": "Zero capacity",
      "args": [
        [
          1
        ],
        [
          10
        ],
        0
      ],
      "expected": 0
    },
    {
      "name": "Fits exactly",
      "args": [
        [
          5
        ],
        [
          10
        ],
        5
      ],
      "expected": 10
    },
    {
      "name": "Too heavy",
      "args": [
        [
          2,
          3
        ],
        [
          3,
          4
        ],
        1
      ],
      "expected": 0
    },
    {
      "name": "Best pair",
      "args": [
        [
          1,
          2,
          3
        ],
        [
          6,
          10,
          12
        ],
        5
      ],
      "expected": 22
    },
    {
      "name": "Choose the valuable one",
      "args": [
        [
          4,
          5,
          1
        ],
        [
          1,
          2,
          3
        ],
        4
      ],
      "expected": 3
    }
  ],
  "challenge": {
    "question": "What is the maximum value you can carry with capacity 5?",
    "input": "[1,2,3], [6,10,12], 5",
    "options": [
      "22",
      "25",
      "20",
      "44"
    ],
    "answer": 0,
    "explanation": "Taking the items of weight 2 and 3 gives value 10 + 12 = 22 with total weight 5 — better than 1 + 3 (value 18)."
  },
  "memory": {
    "remember": "For each item: take it or leave it —\nloop the capacity backwards so each item is used once.",
    "pattern": "1-D DP (capacity loop backwards)"
  }
};

export default problem;
