// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H103",
  "number": 103,
  "slug": "fast-slow-pointer-detect-cycle",
  "title": "Fast & Slow Pointer — Detect Cycle",
  "category": "Linked List",
  "definition": "Does the linked list contain a cycle?",
  "example": {
    "input": "1 → 2 → 3 → 4 → 2 …",
    "output": "true"
  },
  "approach": "A slow and a fast pointer: if the list has a loop, the fast one eventually catches the slow one.",
  "keyIdea": [
    "slow moves 1, fast moves 2",
    "fast reaches null → no cycle",
    "slow == fast → cycle"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass, O(1) space.",
  "figure": {
    "k": "list",
    "v": [
      1,
      2,
      3,
      4
    ],
    "cyc": 1,
    "hi": [
      1
    ],
    "cap": "Inside a loop the fast pointer laps the slow one."
  },
  "code": "class Solution {\n  public boolean hasCycle(ListNode head) {\n    ListNode slow = head, fast = head;\n    while (fast != null && fast.next != null) {\n      slow = slow.next;\n      fast = fast.next.next;\n      if (slow == fast) return true;       // the hare caught the tortoise\n    }\n    return false;\n  }\n}",
  "method": "hasCycle",
  "defaultInput": "{\"list\":[3,2,0,-4],\"pos\":1}",
  "tests": [
    {
      "name": "Example",
      "args": [
        {
          "list": [
            3,
            2,
            0,
            -4
          ],
          "pos": 1
        }
      ],
      "expected": true
    },
    {
      "name": "Two nodes in a loop",
      "args": [
        {
          "list": [
            1,
            2
          ],
          "pos": 0
        }
      ],
      "expected": true
    },
    {
      "name": "Single node, no loop",
      "args": [
        [
          1
        ]
      ],
      "expected": false
    },
    {
      "name": "No loop",
      "args": [
        {
          "list": [
            1,
            2,
            3
          ],
          "pos": -1
        }
      ],
      "expected": false
    },
    {
      "name": "Self loop",
      "args": [
        {
          "list": [
            1
          ],
          "pos": 0
        }
      ],
      "expected": true
    },
    {
      "name": "Empty list",
      "args": [
        []
      ],
      "expected": false
    }
  ],
  "challenge": {
    "question": "Does the list contain a cycle?",
    "input": "{\"list\":[1,2,3,4,5],\"pos\":2}",
    "options": [
      "true",
      "false"
    ],
    "answer": 0,
    "explanation": "Node 5 points back to node 3, so there is a loop. Fast (two steps) laps slow (one step) inside it and they meet → true."
  },
  "memory": {
    "remember": "Tortoise and hare:\nif the fast pointer ever meets the slow one, there is a loop.",
    "pattern": "Floyd's Tortoise & Hare"
  }
};

export default problem;
