// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H041",
  "number": 41,
  "slug": "heap-sort",
  "title": "Heap Sort",
  "category": "Sorting Algorithms",
  "definition": "Turn the array into a heap (biggest on top), then keep moving the biggest to the end.",
  "example": {
    "input": "[5,2,9,1,5,6]",
    "output": "[1,2,5,5,6,9]"
  },
  "approach": "A heap keeps the biggest number at the top. Take the top, put it at the end of the array, fix the heap, repeat.",
  "keyIdea": [
    "Turn the array into a max-heap",
    "Swap the root (max) with the last item",
    "Shrink the heap and sink the new root"
  ],
  "time": "O(n log n)",
  "space": "O(1)",
  "complexityWhy": "n removals, each sink costs log n. No extra memory.",
  "figure": {
    "k": "tree",
    "v": [
      9,
      5,
      6,
      1,
      2,
      5
    ],
    "hi": [
      9
    ],
    "cap": "Max-heap: every parent is bigger than its children."
  },
  "code": "class Solution {\n  public int[] heapSort(int[] arr) {\n    int n = arr.length;\n    for (int i = n / 2 - 1; i >= 0; i--) sink(arr, i, n);   // build max-heap\n    for (int end = n - 1; end > 0; end--) {\n      int t = arr[0]; arr[0] = arr[end]; arr[end] = t;       // max to the end\n      sink(arr, 0, end);\n    }\n    return arr;\n  }\n  private void sink(int[] arr, int i, int size) {            // push arr[i] down to its place\n    while (true) {\n      int largest = i, l = 2 * i + 1, r = 2 * i + 2;\n      if (l < size && arr[l] > arr[largest]) largest = l;\n      if (r < size && arr[r] > arr[largest]) largest = r;\n      if (largest == i) return;\n      int t = arr[i]; arr[i] = arr[largest]; arr[largest] = t;\n      i = largest;\n    }\n  }\n}",
  "method": "heapSort",
  "viz": "heap",
  "defaultInput": "[5,2,9,1,5,6]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          5,
          2,
          9,
          1,
          5,
          6
        ]
      ],
      "expected": [
        1,
        2,
        5,
        5,
        6,
        9
      ]
    },
    {
      "name": "Already sorted",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "name": "Reversed",
      "args": [
        [
          5,
          4,
          3,
          2,
          1
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          7
        ]
      ],
      "expected": [
        7
      ]
    },
    {
      "name": "Empty",
      "args": [
        []
      ],
      "expected": []
    },
    {
      "name": "Duplicates",
      "args": [
        [
          3,
          3,
          1,
          1,
          2,
          2
        ]
      ],
      "expected": [
        1,
        1,
        2,
        2,
        3,
        3
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          0,
          -3,
          8,
          -1
        ]
      ],
      "expected": [
        -3,
        -1,
        0,
        8
      ]
    }
  ],
  "challenge": {
    "question": "Which value sits at the root of the max-heap built from [5,2,9,1,5,6]?",
    "input": "[5,2,9,1,5,6]",
    "options": [
      "5",
      "6",
      "9",
      "1"
    ],
    "answer": 2,
    "explanation": "In a max-heap every parent is bigger than its children, so the largest value (9) is at the root."
  },
  "memory": {
    "remember": "Build a max-heap, then keep moving\nthe biggest to the back.",
    "pattern": "Max-Heap → Swap Root to the End"
  }
};

export default problem;
