// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H124",
  "number": 124,
  "slug": "decode-ways",
  "title": "Decode Ways",
  "category": "Dynamic Programming",
  "definition": "Count ways to decode a digit string where A=1 … Z=26.",
  "example": {
    "input": "\"226\"",
    "output": "3  (BZ, VF, BBF)"
  },
  "approach": "At each position decode one digit (if not 0), or two digits (if 10–26). Add up all the ways.",
  "keyIdea": [
    "'0' alone can't be decoded",
    "ways(i) = ways(i+1) + ways(i+2) (if the pair ≤ 26)"
  ],
  "time": "O(2ⁿ)",
  "space": "O(n)",
  "complexityWhy": "Repeated sub-problems.",
  "figure": {
    "k": "flow",
    "s": [
      "2 | 2 | 6  →  B B F",
      "22 | 6  →  V F",
      "2 | 26  →  B Z",
      "!3 ways"
    ],
    "cap": "Split into 1-digit or 2-digit chunks."
  },
  "better": {
    "name": "Bottom-up with two variables",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int numDecodings(String s) {\n    int prev2 = 1;                                         // ways to decode the first i-2 digits\n    int prev1 = s.charAt(0) == '0' ? 0 : 1;                // ways to decode the first i-1 digits\n    for (int i = 2; i <= s.length(); i++) {\n      int cur = 0;\n      if (s.charAt(i - 1) != '0') cur += prev1;            // last digit alone\n      int two = Integer.parseInt(s.substring(i - 2, i));\n      if (two >= 10 && two <= 26) cur += prev2;            // last two digits together\n      prev2 = prev1;\n      prev1 = cur;\n    }\n    return prev1;\n  }\n}"
  },
  "code": "class Solution {\n  public int numDecodings(String s) { return decode(s, 0); }\n  private int decode(String s, int i) {\n    if (i == s.length()) return 1;                         // decoded everything: one way\n    if (s.charAt(i) == '0') return 0;                      // \"0\" alone is not a letter\n    int ways = decode(s, i + 1);                           // take one digit\n    if (i + 1 < s.length() && Integer.parseInt(s.substring(i, i + 2)) <= 26) {\n      ways += decode(s, i + 2);                            // take two digits\n    }\n    return ways;\n  }\n}",
  "method": "numDecodings",
  "defaultInput": "\"226\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "226"
      ],
      "expected": 3
    },
    {
      "name": "Two ways",
      "args": [
        "12"
      ],
      "expected": 2
    },
    {
      "name": "Leading zero",
      "args": [
        "06"
      ],
      "expected": 0
    },
    {
      "name": "Ten",
      "args": [
        "10"
      ],
      "expected": 1
    },
    {
      "name": "Zero in the middle",
      "args": [
        "2101"
      ],
      "expected": 1
    },
    {
      "name": "Longer",
      "args": [
        "11106"
      ],
      "expected": 2
    }
  ],
  "challenge": {
    "question": "In how many ways can \"1226\" be decoded (A = 1 … Z = 26)?",
    "input": "\"1226\"",
    "options": [
      "5",
      "6",
      "4",
      "10"
    ],
    "answer": 0,
    "explanation": "1·2·2·6, 12·2·6, 1·22·6, 1·2·26 and 12·26 → 5 different decodings."
  },
  "memory": {
    "remember": "dp[i] = ways to decode the first i digits:\nadd dp[i−1] and dp[i−2] when they are valid.",
    "pattern": "DP over Prefixes (1 or 2 Digits)"
  }
};

export default problem;
