// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H080",
  "number": 80,
  "slug": "validate-binary-search-tree",
  "title": "Validate Binary Search Tree",
  "category": "Trees",
  "definition": "Is the tree a valid BST?",
  "example": {
    "input": "[5,1,4,null,null,3,6]",
    "output": "false"
  },
  "approach": "Every node must be inside an allowed range. Going left, the upper limit becomes the node's value; going right, the lower limit does.",
  "keyIdea": [
    "Start with the range (−∞, +∞)",
    "Value outside the range → false",
    "Left child: (min, node)",
    "Right child: (node, max)"
  ],
  "time": "O(n)",
  "space": "O(h)",
  "complexityWhy": "Each node is visited once.",
  "figure": {
    "k": "tree",
    "v": [
      5,
      1,
      4,
      null,
      null,
      3,
      6
    ],
    "no": [
      3
    ],
    "hi": [
      4
    ],
    "cap": "3 is in the right subtree of 5 but is smaller than 5 → invalid."
  },
  "code": "class Solution {\n  public boolean isValidBST(TreeNode root) {\n    return check(root, Long.MIN_VALUE, Long.MAX_VALUE);   // long so Integer.MIN/MAX values are safe\n  }\n  private boolean check(TreeNode node, long min, long max) {\n    if (node == null) return true;\n    if (node.val <= min || node.val >= max) return false;   // outside the allowed range\n    return check(node.left, min, node.val)                  // left: everything < node\n        && check(node.right, node.val, max);                // right: everything > node\n  }\n}",
  "method": "isValidBST",
  "defaultInput": "[5,1,4,null,null,3,6]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          5,
          1,
          4,
          null,
          null,
          3,
          6
        ]
      ],
      "expected": false
    },
    {
      "name": "Valid BST",
      "args": [
        [
          2,
          1,
          3
        ]
      ],
      "expected": true
    },
    {
      "name": "Empty tree",
      "args": [
        []
      ],
      "expected": true
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": true
    },
    {
      "name": "Deep violation",
      "args": [
        [
          5,
          4,
          6,
          null,
          null,
          3,
          7
        ]
      ],
      "expected": false
    },
    {
      "name": "Equal values",
      "args": [
        [
          2,
          2,
          2
        ]
      ],
      "expected": false
    }
  ],
  "challenge": {
    "question": "Is it a valid binary search tree?",
    "input": "[8,3,10,1,6,null,14,null,null,4,9]",
    "options": [
      "true",
      "false"
    ],
    "answer": 1,
    "explanation": "9 sits in the left subtree of 8, so it must be smaller than 8 — it isn't. Every node must respect the range set by all its ancestors, not just its parent."
  },
  "memory": {
    "remember": "Every node must stay inside a (min, max) range\ninherited from all its ancestors.",
    "pattern": "Recurse with (min, max) bounds"
  }
};

export default problem;
