// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H091",
  "number": 91,
  "slug": "detect-cycle-in-directed-graph",
  "title": "Detect Cycle in Directed Graph (DFS, 3-color)",
  "category": "Graph",
  "definition": "Does the directed graph contain a cycle?",
  "example": {
    "input": "n = 3, edges [[0,1],[1,2],[2,0]]",
    "output": "true"
  },
  "approach": "Colour the nodes: 0 = new, 1 = on the current path, 2 = finished. Reaching a node that is on the current path means a cycle.",
  "keyIdea": [
    "state[node] = 1 while exploring",
    "A neighbour with state 1 → cycle",
    "When done, state = 2"
  ],
  "time": "O(V + E)",
  "space": "O(V)",
  "complexityWhy": "Each node and edge once.",
  "figure": {
    "k": "graph",
    "n": 3,
    "e": [
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        0
      ]
    ],
    "d": true,
    "pos": [
      [
        5,
        0
      ],
      [
        1,
        6
      ],
      [
        9,
        6
      ]
    ],
    "he": [
      0,
      1,
      2
    ],
    "cap": "0 → 1 → 2 → 0: the path returns to a grey (in-progress) node."
  },
  "code": "class Solution {\n  private List<List<Integer>> graph;\n  private int[] state;                       // 0 = new, 1 = on the current path, 2 = finished\n  public boolean hasCycleDirected(int n, int[][] edges) {\n    graph = new ArrayList<>();\n    for (int i = 0; i < n; i++) graph.add(new ArrayList<>());\n    for (int[] e : edges) graph.get(e[0]).add(e[1]);\n    state = new int[n];\n    for (int i = 0; i < n; i++) if (state[i] == 0 && dfs(i)) return true;\n    return false;\n  }\n  private boolean dfs(int node) {\n    state[node] = 1;\n    for (int next : graph.get(node)) {\n      if (state[next] == 1) return true;     // back to a node on the current path -> cycle\n      if (state[next] == 0 && dfs(next)) return true;\n    }\n    state[node] = 2;\n    return false;\n  }\n}",
  "method": "hasCycleDirected",
  "defaultInput": "3, [[0,1],[1,2],[2,0]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        3,
        [
          [
            0,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            0
          ]
        ]
      ],
      "expected": true
    },
    {
      "name": "A DAG",
      "args": [
        4,
        [
          [
            0,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            3
          ],
          [
            1,
            3
          ]
        ]
      ],
      "expected": false
    },
    {
      "name": "Self loop",
      "args": [
        2,
        [
          [
            0,
            0
          ]
        ]
      ],
      "expected": true
    },
    {
      "name": "Diamond",
      "args": [
        4,
        [
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            1,
            3
          ],
          [
            2,
            3
          ]
        ]
      ],
      "expected": false
    },
    {
      "name": "No edges",
      "args": [
        3,
        []
      ],
      "expected": false
    },
    {
      "name": "Cycle at the end",
      "args": [
        4,
        [
          [
            0,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            3
          ],
          [
            3,
            1
          ]
        ]
      ],
      "expected": true
    }
  ],
  "challenge": {
    "question": "Does the directed graph contain a cycle?",
    "input": "4, [[0,1],[1,2],[2,3],[1,3]]",
    "options": [
      "true",
      "false"
    ],
    "answer": 1,
    "explanation": "Every edge goes 'forward' (0→1→2→3 and 1→3) and no path leads back to where it started, so there is no cycle."
  },
  "memory": {
    "remember": "White = new, grey = on the current path,\nblack = finished. Meeting grey = cycle.",
    "pattern": "DFS with 3 colours (white / grey / black)"
  }
};

export default problem;
