// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H056",
  "number": 56,
  "slug": "subarray-sum-equals-k",
  "title": "Subarray Sum Equals K (count all subarrays)",
  "category": "Hashing",
  "definition": "Count subarrays whose sum equals k (negatives allowed).",
  "example": {
    "input": "[1,2,3], k = 3",
    "output": "2  ([1,2] and [3])"
  },
  "approach": "Same prefix-sum idea, but count how many times each prefix sum happened. Every earlier match is one more subarray.",
  "keyIdea": [
    "freq map: prefix sum → count (0 → 1)",
    "running sum += number",
    "count += freq[sum − k]",
    "freq[sum]++"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "One pass. Negative numbers are fine.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums",
        "v": [
          1,
          2,
          3
        ]
      },
      {
        "l": "prefix",
        "v": [
          1,
          3,
          6
        ],
        "ok": [
          1
        ]
      },
      {
        "l": "subarrays",
        "v": [
          "[1,2]",
          "[3]"
        ],
        "ok": [
          0,
          1
        ]
      }
    ],
    "cap": "prefix[j] − prefix[i] = k means nums[i+1..j] sums to k."
  },
  "code": "class Solution {\n  public int subarraySum(int[] nums, int k) {\n    Map<Integer, Integer> freq = new HashMap<>();      // prefix sum -> how many times seen\n    freq.put(0, 1);\n    int sum = 0, count = 0;\n    for (int n : nums) {\n      sum += n;\n      count += freq.getOrDefault(sum - k, 0);          // each earlier match = one subarray\n      freq.put(sum, freq.getOrDefault(sum, 0) + 1);\n    }\n    return count;\n  }\n}",
  "method": "subarraySum",
  "defaultInput": "[1,2,3], 3",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3
        ],
        3
      ],
      "expected": 2
    },
    {
      "name": "Ones",
      "args": [
        [
          1,
          1,
          1
        ],
        2
      ],
      "expected": 2
    },
    {
      "name": "With negatives",
      "args": [
        [
          1,
          -1,
          0
        ],
        0
      ],
      "expected": 3
    },
    {
      "name": "None",
      "args": [
        [
          1,
          2
        ],
        7
      ],
      "expected": 0
    },
    {
      "name": "Single",
      "args": [
        [
          5
        ],
        5
      ],
      "expected": 1
    },
    {
      "name": "All zeros",
      "args": [
        [
          0,
          0,
          0
        ],
        0
      ],
      "expected": 6
    }
  ],
  "challenge": {
    "question": "How many subarrays sum to k?",
    "input": "[2,2,-4,1,1,2], 0",
    "options": [
      "1",
      "5",
      "3",
      "6"
    ],
    "answer": 2,
    "explanation": "Equal prefix sums mark zero-sum subarrays: (0,3), (1,5) and (2,6) → 3 subarrays."
  },
  "memory": {
    "remember": "Count how often (prefix − k)\nwas seen before.",
    "pattern": "Prefix sums + frequency Map"
  }
};

export default problem;
