// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H018",
  "number": 18,
  "slug": "move-all-zeroes-to-the-end",
  "title": "Move All Zeroes to the End",
  "category": "Arrays",
  "definition": "Move all 0s to the end, keeping the order of other numbers.",
  "example": {
    "input": "[0,1,0,3,12]",
    "output": "[1,3,12,0,0]"
  },
  "approach": "Keep a slot pointer for the next place a non-zero number belongs. Every time you see a non-zero, swap it into the slot.",
  "keyIdea": [
    "slot = 0",
    "For each i: if nums[i] ≠ 0, swap nums[slot] and nums[i]",
    "slot++"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass, in place.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "before",
        "v": [
          0,
          1,
          0,
          3,
          12
        ],
        "no": [
          0,
          2
        ]
      },
      {
        "l": "after",
        "v": [
          1,
          3,
          12,
          0,
          0
        ],
        "ok": [
          0,
          1,
          2
        ],
        "no": [
          3,
          4
        ]
      }
    ],
    "cap": "Non-zeros keep their order; zeroes go last."
  },
  "code": "class Solution {\n  public int[] moveZeroes(int[] nums) {\n    int slot = 0;                           // next place for a non-zero\n    for (int i = 0; i < nums.length; i++) {\n      if (nums[i] != 0) {\n        int t = nums[slot]; nums[slot] = nums[i]; nums[i] = t;\n        slot++;\n      }\n    }\n    return nums;\n  }\n}",
  "method": "moveZeroes",
  "defaultInput": "[0,1,0,3,12]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          0,
          1,
          0,
          3,
          12
        ]
      ],
      "expected": [
        1,
        3,
        12,
        0,
        0
      ]
    },
    {
      "name": "No zeros",
      "args": [
        [
          1,
          2,
          3
        ]
      ],
      "expected": [
        1,
        2,
        3
      ]
    },
    {
      "name": "All zeros",
      "args": [
        [
          0,
          0,
          0
        ]
      ],
      "expected": [
        0,
        0,
        0
      ]
    },
    {
      "name": "Zero at the end",
      "args": [
        [
          1,
          0
        ]
      ],
      "expected": [
        1,
        0
      ]
    },
    {
      "name": "Single zero",
      "args": [
        [
          0
        ]
      ],
      "expected": [
        0
      ]
    },
    {
      "name": "Alternating",
      "args": [
        [
          0,
          1,
          0,
          2,
          0,
          3
        ]
      ],
      "expected": [
        1,
        2,
        3,
        0,
        0,
        0
      ]
    }
  ],
  "challenge": {
    "question": "What does the array look like afterwards?",
    "input": "[0,4,0,5,6]",
    "options": [
      "[0,0,6,5,4]",
      "[0,0,4,5,6]",
      "[5,6,7,1,1]",
      "[4,5,6,0,0]"
    ],
    "answer": 3,
    "explanation": "Non-zero numbers keep their order and slide left; the zeros collect at the end: [4,5,6,0,0]."
  },
  "memory": {
    "remember": "Slow marks where the next non-zero goes;\nfast goes looking for it.",
    "pattern": "Two pointers (swap in place)"
  }
};

export default problem;
