// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H128",
  "number": 128,
  "slug": "edit-distance",
  "title": "Edit Distance",
  "category": "Dynamic Programming",
  "definition": "Minimum insert / delete / replace operations to turn one word into another.",
  "example": {
    "input": "\"horse\" → \"ros\"",
    "output": "3"
  },
  "approach": "dp[i][j] = edits to turn the first i letters of a into the first j letters of b. Same letter: copy the diagonal. Otherwise 1 + the best of replace, delete or insert.",
  "keyIdea": [
    "dp[i][0] = i and dp[0][j] = j",
    "Same letter → dp[i − 1][j − 1]",
    "Otherwise 1 + min(replace, delete, insert)",
    "Answer dp[m][n]"
  ],
  "time": "O(m·n)",
  "space": "O(m·n)",
  "complexityWhy": "Fills an m × n table.",
  "figure": {
    "k": "grid",
    "v": [
      [
        0,
        1,
        2,
        3
      ],
      [
        1,
        1,
        2,
        3
      ],
      [
        2,
        2,
        1,
        2
      ],
      [
        3,
        2,
        2,
        2
      ],
      [
        4,
        3,
        3,
        2
      ],
      [
        5,
        4,
        4,
        3
      ]
    ],
    "rl": [
      "",
      "h",
      "o",
      "r",
      "s",
      "e"
    ],
    "cl": [
      "",
      "r",
      "o",
      "s"
    ],
    "ok": [
      [
        5,
        3
      ]
    ],
    "cap": "Rows = horse, columns = ros. Answer 3."
  },
  "code": "class Solution {\n  public int minDistance(String a, String b) {\n    int m = a.length(), n = b.length();\n    int[][] dp = new int[m + 1][n + 1];                     // dp[i][j]: edits for a[0..i) -> b[0..j)\n    for (int i = 0; i <= m; i++) dp[i][0] = i;\n    for (int j = 0; j <= n; j++) dp[0][j] = j;\n    for (int i = 1; i <= m; i++) {\n      for (int j = 1; j <= n; j++) {\n        if (a.charAt(i - 1) == b.charAt(j - 1)) dp[i][j] = dp[i - 1][j - 1];\n        else dp[i][j] = 1 + Math.min(dp[i - 1][j - 1], Math.min(dp[i - 1][j], dp[i][j - 1]));\n      }\n    }\n    return dp[m][n];\n  }\n}",
  "method": "minDistance",
  "defaultInput": "\"horse\", \"ros\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "horse",
        "ros"
      ],
      "expected": 3
    },
    {
      "name": "Longer",
      "args": [
        "intention",
        "execution"
      ],
      "expected": 5
    },
    {
      "name": "From empty",
      "args": [
        "",
        "a"
      ],
      "expected": 1
    },
    {
      "name": "Identical",
      "args": [
        "abc",
        "abc"
      ],
      "expected": 0
    },
    {
      "name": "To empty",
      "args": [
        "a",
        ""
      ],
      "expected": 1
    },
    {
      "name": "Classic",
      "args": [
        "sunday",
        "saturday"
      ],
      "expected": 3
    }
  ],
  "challenge": {
    "question": "What is the minimum number of edits (insert, delete or replace a letter) to turn \"kitten\" into \"sitting\"?",
    "input": "\"kitten\", \"sitting\"",
    "options": [
      "3",
      "6",
      "5",
      "2"
    ],
    "answer": 0,
    "explanation": "kitten → sitten (replace k with s) → sittin (replace e with i) → sitting (insert g): 3 edits."
  },
  "memory": {
    "remember": "Insert, delete or replace —\nthe table stores the cheapest way for every pair of prefixes.",
    "pattern": "DP table"
  }
};

export default problem;
