// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H027",
  "number": 27,
  "slug": "group-anagrams",
  "title": "Group Anagrams",
  "category": "Strings",
  "definition": "Group words that are anagrams of each other.",
  "example": {
    "input": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]",
    "output": "[[\"eat\",\"tea\",\"ate\"],[\"tan\",\"nat\"],[\"bat\"]]"
  },
  "approach": "Anagrams become the same word when their letters are sorted. Use the sorted word as the key of a map.",
  "keyIdea": [
    "Sort the letters of each word → key",
    "map[key].add(word)",
    "Return all groups of the map"
  ],
  "time": "O(n·k log k)",
  "space": "O(n·k)",
  "complexityWhy": "Sorting a word of length k costs k log k.",
  "figure": {
    "k": "flow",
    "s": [
      "eat → key aet",
      "tea → key aet",
      "tan → key ant",
      "ate → key aet",
      "nat → key ant",
      "bat → key abt",
      "!aet: eat, tea, ate   ant: tan, nat   abt: bat"
    ],
    "cap": "Anagrams share the same sorted key."
  },
  "code": "class Solution {\n  public List<List<String>> groupAnagrams(String[] strs) {\n    Map<String, List<String>> groups = new LinkedHashMap<>();\n    for (String word : strs) {\n      char[] chars = word.toCharArray();\n      Arrays.sort(chars);\n      String key = new String(chars);                   // \"eat\" -> \"aet\"\n      if (!groups.containsKey(key)) groups.put(key, new ArrayList<>());\n      groups.get(key).add(word);\n    }\n    return new ArrayList<>(groups.values());\n  }\n}",
  "method": "groupAnagrams",
  "defaultInput": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          "eat",
          "tea",
          "tan",
          "ate",
          "nat",
          "bat"
        ]
      ],
      "expected": [
        [
          "eat",
          "tea",
          "ate"
        ],
        [
          "tan",
          "nat"
        ],
        [
          "bat"
        ]
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          "a"
        ]
      ],
      "expected": [
        [
          "a"
        ]
      ]
    },
    {
      "name": "Empty string",
      "args": [
        [
          ""
        ]
      ],
      "expected": [
        [
          ""
        ]
      ]
    },
    {
      "name": "No anagrams",
      "args": [
        [
          "abc",
          "def"
        ]
      ],
      "expected": [
        [
          "abc"
        ],
        [
          "def"
        ]
      ]
    },
    {
      "name": "All anagrams",
      "args": [
        [
          "abc",
          "bca",
          "cab"
        ]
      ],
      "expected": [
        [
          "abc",
          "bca",
          "cab"
        ]
      ]
    },
    {
      "name": "Two groups",
      "args": [
        [
          "ab",
          "ba",
          "cd",
          "dc"
        ]
      ],
      "expected": [
        [
          "ab",
          "ba"
        ],
        [
          "cd",
          "dc"
        ]
      ]
    }
  ],
  "challenge": {
    "question": "How many groups of anagrams are there?",
    "input": "[\"stop\",\"pots\",\"tops\",\"cat\",\"act\",\"dog\"]",
    "options": [
      "4",
      "2",
      "5",
      "3"
    ],
    "answer": 3,
    "explanation": "stop/pots/tops, cat/act and dog share sorted keys \"opst\", \"act\" and \"dgo\" → 3 groups."
  },
  "memory": {
    "remember": "Same letters → same sorted key.",
    "pattern": "Sorted word as a Map key"
  }
};

export default problem;
