// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H046",
  "number": 46,
  "slug": "check-prime-number",
  "title": "Check Prime Number",
  "category": "Math & Number Theory",
  "definition": "Is n a prime number?",
  "example": {
    "input": "n = 97",
    "output": "true"
  },
  "approach": "Divisors come in pairs, so it is enough to test up to √n.",
  "keyIdea": [
    "n < 2 → not prime",
    "Test i from 2 while i × i ≤ n",
    "n % i == 0 → not prime"
  ],
  "time": "O(√n)",
  "space": "O(1)",
  "complexityWhy": "At most √n checks.",
  "figure": {
    "k": "flow",
    "s": [
      "100 = 2 × 50 = 4 × 25 = 10 × 10",
      "Every pair has one factor ≤ √100 = 10",
      "!So testing up to √n is enough"
    ],
    "cap": "If n has a big divisor, it also has a small one."
  },
  "code": "class Solution {\n  public boolean isPrime(int n) {\n    if (n < 2) return false;\n    for (int i = 2; (long) i * i <= n; i++) {                   // divisors come in pairs: check up to sqrt(n)\n      if (n % i == 0) return false;\n    }\n    return true;\n  }\n}",
  "method": "isPrime",
  "defaultInput": "97",
  "tests": [
    {
      "name": "Example",
      "args": [
        97
      ],
      "expected": true
    },
    {
      "name": "Composite",
      "args": [
        91
      ],
      "expected": false
    },
    {
      "name": "One",
      "args": [
        1
      ],
      "expected": false
    },
    {
      "name": "Two",
      "args": [
        2
      ],
      "expected": true
    },
    {
      "name": "Even",
      "args": [
        100
      ],
      "expected": false
    },
    {
      "name": "Square of a prime",
      "args": [
        49
      ],
      "expected": false
    },
    {
      "name": "Big prime",
      "args": [
        7919
      ],
      "expected": true
    }
  ],
  "challenge": {
    "question": "Is the number prime?",
    "input": "221",
    "options": [
      "true",
      "false"
    ],
    "answer": 1,
    "explanation": "221 = 13 × 17. The loop reaches 13 (13 × 13 = 169 ≤ 221) and finds a divisor, so it is not prime."
  },
  "memory": {
    "remember": "If n has a divisor,\nit has one ≤ √n.",
    "pattern": "Check only up to √n"
  }
};

export default problem;
