// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H085",
  "number": 85,
  "slug": "bfs-dfs-traversal",
  "title": "BFS & DFS Traversal",
  "category": "Graph",
  "definition": "Visit every node reachable from a start node.",
  "example": {
    "input": "adjacency list [[1,2],[0,3],[0,3],[1,2]], start = 0",
    "output": "BFS [0,1,2,3] · DFS [0,1,3,2]"
  },
  "approach": "BFS spreads out like a ripple (nearest first). DFS goes as deep as it can, then backs up.",
  "keyIdea": [
    "BFS: queue — visit neighbours level by level",
    "DFS: recursion — go deep first",
    "Keep a 'seen' Set so nothing is visited twice"
  ],
  "time": "O(V + E)",
  "space": "O(V)",
  "complexityWhy": "Each node and edge is handled once. Very deep recursion can overflow the call stack.",
  "figure": {
    "k": "graph",
    "n": 4,
    "e": [
      [
        0,
        1
      ],
      [
        0,
        2
      ],
      [
        1,
        3
      ],
      [
        2,
        3
      ]
    ],
    "pos": [
      [
        5,
        0
      ],
      [
        1,
        3
      ],
      [
        9,
        3
      ],
      [
        5,
        6
      ]
    ],
    "ok": [
      0
    ],
    "cap": "BFS: 0 → 1 → 2 → 3    DFS: 0 → 1 → 3 → 2"
  },
  "code": "class Solution {\n  public List<List<Integer>> traverse(List<List<Integer>> graph, int start) {\n    // ---- BFS ----\n    List<Integer> bfsOrder = new ArrayList<>();\n    Set<Integer> seen = new HashSet<>();\n    Queue<Integer> queue = new ArrayDeque<>();\n    seen.add(start);\n    queue.add(start);\n    while (!queue.isEmpty()) {\n      int node = queue.poll();                       // take from the front\n      bfsOrder.add(node);\n      for (int next : graph.get(node)) {\n        if (seen.add(next)) queue.add(next);         // add() is false if already seen\n      }\n    }\n    // ---- DFS (recursion) ----\n    List<Integer> dfsOrder = new ArrayList<>();\n    dfs(graph, start, new HashSet<>(), dfsOrder);\n    return Arrays.asList(bfsOrder, dfsOrder);\n  }\n  private void dfs(List<List<Integer>> graph, int node, Set<Integer> seen, List<Integer> order) {\n    seen.add(node);\n    order.add(node);\n    for (int next : graph.get(node)) {\n      if (!seen.contains(next)) dfs(graph, next, seen, order);\n    }\n  }\n}",
  "method": "traverse",
  "defaultInput": "[[1,2],[0,3],[0,3],[1,2]], 0",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            1,
            2
          ],
          [
            0,
            3
          ],
          [
            0,
            3
          ],
          [
            1,
            2
          ]
        ],
        0
      ],
      "expected": [
        [
          0,
          1,
          2,
          3
        ],
        [
          0,
          1,
          3,
          2
        ]
      ]
    },
    {
      "name": "Single node",
      "args": [
        [
          []
        ],
        0
      ],
      "expected": [
        [
          0
        ],
        [
          0
        ]
      ]
    },
    {
      "name": "Path",
      "args": [
        [
          [
            1
          ],
          [
            0,
            2
          ],
          [
            1
          ]
        ],
        0
      ],
      "expected": [
        [
          0,
          1,
          2
        ],
        [
          0,
          1,
          2
        ]
      ]
    },
    {
      "name": "Start in the middle",
      "args": [
        [
          [
            1
          ],
          [
            0,
            2
          ],
          [
            1
          ]
        ],
        1
      ],
      "expected": [
        [
          1,
          0,
          2
        ],
        [
          1,
          0,
          2
        ]
      ]
    },
    {
      "name": "Star",
      "args": [
        [
          [
            1,
            2,
            3
          ],
          [
            0
          ],
          [
            0
          ],
          [
            0
          ]
        ],
        0
      ],
      "expected": [
        [
          0,
          1,
          2,
          3
        ],
        [
          0,
          1,
          2,
          3
        ]
      ]
    },
    {
      "name": "Disconnected part",
      "args": [
        [
          [
            1
          ],
          [
            0
          ],
          [
            3
          ],
          [
            2
          ]
        ],
        0
      ],
      "expected": [
        [
          0,
          1
        ],
        [
          0,
          1
        ]
      ]
    }
  ],
  "challenge": {
    "question": "In what order does BFS visit the nodes?",
    "input": "[[2,1],[0,3],[0,3],[1,2]], 0",
    "options": [
      "[0,2,1,3]",
      "[3,2,1,0]",
      "[0,1,2,3]",
      "[1,3,2,4]"
    ],
    "answer": 0,
    "explanation": "BFS visits the start (0), then all its neighbours in list order (2, then 1), and only then the next level (3) → [0,2,1,3]."
  },
  "memory": {
    "remember": "BFS: a queue, level by level.\nDFS: go as deep as possible, then back up.",
    "pattern": "BFS (Queue) vs DFS (Recursion)"
  }
};

export default problem;
