// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H129",
  "number": 129,
  "slug": "longest-palindromic-subsequence",
  "title": "Longest Palindromic Subsequence",
  "category": "Dynamic Programming",
  "definition": "Length of the longest palindrome you can get by deleting letters (order kept).",
  "example": {
    "input": "\"bbbab\"",
    "output": "4  (bbbb)"
  },
  "approach": "dp[i][j] = longest palindromic subsequence of s[i..j]. Equal ends add 2 to the inside answer; otherwise drop one end.",
  "keyIdea": [
    "dp[i][i] = 1",
    "Ends equal → dp[i + 1][j − 1] + 2",
    "Otherwise max(dp[i + 1][j], dp[i][j − 1])",
    "Answer dp[0][n − 1]"
  ],
  "time": "O(n²)",
  "space": "O(n²)",
  "complexityWhy": "Fills an n × n table.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "b",
          "b",
          "b",
          "a",
          "b"
        ],
        "ok": [
          0,
          1,
          2,
          4
        ],
        "no": [
          3
        ]
      }
    ],
    "cap": "Skip the 'a' → b b b b (length 4)."
  },
  "code": "class Solution {\n  public int longestPalindromeSubseq(String s) {\n    int n = s.length();\n    int[][] dp = new int[n][n];                             // dp[i][j]: answer for s[i..j]\n    for (int i = n - 1; i >= 0; i--) {\n      dp[i][i] = 1;\n      for (int j = i + 1; j < n; j++) {\n        if (s.charAt(i) == s.charAt(j)) dp[i][j] = dp[i + 1][j - 1] + 2;\n        else dp[i][j] = Math.max(dp[i + 1][j], dp[i][j - 1]);\n      }\n    }\n    return dp[0][n - 1];\n  }\n}",
  "method": "longestPalindromeSubseq",
  "defaultInput": "\"bbbab\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "bbbab"
      ],
      "expected": 4
    },
    {
      "name": "Even palindrome",
      "args": [
        "cbbd"
      ],
      "expected": 2
    },
    {
      "name": "Single letter",
      "args": [
        "a"
      ],
      "expected": 1
    },
    {
      "name": "No repeats",
      "args": [
        "abcde"
      ],
      "expected": 1
    },
    {
      "name": "Whole string",
      "args": [
        "abacaba"
      ],
      "expected": 7
    },
    {
      "name": "Mixed",
      "args": [
        "agbdba"
      ],
      "expected": 5
    }
  ],
  "challenge": {
    "question": "How long is the longest palindromic subsequence of \"agbcba\"?",
    "input": "\"agbcba\"",
    "options": [
      "5",
      "10",
      "7",
      "3"
    ],
    "answer": 0,
    "explanation": "Dropping the 'g' leaves \"abcba\", which is a palindrome of length 5."
  },
  "memory": {
    "remember": "Matching ends add 2 around the inside;\notherwise drop one end.",
    "pattern": "Interval DP table"
  }
};

export default problem;
