// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H062",
  "number": 62,
  "slug": "first-last-occurrence",
  "title": "First & Last Occurrence (Lower / Upper Bound)",
  "category": "Binary Search",
  "definition": "Find the first and last index of target in a sorted array.",
  "example": {
    "input": "[5,7,7,8,8,10], target = 8",
    "output": "[3,4]"
  },
  "approach": "Binary search twice: find the first index where the value is ≥ target, and the first index where it is ≥ target + 1 (minus one is the last).",
  "keyIdea": [
    "lowerBound(target) = first position with nums[i] ≥ target",
    "Not there → [−1, −1]",
    "last = lowerBound(target + 1) − 1"
  ],
  "time": "O(log n)",
  "space": "O(1)",
  "complexityWhy": "Two binary searches.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          5,
          7,
          7,
          8,
          8,
          10
        ],
        "ok": [
          3,
          4
        ],
        "p": {
          "3": "first",
          "4": "last"
        },
        "ix": 1
      }
    ],
    "cap": "Lower bound finds index 3; the next value's lower bound − 1 gives 4."
  },
  "code": "class Solution {\n  public int[] searchRange(int[] nums, int target) {\n    int first = lowerBound(nums, target);\n    if (first == nums.length || nums[first] != target) return new int[]{-1, -1};\n    return new int[]{first, lowerBound(nums, target + 1) - 1};\n  }\n  // first index where nums[i] >= x\n  private int lowerBound(int[] nums, int x) {\n    int lo = 0, hi = nums.length;\n    while (lo < hi) {\n      int mid = lo + (hi - lo) / 2;\n      if (nums[mid] < x) lo = mid + 1; else hi = mid;\n    }\n    return lo;\n  }\n}",
  "method": "searchRange",
  "defaultInput": "[5,7,7,8,8,10], 8",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          5,
          7,
          7,
          8,
          8,
          10
        ],
        8
      ],
      "expected": [
        3,
        4
      ]
    },
    {
      "name": "Not found",
      "args": [
        [
          5,
          7,
          7,
          8,
          8,
          10
        ],
        6
      ],
      "expected": [
        -1,
        -1
      ]
    },
    {
      "name": "Single occurrence",
      "args": [
        [
          1,
          2,
          3
        ],
        2
      ],
      "expected": [
        1,
        1
      ]
    },
    {
      "name": "All the same",
      "args": [
        [
          4,
          4,
          4,
          4
        ],
        4
      ],
      "expected": [
        0,
        3
      ]
    },
    {
      "name": "At the ends",
      "args": [
        [
          2,
          2,
          3,
          3
        ],
        2
      ],
      "expected": [
        0,
        1
      ]
    },
    {
      "name": "Empty array",
      "args": [
        [],
        1
      ],
      "expected": [
        -1,
        -1
      ]
    }
  ],
  "challenge": {
    "question": "What are the first and last index of the target? (first, last)",
    "input": "[1,2,2,2,2,3,5], 2",
    "options": [
      "[4,1]",
      "[1]",
      "[1,4]",
      "[2,5]"
    ],
    "answer": 2,
    "explanation": "2 starts at index 1 and ends at index 4: the lower bound of 2 is 1, and the lower bound of the next value (3) is 5, minus 1 → 4."
  },
  "memory": {
    "remember": "Lower bound of the target = first;\nlower bound of target + 1, minus one = last.",
    "pattern": "Two binary searches (lower bound)"
  }
};

export default problem;
