// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H087",
  "number": 87,
  "slug": "rotting-oranges",
  "title": "Rotting Oranges (Multi-source BFS)",
  "category": "Graph",
  "definition": "Minutes until all oranges rot (rotten ones infect neighbours each minute).",
  "example": {
    "input": "[[2,1,1],[1,1,0],[0,1,1]]",
    "output": "4"
  },
  "approach": "Start BFS from ALL rotten oranges at once. Each round of the queue is one minute.",
  "keyIdea": [
    "Queue every rotten orange and count the fresh ones",
    "Each round: rot the fresh neighbours",
    "minutes++ per round",
    "Fresh oranges left over → −1"
  ],
  "time": "O(m·n)",
  "space": "O(m·n)",
  "complexityWhy": "Each cell is processed once.",
  "figure": [
    {
      "k": "grid",
      "v": [
        [
          2,
          1,
          1
        ],
        [
          1,
          1,
          0
        ],
        [
          0,
          1,
          1
        ]
      ],
      "no": [
        [
          0,
          0
        ]
      ],
      "cap": "Minute 0: one rotten orange (2)."
    },
    {
      "k": "grid",
      "v": [
        [
          2,
          2,
          2
        ],
        [
          2,
          2,
          0
        ],
        [
          0,
          2,
          2
        ]
      ],
      "ok": [
        [
          2,
          2
        ]
      ],
      "cap": "Minute 4: everything is rotten."
    }
  ],
  "code": "class Solution {\n  public int orangesRotting(int[][] grid) {\n    int rows = grid.length, cols = grid[0].length, fresh = 0;\n    Queue<int[]> queue = new ArrayDeque<>();\n    for (int r = 0; r < rows; r++) {\n      for (int c = 0; c < cols; c++) {\n        if (grid[r][c] == 2) queue.add(new int[]{r, c});           // ALL rotten oranges start together\n        else if (grid[r][c] == 1) fresh++;\n      }\n    }\n    int[][] dirs = {{1, 0}, {-1, 0}, {0, 1}, {0, -1}};\n    int minutes = 0;\n    while (!queue.isEmpty() && fresh > 0) {\n      for (int size = queue.size(); size > 0; size--) {\n        int[] cell = queue.poll();\n        for (int[] d : dirs) {\n          int nr = cell[0] + d[0], nc = cell[1] + d[1];\n          if (nr >= 0 && nc >= 0 && nr < rows && nc < cols && grid[nr][nc] == 1) {\n            grid[nr][nc] = 2; fresh--; queue.add(new int[]{nr, nc});\n          }\n        }\n      }\n      minutes++;\n    }\n    return fresh == 0 ? minutes : -1;\n  }\n}",
  "method": "orangesRotting",
  "defaultInput": "[[2,1,1],[1,1,0],[0,1,1]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            2,
            1,
            1
          ],
          [
            1,
            1,
            0
          ],
          [
            0,
            1,
            1
          ]
        ]
      ],
      "expected": 4
    },
    {
      "name": "An orange that can't rot",
      "args": [
        [
          [
            2,
            1,
            1
          ],
          [
            0,
            1,
            1
          ],
          [
            1,
            0,
            1
          ]
        ]
      ],
      "expected": -1
    },
    {
      "name": "Nothing fresh",
      "args": [
        [
          [
            0,
            2
          ]
        ]
      ],
      "expected": 0
    },
    {
      "name": "All rotten",
      "args": [
        [
          [
            2,
            2
          ]
        ]
      ],
      "expected": 0
    },
    {
      "name": "Only a fresh orange",
      "args": [
        [
          [
            1
          ]
        ]
      ],
      "expected": -1
    },
    {
      "name": "A chain",
      "args": [
        [
          [
            2,
            1,
            1,
            1,
            1
          ]
        ]
      ],
      "expected": 4
    }
  ],
  "challenge": {
    "question": "How many minutes until every orange is rotten? (−1 if impossible)",
    "input": "[[2,1,1],[0,1,1],[1,0,1]]",
    "options": [
      "1",
      "-1",
      "-2",
      "0"
    ],
    "answer": 1,
    "explanation": "The orange in the bottom-left corner touches no other orange, so the rot can never reach it → −1."
  },
  "memory": {
    "remember": "Start BFS from all rotten oranges at once —\nthe number of rounds is the time.",
    "pattern": "Multi-source BFS"
  }
};

export default problem;
