// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H050",
  "number": 50,
  "slug": "gcd-lcm-euclidean-algorithm",
  "title": "GCD & LCM (Euclidean Algorithm)",
  "category": "Math & Number Theory",
  "definition": "Greatest common divisor and least common multiple.",
  "example": {
    "input": "12, 18",
    "output": "gcd 6, lcm 36"
  },
  "approach": "Euclid: gcd(a, b) = gcd(b, a % b). Repeat until the remainder is 0. Then lcm = a / gcd × b.",
  "keyIdea": [
    "While y ≠ 0: (x, y) = (y, x % y)",
    "x is the gcd",
    "lcm = a / gcd × b"
  ],
  "time": "O(log min(a,b))",
  "space": "O(1)",
  "complexityWhy": "About log(min(a, b)) steps.",
  "figure": {
    "k": "flow",
    "s": [
      "gcd(18, 12)",
      "= gcd(12, 6)   (18 mod 12 = 6)",
      "= gcd(6, 0)     (12 mod 6 = 0)",
      "!gcd = 6  →  lcm = 12 × 18 ÷ 6 = 36"
    ],
    "cap": "Replace the pair by (smaller, remainder) until the remainder is 0."
  },
  "code": "class Solution {\n  public int[] gcdLcm(int a, int b) {\n    int x = a, y = b;\n    while (y != 0) {                                            // gcd(a, b) = gcd(b, a % b)\n      int t = x % y;\n      x = y;\n      y = t;\n    }\n    return new int[]{x, a / x * b};\n  }\n}",
  "method": "gcdLcm",
  "defaultInput": "12, 18",
  "tests": [
    {
      "name": "Example",
      "args": [
        12,
        18
      ],
      "expected": [
        6,
        36
      ]
    },
    {
      "name": "Coprime",
      "args": [
        7,
        13
      ],
      "expected": [
        1,
        91
      ]
    },
    {
      "name": "Equal",
      "args": [
        10,
        10
      ],
      "expected": [
        10,
        10
      ]
    },
    {
      "name": "Multiples",
      "args": [
        100,
        75
      ],
      "expected": [
        25,
        300
      ]
    },
    {
      "name": "Ones",
      "args": [
        1,
        1
      ],
      "expected": [
        1,
        1
      ]
    },
    {
      "name": "Larger",
      "args": [
        48,
        180
      ],
      "expected": [
        12,
        720
      ]
    }
  ],
  "challenge": {
    "question": "What are the GCD and the LCM? (gcd, lcm)",
    "input": "24, 36",
    "options": [
      "[13,73]",
      "[12,72]",
      "[12]",
      "[72,12]"
    ],
    "answer": 1,
    "explanation": "gcd(24, 36): 36 mod 24 = 12, 24 mod 12 = 0 → 12. lcm = 24 × 36 / 12 = 72."
  },
  "memory": {
    "remember": "gcd(a, b) = gcd(b, a mod b);\nlcm = a × b / gcd.",
    "pattern": "Euclid: gcd(a, b) = gcd(b, a mod b)"
  }
};

export default problem;
