// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H111",
  "number": 111,
  "slug": "copy-list-with-random-pointer",
  "title": "Copy List with Random Pointer",
  "category": "Linked List",
  "definition": "Make a full copy of a list where every node also points to one random node.",
  "example": {
    "input": "7→13→11→10→1 (with random links)",
    "output": "a completely new list with the same links"
  },
  "approach": "Make a copy of every node first and remember old → new in a Map. Then wire up the copies' pointers.",
  "keyIdea": [
    "Pass 1: create a copy of each node in a Map",
    "Pass 2: set copy.next and copy.random using the Map"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "Two passes and a Map of n nodes.",
  "figure": {
    "k": "list",
    "v": [
      "7",
      "7'",
      "13",
      "13'",
      "11",
      "11'"
    ],
    "hi": [
      1,
      3,
      5
    ],
    "cap": "Copies (') sit right after their originals, so random pointers are easy to copy."
  },
  "better": {
    "name": "Weave copies between originals",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public Node copyRandomList(Node head) {\n    if (head == null) return null;\n    for (Node node = head; node != null; node = node.next.next) {   // 1) A -> A' -> B -> B' ...\n      Node copy = new Node(node.val);\n      copy.next = node.next;\n      node.next = copy;\n    }\n    for (Node node = head; node != null; node = node.next.next) {   // 2) copy.random = original.random.next\n      if (node.random != null) node.next.random = node.random.next;\n    }\n    Node newHead = head.next;\n    for (Node node = head; node != null; node = node.next) {        // 3) unweave the two lists\n      Node copy = node.next;\n      node.next = copy.next;\n      copy.next = (copy.next != null) ? copy.next.next : null;\n    }\n    return newHead;\n  }\n}"
  },
  "code": "class Solution {\n  public Node copyRandomList(Node head) {\n    if (head == null) return null;\n    Map<Node, Node> copies = new HashMap<>();          // old node -> new node\n    for (Node node = head; node != null; node = node.next) {\n      copies.put(node, new Node(node.val));\n    }\n    for (Node node = head; node != null; node = node.next) {\n      copies.get(node).next = copies.get(node.next);       // get(null) is null - fine\n      copies.get(node).random = copies.get(node.random);\n    }\n    return copies.get(head);\n  }\n}",
  "method": "copyRandomList",
  "prelude": "class Node { int val; Node next; Node random; Node() {} Node(int val) { this.val = val; } }\n",
  "defaultInput": "[[7,null],[13,0],[11,4],[10,2],[1,0]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            7,
            null
          ],
          [
            13,
            0
          ],
          [
            11,
            4
          ],
          [
            10,
            2
          ],
          [
            1,
            0
          ]
        ]
      ],
      "expected": [
        [
          7,
          null
        ],
        [
          13,
          0
        ],
        [
          11,
          4
        ],
        [
          10,
          2
        ],
        [
          1,
          0
        ]
      ]
    },
    {
      "name": "Single node",
      "args": [
        [
          [
            1,
            null
          ]
        ]
      ],
      "expected": [
        [
          1,
          null
        ]
      ]
    },
    {
      "name": "Random points to itself",
      "args": [
        [
          [
            1,
            0
          ]
        ]
      ],
      "expected": [
        [
          1,
          0
        ]
      ]
    },
    {
      "name": "Two nodes",
      "args": [
        [
          [
            1,
            1
          ],
          [
            2,
            1
          ]
        ]
      ],
      "expected": [
        [
          1,
          1
        ],
        [
          2,
          1
        ]
      ]
    },
    {
      "name": "No random pointers",
      "args": [
        [
          [
            1,
            null
          ],
          [
            2,
            null
          ],
          [
            3,
            null
          ]
        ]
      ],
      "expected": [
        [
          1,
          null
        ],
        [
          2,
          null
        ],
        [
          3,
          null
        ]
      ]
    },
    {
      "name": "Empty list",
      "args": [
        []
      ],
      "expected": null
    }
  ],
  "challenge": {
    "question": "In the copied list, which index does the 3rd node's random pointer point to?",
    "input": "[[7,null],[13,0],[11,4],[10,2],[1,0]]",
    "options": [
      "5",
      "3",
      "7",
      "4"
    ],
    "answer": 3,
    "explanation": "The original 3rd node (11) points to the 5th node (index 4). Its copy must point to the COPY of that node, so the index stays 4."
  },
  "memory": {
    "remember": "Map every old node to its copy first,\nthen wire next and random through the Map.",
    "pattern": "Map of Old Node → New Node"
  }
};

export default problem;
