// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H059",
  "number": 59,
  "slug": "count-distinct-elements-in-every-window",
  "title": "Count Distinct Elements in Every Window",
  "category": "Hashing",
  "definition": "Number of distinct values in every window of size k.",
  "example": {
    "input": "[1,2,1,3,4,2,3], k = 4",
    "output": "[3,4,4,3]"
  },
  "approach": "Slide a window and keep a count for each value. The number of keys in the map is the number of distinct values.",
  "keyIdea": [
    "Add the new number to the map",
    "Remove the number that left the window",
    "Record map.size() once the window is full"
  ],
  "time": "O(n)",
  "space": "O(k)",
  "complexityWhy": "One pass, O(1) per step.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          1,
          2,
          1,
          3,
          4,
          2,
          3
        ],
        "hi": [
          0,
          1,
          2,
          3
        ],
        "br": [
          [
            0,
            3,
            "3 distinct"
          ]
        ]
      },
      {
        "v": [
          1,
          2,
          1,
          3,
          4,
          2,
          3
        ],
        "ok": [
          1,
          2,
          3,
          4
        ],
        "br": [
          [
            1,
            4,
            "4 distinct"
          ]
        ]
      }
    ],
    "cap": "Add one number, remove one number, read the Map size."
  },
  "code": "class Solution {\n  public int[] countDistinct(int[] nums, int k) {\n    Map<Integer, Integer> freq = new HashMap<>();\n    int[] result = new int[nums.length - k + 1];\n    for (int i = 0; i < nums.length; i++) {\n      freq.put(nums[i], freq.getOrDefault(nums[i], 0) + 1);   // add new\n      if (i >= k) {                                     // remove old\n        int out = nums[i - k];\n        if (freq.get(out) == 1) freq.remove(out);\n        else freq.put(out, freq.get(out) - 1);\n      }\n      if (i >= k - 1) result[i - k + 1] = freq.size();\n    }\n    return result;\n  }\n}",
  "method": "countDistinct",
  "defaultInput": "[1,2,1,3,4,2,3], 4",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          1,
          3,
          4,
          2,
          3
        ],
        4
      ],
      "expected": [
        3,
        4,
        4,
        3
      ]
    },
    {
      "name": "k = 1",
      "args": [
        [
          5,
          5,
          6
        ],
        1
      ],
      "expected": [
        1,
        1,
        1
      ]
    },
    {
      "name": "k = n",
      "args": [
        [
          1,
          2,
          2
        ],
        3
      ],
      "expected": [
        2
      ]
    },
    {
      "name": "All same",
      "args": [
        [
          7,
          7,
          7,
          7
        ],
        2
      ],
      "expected": [
        1,
        1,
        1
      ]
    },
    {
      "name": "All distinct",
      "args": [
        [
          1,
          2,
          3,
          4
        ],
        2
      ],
      "expected": [
        2,
        2,
        2
      ]
    },
    {
      "name": "Wider window",
      "args": [
        [
          1,
          1,
          2,
          2,
          3,
          3
        ],
        4
      ],
      "expected": [
        2,
        3,
        2
      ]
    }
  ],
  "challenge": {
    "question": "How many distinct values are in each window?",
    "input": "[4,4,5,6,5], 3",
    "options": [
      "[2,2,3]",
      "[3,2,2]",
      "[2,3,2]",
      "[2,3]"
    ],
    "answer": 2,
    "explanation": "Windows [4,4,5], [4,5,6] and [5,6,5] have 2, 3 and 2 distinct values."
  },
  "memory": {
    "remember": "Add one on the right, remove one on the left —\nupdate the counts.",
    "pattern": "Sliding window + frequency Map"
  }
};

export default problem;
