// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H136",
  "number": 136,
  "slug": "burst-balloons",
  "title": "Burst Balloons",
  "category": "Dynamic Programming",
  "definition": "Burst balloons to collect the most coins (nums[i−1] × nums[i] × nums[i+1]).",
  "example": {
    "input": "[3,1,5,8]",
    "output": "167"
  },
  "approach": "Think backwards: choose the LAST balloon to burst in a range. Then the balloons left and right of it are independent problems.",
  "keyIdea": [
    "Pad the array with 1 on both ends",
    "dp[l][r] = best coins for balloons l..r",
    "Try each k as the last balloon",
    "dp[l][k − 1] + a[l − 1]·a[k]·a[r + 1] + dp[k + 1][r]"
  ],
  "time": "O(n³)",
  "space": "O(n²)",
  "complexityWhy": "Three nested loops.",
  "figure": {
    "k": "flow",
    "s": [
      "[3,1,5,8] → burst 1: 3·1·5 = 15",
      "[3,5,8] → burst 5: 3·5·8 = 120",
      "[3,8] → burst 3: 1·3·8 = 24",
      "!burst 8: 1·8·1 = 8 → total 167"
    ],
    "cap": "One optimal order gives 167."
  },
  "code": "class Solution {\n  public int maxCoins(int[] nums) {\n    int n = nums.length;\n    int[] a = new int[n + 2];                               // pad both ends with 1\n    a[0] = a[n + 1] = 1;\n    for (int i = 0; i < n; i++) a[i + 1] = nums[i];\n    int[][] dp = new int[n + 2][n + 2];                     // dp[l][r]: best coins for balloons l..r\n    for (int len = 1; len <= n; len++) {\n      for (int left = 1; left + len - 1 <= n; left++) {\n        int right = left + len - 1;\n        for (int k = left; k <= right; k++) {               // k = the LAST balloon to burst\n          dp[left][right] = Math.max(dp[left][right],\n              dp[left][k - 1] + a[left - 1] * a[k] * a[right + 1] + dp[k + 1][right]);\n        }\n      }\n    }\n    return dp[1][n];\n  }\n}",
  "method": "maxCoins",
  "defaultInput": "[3,1,5,8]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          1,
          5,
          8
        ]
      ],
      "expected": 167
    },
    {
      "name": "Two balloons",
      "args": [
        [
          1,
          5
        ]
      ],
      "expected": 10
    },
    {
      "name": "Single balloon",
      "args": [
        [
          7
        ]
      ],
      "expected": 7
    },
    {
      "name": "No balloons",
      "args": [
        []
      ],
      "expected": 0
    },
    {
      "name": "Classic",
      "args": [
        [
          9,
          76,
          64,
          21
        ]
      ],
      "expected": 116718
    },
    {
      "name": "Two small",
      "args": [
        [
          3,
          1
        ]
      ],
      "expected": 6
    }
  ],
  "challenge": {
    "question": "What is the maximum number of coins from bursting [3,1,5]?",
    "input": "[3,1,5]",
    "options": [
      "17",
      "35",
      "34",
      "37"
    ],
    "answer": 1,
    "explanation": "Burst 1 first (3·1·5 = 15), then 3 (1·3·5 = 15), then 5 (1·5·1 = 5) → 35 coins."
  },
  "memory": {
    "remember": "Think about the LAST balloon to burst in a range —\nit splits the problem cleanly.",
    "pattern": "Interval DP table"
  }
};

export default problem;
