// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H035",
  "number": 35,
  "slug": "palindromic-substrings-count",
  "title": "Palindromic Substrings (Count)",
  "category": "Strings",
  "definition": "Count how many substrings are palindromes.",
  "example": {
    "input": "\"aaa\"",
    "output": "6"
  },
  "approach": "Every palindrome mirrors around a centre. For each centre grow outwards and count every success.",
  "keyIdea": [
    "Try each centre (odd length) and each gap (even length)",
    "Expand while both ends match",
    "Each successful expansion = one palindrome"
  ],
  "time": "O(n²)",
  "space": "O(1)",
  "complexityWhy": "n centres, each expands at most n steps.",
  "figure": {
    "k": "flow",
    "s": [
      "a  a  a  →  3 single letters",
      "aa  aa  →  2 pairs",
      "aaa  →  1 triple",
      "!3 + 2 + 1 = 6"
    ],
    "cap": "Every centre can grow into several palindromes."
  },
  "code": "class Solution {\n  public int countSubstrings(String s) {\n    int count = 0;\n    for (int i = 0; i < s.length(); i++) {\n      count += expand(s, i, i);        // odd length\n      count += expand(s, i, i + 1);    // even length\n    }\n    return count;\n  }\n  private int expand(String s, int l, int r) {\n    int found = 0;\n    while (l >= 0 && r < s.length() && s.charAt(l) == s.charAt(r)) { found++; l--; r++; }\n    return found;\n  }\n}",
  "method": "countSubstrings",
  "defaultInput": "\"aaa\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "aaa"
      ],
      "expected": 6
    },
    {
      "name": "Distinct letters",
      "args": [
        "abc"
      ],
      "expected": 3
    },
    {
      "name": "Single",
      "args": [
        "a"
      ],
      "expected": 1
    },
    {
      "name": "Even palindrome",
      "args": [
        "abba"
      ],
      "expected": 6
    },
    {
      "name": "Two",
      "args": [
        "aa"
      ],
      "expected": 3
    },
    {
      "name": "Mixed",
      "args": [
        "aabaa"
      ],
      "expected": 9
    }
  ],
  "challenge": {
    "question": "How many palindromic substrings are there?",
    "input": "\"level\"",
    "options": [
      "7",
      "10",
      "5",
      "9"
    ],
    "answer": 0,
    "explanation": "5 single letters + \"eve\" + \"level\" = 7 palindromic substrings."
  },
  "memory": {
    "remember": "2n − 1 centres,\neach expands while both ends match.",
    "pattern": "Expand around every centre"
  }
};

export default problem;
