// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H106",
  "number": 106,
  "slug": "remove-nth-node-from-end",
  "title": "Remove Nth Node From End",
  "category": "Linked List",
  "definition": "Remove the nth node from the end of the list.",
  "example": {
    "input": "1→2→3→4→5, n = 2",
    "output": "1→2→3→5"
  },
  "approach": "Move a fast pointer n steps ahead, then move both pointers together. When fast reaches the end, slow is right before the node to delete.",
  "keyIdea": [
    "Dummy node before head",
    "Move fast n + 1 steps",
    "Move fast and slow together until fast is null",
    "slow.next = slow.next.next"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass.",
  "figure": {
    "k": "list",
    "v": [
      1,
      2,
      3,
      4,
      5
    ],
    "no": [
      3
    ],
    "ok": [
      2
    ],
    "p": {
      "2": "slow",
      "4": "fast"
    },
    "cap": "Keep a gap of n between the pointers; when fast ends, slow is just before the target."
  },
  "code": "class Solution {\n  public ListNode removeNthFromEnd(ListNode head, int n) {\n    ListNode dummy = new ListNode(0, head);\n    ListNode fast = dummy, slow = dummy;\n    for (int i = 0; i <= n; i++) fast = fast.next;      // create a gap\n    while (fast != null) { fast = fast.next; slow = slow.next; }\n    slow.next = slow.next.next;                         // slow stops before the target\n    return dummy.next;\n  }\n}",
  "method": "removeNthFromEnd",
  "defaultInput": "[1,2,3,4,5], 2",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ],
        2
      ],
      "expected": [
        1,
        2,
        3,
        5
      ]
    },
    {
      "name": "Remove the only node",
      "args": [
        [
          1
        ],
        1
      ],
      "expected": null
    },
    {
      "name": "Remove the last",
      "args": [
        [
          1,
          2
        ],
        1
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "Remove the head",
      "args": [
        [
          1,
          2
        ],
        2
      ],
      "expected": [
        2
      ]
    },
    {
      "name": "Remove the head of three",
      "args": [
        [
          1,
          2,
          3
        ],
        3
      ],
      "expected": [
        2,
        3
      ]
    },
    {
      "name": "Longer list",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          6
        ],
        4
      ],
      "expected": [
        1,
        2,
        4,
        5,
        6
      ]
    }
  ],
  "challenge": {
    "question": "What is the list after removing the 3rd node from the end?",
    "input": "[10,20,30,40,50,60], 3",
    "options": [
      "[60,50,30,20,10]",
      "[20,30,50,60,10]",
      "[10,20,30,50,60]",
      "[10,20,30,50]"
    ],
    "answer": 2,
    "explanation": "Move one pointer 3 steps ahead, then walk both until it reaches the end: the other stops just before 40, so 40 is removed."
  },
  "memory": {
    "remember": "Two pointers n apart —\nwhen the front one ends, the back one is at the spot.",
    "pattern": "Two pointers with a gap of n"
  }
};

export default problem;
