// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H007",
  "number": 7,
  "slug": "merge-two-sorted-arrays",
  "title": "Merge Two Sorted Arrays",
  "category": "Arrays",
  "definition": "Merge two sorted arrays into one sorted array.",
  "example": {
    "input": "[1,3,5], [2,4,6]",
    "output": "[1,2,3,4,5,6]"
  },
  "approach": "Look at the front of both arrays, copy the smaller one and move that pointer. When one array ends, copy the rest of the other.",
  "keyIdea": [
    "Pointers i (array a) and j (array b)",
    "Copy the smaller of a[i] and b[j]",
    "Move that pointer",
    "Copy the leftovers"
  ],
  "time": "O(n+m)",
  "space": "O(n+m)",
  "complexityWhy": "Every element is copied once.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "a",
        "v": [
          1,
          3,
          5
        ],
        "ok": [
          0
        ],
        "p": {
          "0": "i"
        }
      },
      {
        "l": "b",
        "v": [
          2,
          4,
          6
        ],
        "hi": [
          0
        ],
        "p": {
          "0": "j"
        }
      },
      {
        "l": "out",
        "v": [
          1,
          2,
          3,
          4,
          5,
          6
        ],
        "ok": [
          0
        ]
      }
    ],
    "cap": "Take the smaller front value each time."
  },
  "code": "class Solution {\n  public int[] merge(int[] a, int[] b) {\n    int[] result = new int[a.length + b.length];\n    int i = 0, j = 0, k = 0;\n    while (i < a.length && j < b.length) {\n      if (a[i] <= b[j]) result[k++] = a[i++];\n      else result[k++] = b[j++];\n    }\n    while (i < a.length) result[k++] = a[i++];         // leftovers\n    while (j < b.length) result[k++] = b[j++];\n    return result;\n  }\n}",
  "method": "merge",
  "defaultInput": "[1,3,5], [2,4,6]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          3,
          5
        ],
        [
          2,
          4,
          6
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "name": "Empty second",
      "args": [
        [
          1,
          2,
          3
        ],
        []
      ],
      "expected": [
        1,
        2,
        3
      ]
    },
    {
      "name": "Empty first",
      "args": [
        [],
        [
          4,
          5
        ]
      ],
      "expected": [
        4,
        5
      ]
    },
    {
      "name": "Overlapping",
      "args": [
        [
          1,
          4,
          4,
          9
        ],
        [
          2,
          4,
          10
        ]
      ],
      "expected": [
        1,
        2,
        4,
        4,
        4,
        9,
        10
      ]
    },
    {
      "name": "All before",
      "args": [
        [
          1,
          2
        ],
        [
          3,
          4
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          -5,
          -1,
          3
        ],
        [
          -3,
          0,
          8
        ]
      ],
      "expected": [
        -5,
        -3,
        -1,
        0,
        3,
        8
      ]
    }
  ],
  "challenge": {
    "question": "What is the merged array?",
    "input": "[1,5,9], [2,3,10]",
    "options": [
      "[2,3,5,9,10,1]",
      "[2,1,3,5,9,10]",
      "[1,2,3,5,9,10]",
      "[1,2,3,5,9]"
    ],
    "answer": 2,
    "explanation": "Always take the smaller front value: 1, 2, 3, 5, 9 — then the leftover 10 is copied at the end."
  },
  "memory": {
    "remember": "Take the smaller front value,\nthen move that pointer.",
    "pattern": "Two-pointer merge"
  }
};

export default problem;
