// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H024",
  "number": 24,
  "slug": "longest-substring-without-repeating-characters",
  "title": "Longest Substring Without Repeating Characters",
  "category": "Strings",
  "definition": "Find the longest piece of the string that has no repeated letters.",
  "example": {
    "input": "\"abcabcbb\"",
    "output": "3  (\"abc\")"
  },
  "approach": "Slide a window. When a letter repeats, move the left edge just past the last place we saw that letter.",
  "keyIdea": [
    "Map: letter → last index",
    "Move right one step at a time",
    "Letter seen inside the window → jump left past it",
    "Track the longest window"
  ],
  "time": "O(n)",
  "space": "O(k)",
  "complexityWhy": "One pass with a HashMap.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "a",
          "b",
          "c",
          "a",
          "b",
          "c",
          "b",
          "b"
        ],
        "ok": [
          0,
          1,
          2
        ],
        "br": [
          [
            0,
            2,
            "length 3"
          ]
        ]
      },
      {
        "v": [
          "a",
          "b",
          "c",
          "a",
          "b",
          "c",
          "b",
          "b"
        ],
        "hi": [
          1,
          2,
          3
        ],
        "br": [
          [
            1,
            3,
            "window slides"
          ]
        ]
      }
    ],
    "cap": "When a letter repeats, the left edge jumps past its old spot."
  },
  "code": "class Solution {\n  public int lengthOfLongestSubstring(String s) {\n    Map<Character, Integer> lastSeen = new HashMap<>();\n    int left = 0, best = 0;\n    for (int right = 0; right < s.length(); right++) {\n      char ch = s.charAt(right);\n      if (lastSeen.containsKey(ch) && lastSeen.get(ch) >= left) left = lastSeen.get(ch) + 1;\n      lastSeen.put(ch, right);\n      best = Math.max(best, right - left + 1);\n    }\n    return best;\n  }\n}",
  "method": "lengthOfLongestSubstring",
  "defaultInput": "\"abcabcbb\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "abcabcbb"
      ],
      "expected": 3
    },
    {
      "name": "All same",
      "args": [
        "bbbbb"
      ],
      "expected": 1
    },
    {
      "name": "Empty",
      "args": [
        ""
      ],
      "expected": 0
    },
    {
      "name": "Single",
      "args": [
        "z"
      ],
      "expected": 1
    },
    {
      "name": "Window slides",
      "args": [
        "pwwkew"
      ],
      "expected": 3
    },
    {
      "name": "Repeat at the end",
      "args": [
        "abcdab"
      ],
      "expected": 4
    }
  ],
  "challenge": {
    "question": "How long is the longest substring without repeating characters?",
    "input": "\"abcdbea\"",
    "options": [
      "8",
      "6",
      "4",
      "5"
    ],
    "answer": 3,
    "explanation": "When the second 'b' appears, the left edge jumps past the old 'b'. The window \"cdbea\" has no repeats → length 5."
  },
  "memory": {
    "remember": "Slide the window; when a letter repeats,\njump the left edge past its old spot.",
    "pattern": "Sliding window + last-seen Map"
  }
};

export default problem;
