// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H096",
  "number": 96,
  "slug": "dijkstras-algorithm",
  "title": "Dijkstra's Algorithm (Shortest Path)",
  "category": "Graph",
  "definition": "Shortest distance from a source to every node (non-negative weights).",
  "example": {
    "input": "5 nodes, weighted edges, source 0",
    "output": "[0,3,1,4,7]"
  },
  "approach": "Repeat: pick the closest node not yet finished, then see if going through it gives a shorter path to its neighbours.",
  "keyIdea": [
    "dist[source] = 0, others = ∞",
    "Pick the unfinished node with the smallest dist",
    "Relax its outgoing edges",
    "Repeat until all are finished"
  ],
  "time": "O(V²)",
  "space": "O(V)",
  "complexityWhy": "Scanning all nodes to find the minimum each time.",
  "figure": {
    "k": "graph",
    "n": 5,
    "e": [
      [
        0,
        1,
        4
      ],
      [
        0,
        2,
        1
      ],
      [
        2,
        1,
        2
      ],
      [
        1,
        3,
        1
      ],
      [
        2,
        3,
        5
      ],
      [
        3,
        4,
        3
      ]
    ],
    "d": true,
    "pos": [
      [
        0,
        3
      ],
      [
        3,
        0
      ],
      [
        3,
        6
      ],
      [
        6,
        3
      ],
      [
        9,
        3
      ]
    ],
    "he": [
      1,
      2,
      3,
      5
    ],
    "ok": [
      0
    ],
    "cap": "Shortest path to node 4: 0 → 2 → 1 → 3 → 4 (cost 7)."
  },
  "better": {
    "name": "Dijkstra with a min-heap",
    "time": "O((V + E) log V)",
    "space": "O(V + E)",
    "code": "class Solution {\n  public int[] dijkstra(int n, int[][] edges, int source) {\n    List<List<int[]>> graph = new ArrayList<>();\n    for (int i = 0; i < n; i++) graph.add(new ArrayList<>());\n    for (int[] e : edges) graph.get(e[0]).add(new int[]{e[1], e[2]});\n    int[] dist = new int[n];\n    Arrays.fill(dist, Integer.MAX_VALUE);\n    dist[source] = 0;\n    PriorityQueue<int[]> heap = new PriorityQueue<>((a, b) -> Integer.compare(a[0], b[0]));   // {distance, node}\n    heap.add(new int[]{0, source});\n    while (!heap.isEmpty()) {\n      int[] top = heap.poll();\n      int d = top[0], u = top[1];\n      if (d > dist[u]) continue;                       // outdated entry\n      for (int[] edge : graph.get(u)) {\n        if (d + edge[1] < dist[edge[0]]) {\n          dist[edge[0]] = d + edge[1];\n          heap.add(new int[]{dist[edge[0]], edge[0]});\n        }\n      }\n    }\n    return dist;\n  }\n}"
  },
  "code": "class Solution {\n  public int[] dijkstra(int n, int[][] edges, int source) {\n    List<List<int[]>> graph = new ArrayList<>();\n    for (int i = 0; i < n; i++) graph.add(new ArrayList<>());\n    for (int[] e : edges) graph.get(e[0]).add(new int[]{e[1], e[2]});   // {to, weight}\n    int[] dist = new int[n];\n    Arrays.fill(dist, Integer.MAX_VALUE);\n    boolean[] done = new boolean[n];\n    dist[source] = 0;\n    for (int step = 0; step < n; step++) {\n      int u = -1;\n      for (int i = 0; i < n; i++) {                    // closest unfinished node\n        if (!done[i] && (u == -1 || dist[i] < dist[u])) u = i;\n      }\n      if (dist[u] == Integer.MAX_VALUE) break;         // the rest are unreachable\n      done[u] = true;\n      for (int[] edge : graph.get(u)) {\n        if (dist[u] + edge[1] < dist[edge[0]]) dist[edge[0]] = dist[u] + edge[1];   // relax\n      }\n    }\n    return dist;\n  }\n}",
  "method": "dijkstra",
  "defaultInput": "5, [[0,1,4],[0,2,1],[2,1,2],[1,3,1],[2,3,5],[3,4,3]], 0",
  "tests": [
    {
      "name": "Example",
      "args": [
        5,
        [
          [
            0,
            1,
            4
          ],
          [
            0,
            2,
            1
          ],
          [
            2,
            1,
            2
          ],
          [
            1,
            3,
            1
          ],
          [
            2,
            3,
            5
          ],
          [
            3,
            4,
            3
          ]
        ],
        0
      ],
      "expected": [
        0,
        3,
        1,
        4,
        7
      ]
    },
    {
      "name": "Unreachable node",
      "args": [
        3,
        [
          [
            0,
            1,
            2
          ]
        ],
        0
      ],
      "expected": [
        0,
        2,
        2147483647
      ]
    },
    {
      "name": "Single node",
      "args": [
        1,
        [],
        0
      ],
      "expected": [
        0
      ]
    },
    {
      "name": "Source in the middle",
      "args": [
        3,
        [
          [
            0,
            1,
            1
          ],
          [
            1,
            2,
            1
          ]
        ],
        1
      ],
      "expected": [
        2147483647,
        0,
        1
      ]
    },
    {
      "name": "Detour is cheaper",
      "args": [
        3,
        [
          [
            0,
            1,
            10
          ],
          [
            0,
            2,
            3
          ],
          [
            2,
            1,
            4
          ]
        ],
        0
      ],
      "expected": [
        0,
        7,
        3
      ]
    },
    {
      "name": "Zero weights",
      "args": [
        3,
        [
          [
            0,
            1,
            0
          ],
          [
            1,
            2,
            0
          ]
        ],
        0
      ],
      "expected": [
        0,
        0,
        0
      ]
    }
  ],
  "challenge": {
    "question": "What are the shortest distances from node 0?",
    "input": "4, [[0,1,5],[0,2,1],[2,1,2],[1,3,1]], 0",
    "options": [
      "[1,4,2,5]",
      "[0,3,1,4]",
      "[0,3,1]",
      "[3,1,4,0]"
    ],
    "answer": 1,
    "explanation": "Node 1: the direct edge costs 5, but 0→2→1 costs 1 + 2 = 3. Node 3: 3 + 1 = 4 → [0,3,1,4]."
  },
  "memory": {
    "remember": "Always finalise the closest unfinished node,\nthen relax its edges.",
    "pattern": "Dijkstra with a min-heap"
  }
};

export default problem;
