// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H110",
  "number": 110,
  "slug": "reverse-nodes-in-k-group",
  "title": "Reverse Nodes in k-Group",
  "category": "Linked List",
  "definition": "Reverse the list in groups of k nodes. Leave a short last group as it is.",
  "example": {
    "input": "1→2→3→4→5, k = 2",
    "output": "2→1→4→3→5"
  },
  "approach": "Put the values in an array, reverse each block of k, and write them back into the nodes.",
  "keyIdea": [
    "Copy values into an array",
    "Reverse every full block of k values",
    "Write the values back"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "Uses an array of all values.",
  "figure": [
    {
      "k": "list",
      "v": [
        1,
        2,
        3,
        4,
        5
      ],
      "hi": [
        0,
        1,
        2,
        3
      ]
    },
    {
      "k": "list",
      "v": [
        2,
        1,
        4,
        3,
        5
      ],
      "ok": [
        0,
        1,
        2,
        3
      ],
      "cap": "Each full pair is reversed; the last node 5 stays."
    }
  ],
  "better": {
    "name": "Reverse each group in place",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public ListNode reverseKGroup(ListNode head, int k) {\n    ListNode dummy = new ListNode(0, head), groupPrev = dummy;\n    while (true) {\n      ListNode kth = groupPrev;\n      for (int i = 0; i < k && kth != null; i++) kth = kth.next;   // find the group's last node\n      if (kth == null) break;                                       // fewer than k nodes left\n      ListNode groupNext = kth.next, prev = groupNext, curr = groupPrev.next;\n      while (curr != groupNext) {                                   // reverse this group\n        ListNode next = curr.next; curr.next = prev; prev = curr; curr = next;\n      }\n      ListNode oldFirst = groupPrev.next;\n      groupPrev.next = kth;\n      groupPrev = oldFirst;\n    }\n    return dummy.next;\n  }\n}"
  },
  "code": "class Solution {\n  public ListNode reverseKGroup(ListNode head, int k) {\n    List<Integer> values = new ArrayList<>();\n    for (ListNode n = head; n != null; n = n.next) values.add(n.val);\n    for (int start = 0; start + k <= values.size(); start += k) {\n      int l = start, r = start + k - 1;                // reverse one full block\n      while (l < r) {\n        int temp = values.get(l); values.set(l, values.get(r)); values.set(r, temp);\n        l++; r--;\n      }\n    }\n    ListNode node = head;\n    for (int v : values) { node.val = v; node = node.next; }\n    return head;\n  }\n}",
  "method": "reverseKGroup",
  "defaultInput": "[1,2,3,4,5], 2",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ],
        2
      ],
      "expected": [
        2,
        1,
        4,
        3,
        5
      ]
    },
    {
      "name": "k = 3",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ],
        3
      ],
      "expected": [
        3,
        2,
        1,
        4,
        5
      ]
    },
    {
      "name": "Two full groups",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          6
        ],
        3
      ],
      "expected": [
        3,
        2,
        1,
        6,
        5,
        4
      ]
    },
    {
      "name": "k = 1",
      "args": [
        [
          1
        ],
        1
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "k bigger than the list",
      "args": [
        [
          1,
          2
        ],
        3
      ],
      "expected": [
        1,
        2
      ]
    },
    {
      "name": "Empty list",
      "args": [
        [],
        2
      ],
      "expected": null
    }
  ],
  "challenge": {
    "question": "What is the list after reversing it in groups of k = 3?",
    "input": "[1,2,3,4,5,6,7], 3",
    "options": [
      "[2,1,6,5,4,7,3]",
      "[7,4,5,6,1,2,3]",
      "[1,2,3,4,5,6,7]",
      "[3,2,1,6,5,4,7]"
    ],
    "answer": 3,
    "explanation": "Each full group of three is reversed (1,2,3 → 3,2,1 and 4,5,6 → 6,5,4); the last single node 7 doesn't make a full group and stays."
  },
  "memory": {
    "remember": "Reverse one group of k at a time,\nand stop if fewer than k nodes remain.",
    "pattern": "Reverse each group in place"
  }
};

export default problem;
