// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H100",
  "number": 100,
  "slug": "accounts-merge",
  "title": "Accounts Merge (Disjoint Set Union)",
  "category": "Graph",
  "definition": "Merge accounts that share at least one email.",
  "example": {
    "input": "John: [a, b] · John: [a, c] · Mary: [d] · John: [e]",
    "output": "John: [a,b,c] · Mary: [d] · John: [e]"
  },
  "approach": "Emails are nodes. Emails in the same account are connected. Each connected group is one person.",
  "keyIdea": [
    "Connect every email to the account's first email",
    "DFS to collect each connected group",
    "Sort the emails, add the name"
  ],
  "time": "O(N log N)",
  "space": "O(N)",
  "complexityWhy": "N = total emails. Sorting each group dominates.",
  "figure": {
    "k": "flow",
    "s": [
      "John [a, b] + John [a, c] share 'a' → one person",
      "!John: a, b, c",
      "Mary: d   ·   John: e (nothing shared)"
    ],
    "cap": "A shared email joins two accounts."
  },
  "better": {
    "name": "Union-Find over email ids",
    "time": "O(N log N)",
    "space": "O(N)",
    "code": "class Solution {\n  private int[] parent;\n  private int find(int x) { return parent[x] == x ? x : (parent[x] = find(parent[x])); }\n  public List<List<String>> accountsMerge(List<List<String>> accounts) {\n    Map<String, Integer> emailId = new HashMap<>();\n    List<String> owner = new ArrayList<>();\n    for (List<String> acc : accounts) {\n      for (int i = 1; i < acc.size(); i++) {\n        if (!emailId.containsKey(acc.get(i))) { emailId.put(acc.get(i), emailId.size()); owner.add(acc.get(0)); }\n      }\n    }\n    parent = new int[emailId.size()];\n    for (int i = 0; i < parent.length; i++) parent[i] = i;\n    for (List<String> acc : accounts) {\n      for (int i = 2; i < acc.size(); i++) {\n        parent[find(emailId.get(acc.get(1)))] = find(emailId.get(acc.get(i)));   // union\n      }\n    }\n    Map<Integer, List<String>> groups = new HashMap<>();                          // root -> emails\n    for (Map.Entry<String, Integer> e : emailId.entrySet()) {\n      int root = find(e.getValue());\n      if (!groups.containsKey(root)) groups.put(root, new ArrayList<>());\n      groups.get(root).add(e.getKey());\n    }\n    List<List<String>> result = new ArrayList<>();\n    for (Map.Entry<Integer, List<String>> g : groups.entrySet()) {\n      List<String> emails = g.getValue();\n      Collections.sort(emails);\n      emails.add(0, owner.get(g.getKey()));\n      result.add(emails);\n    }\n    return result;\n  }\n}"
  },
  "code": "class Solution {\n  public List<List<String>> accountsMerge(List<List<String>> accounts) {\n    Map<String, Set<String>> graph = new HashMap<>();\n    Map<String, String> owner = new HashMap<>();\n    for (List<String> account : accounts) {\n      String name = account.get(0), first = account.get(1);\n      for (int i = 1; i < account.size(); i++) {\n        String email = account.get(i);\n        owner.put(email, name);\n        if (!graph.containsKey(email)) graph.put(email, new HashSet<>());\n        if (!graph.containsKey(first)) graph.put(first, new HashSet<>());\n        graph.get(email).add(first);                       // link every email to the first one\n        graph.get(first).add(email);\n      }\n    }\n    Set<String> seen = new HashSet<>();\n    List<List<String>> result = new ArrayList<>();\n    for (String email : graph.keySet()) {\n      if (!seen.add(email)) continue;\n      List<String> group = new ArrayList<>();\n      Deque<String> stack = new ArrayDeque<>();\n      stack.push(email);\n      while (!stack.isEmpty()) {                           // DFS over one connected group\n        String e = stack.pop();\n        group.add(e);\n        for (String next : graph.get(e)) if (seen.add(next)) stack.push(next);\n      }\n      Collections.sort(group);\n      group.add(0, owner.get(email));\n      result.add(group);\n    }\n    return result;\n  }\n}",
  "method": "accountsMerge",
  "unordered": true,
  "defaultInput": "[[\"John\",\"a\",\"b\"],[\"John\",\"a\",\"c\"],[\"Mary\",\"d\"],[\"John\",\"e\"]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            "John",
            "a",
            "b"
          ],
          [
            "John",
            "a",
            "c"
          ],
          [
            "Mary",
            "d"
          ],
          [
            "John",
            "e"
          ]
        ]
      ],
      "expected": [
        [
          "John",
          "a",
          "b",
          "c"
        ],
        [
          "Mary",
          "d"
        ],
        [
          "John",
          "e"
        ]
      ]
    },
    {
      "name": "Nothing to merge",
      "args": [
        [
          [
            "A",
            "x"
          ],
          [
            "B",
            "y"
          ]
        ]
      ],
      "expected": [
        [
          "A",
          "x"
        ],
        [
          "B",
          "y"
        ]
      ]
    },
    {
      "name": "Chain of merges",
      "args": [
        [
          [
            "A",
            "a",
            "b"
          ],
          [
            "A",
            "b",
            "c"
          ],
          [
            "A",
            "c",
            "d"
          ]
        ]
      ],
      "expected": [
        [
          "A",
          "a",
          "b",
          "c",
          "d"
        ]
      ]
    },
    {
      "name": "One account",
      "args": [
        [
          [
            "Z",
            "z1",
            "z2"
          ]
        ]
      ],
      "expected": [
        [
          "Z",
          "z1",
          "z2"
        ]
      ]
    },
    {
      "name": "Two groups with one name",
      "args": [
        [
          [
            "Sam",
            "s1"
          ],
          [
            "Sam",
            "s2"
          ],
          [
            "Sam",
            "s1",
            "s3"
          ]
        ]
      ],
      "expected": [
        [
          "Sam",
          "s1",
          "s3"
        ],
        [
          "Sam",
          "s2"
        ]
      ]
    },
    {
      "name": "Same email twice",
      "args": [
        [
          [
            "Kim",
            "k1",
            "k1"
          ]
        ]
      ],
      "expected": [
        [
          "Kim",
          "k1"
        ]
      ]
    }
  ],
  "challenge": {
    "question": "How many accounts remain after merging?",
    "input": "[[\"John\",\"a\",\"b\"],[\"John\",\"b\",\"c\"],[\"Mary\",\"d\"],[\"Mary\",\"e\"]]",
    "options": [
      "1",
      "2",
      "3",
      "4"
    ],
    "answer": 2,
    "explanation": "The first two John accounts share 'b', so they become one account. The two Mary accounts share no email, so 3 accounts remain."
  },
  "memory": {
    "remember": "A shared email joins two accounts —\ntreat emails as nodes and merge their groups.",
    "pattern": "Union-Find over email ids"
  }
};

export default problem;
