// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H067",
  "number": 67,
  "slug": "koko-eating-bananas",
  "title": "Koko Eating Bananas (Binary Search on Answer)",
  "category": "Binary Search",
  "definition": "Bananas are in piles. Find the slowest eating speed that still finishes all piles within h hours.",
  "example": {
    "input": "piles = [3,6,7,11], h = 8",
    "output": "4"
  },
  "approach": "The answer (speed) is between 1 and the biggest pile. If a speed is fast enough try slower, otherwise go faster. That is a binary search on the answer.",
  "keyIdea": [
    "lo = 1, hi = biggest pile",
    "Hours at speed mid = sum of ceil(pile / mid)",
    "Fast enough → hi = mid; too slow → lo = mid + 1"
  ],
  "time": "O(n log maxPile)",
  "space": "O(1)",
  "complexityWhy": "About log(max pile) steps, each needs one pass.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "speed",
        "v": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11
        ],
        "no": [
          0,
          1,
          2
        ],
        "ok": [
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10
        ],
        "ix": 1
      }
    ],
    "cap": "Too slow (red) or fast enough (green). Find the boundary."
  },
  "code": "class Solution {\n  public int minEatingSpeed(int[] piles, int h) {\n    int lo = 1, hi = 0;\n    for (int pile : piles) hi = Math.max(hi, pile);\n    while (lo < hi) {\n      int mid = lo + (hi - lo) / 2;\n      long hours = 0;\n      for (int pile : piles) hours += (pile + mid - 1) / mid;\n      if (hours <= h) hi = mid;       // fast enough -> try slower\n      else lo = mid + 1;              // too slow -> speed up\n    }\n    return lo;\n  }\n}",
  "method": "minEatingSpeed",
  "defaultInput": "[3,6,7,11], 8",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          6,
          7,
          11
        ],
        8
      ],
      "expected": 4
    },
    {
      "name": "Exactly one pile per hour",
      "args": [
        [
          30,
          11,
          23,
          4,
          20
        ],
        5
      ],
      "expected": 30
    },
    {
      "name": "More hours",
      "args": [
        [
          30,
          11,
          23,
          4,
          20
        ],
        6
      ],
      "expected": 23
    },
    {
      "name": "Single pile",
      "args": [
        [
          10
        ],
        2
      ],
      "expected": 5
    },
    {
      "name": "Many hours",
      "args": [
        [
          1,
          1,
          1,
          1
        ],
        100
      ],
      "expected": 1
    },
    {
      "name": "Big piles",
      "args": [
        [
          312884470
        ],
        312884469
      ],
      "expected": 2
    }
  ],
  "challenge": {
    "question": "What is the minimum eating speed per hour?",
    "input": "[30,11,23,4,20], 6",
    "options": [
      "11",
      "21",
      "24",
      "23"
    ],
    "answer": 3,
    "explanation": "At speed 23 the piles take 2+1+1+1+1 = 6 hours, but at speed 22 they would take 7 hours — so 23 is the smallest speed that works."
  },
  "memory": {
    "remember": "Binary search the speed:\nthe smallest speed that finishes in h hours.",
    "pattern": "Binary search on the speed"
  }
};

export default problem;
