// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H044",
  "number": 44,
  "slug": "bucket-sort",
  "title": "Bucket Sort",
  "category": "Sorting Algorithms",
  "definition": "Spread values into buckets, sort each bucket, join them.",
  "example": {
    "input": "[0.42,0.32,0.23,0.52,0.25,0.47,0.51]",
    "output": "[0.23,0.25,0.32,0.42,0.47,0.51,0.52]"
  },
  "approach": "Drop numbers into labelled boxes by size. Sort the few numbers inside each box, then empty the boxes in order.",
  "keyIdea": [
    "Make n empty buckets",
    "Bucket index = floor(value × n)",
    "Sort each bucket, then concatenate"
  ],
  "time": "O(n) avg, O(n²) worst",
  "space": "O(n)",
  "complexityWhy": "Fast when values spread evenly.",
  "figure": {
    "k": "flow",
    "s": [
      "bucket 1 → 0.23  0.25",
      "bucket 2 → 0.32  0.42",
      "bucket 3 → 0.47  0.51  0.52",
      "!join → 0.23 0.25 0.32 0.42 0.47 0.51 0.52"
    ],
    "cap": "Each bucket is tiny, so sorting it is cheap."
  },
  "code": "class Solution {\n  public double[] bucketSort(double[] arr) {\n    int n = arr.length;\n    List<List<Double>> buckets = new ArrayList<>();\n    for (int i = 0; i < n; i++) buckets.add(new ArrayList<>());\n    for (double x : arr) {\n      buckets.get((int) (x * n)).add(x);                // works for values in [0, 1)\n    }\n    double[] result = new double[n];\n    int k = 0;\n    for (List<Double> bucket : buckets) {\n      Collections.sort(bucket);                         // small buckets -> fast\n      for (double x : bucket) result[k++] = x;\n    }\n    return result;\n  }\n}",
  "method": "bucketSort",
  "defaultInput": "[0.42,0.32,0.23,0.52,0.25,0.47,0.51]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          0.42,
          0.32,
          0.23,
          0.52,
          0.25,
          0.47,
          0.51
        ]
      ],
      "expected": [
        0.23,
        0.25,
        0.32,
        0.42,
        0.47,
        0.51,
        0.52
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          0.5
        ]
      ],
      "expected": [
        0.5
      ]
    },
    {
      "name": "Already sorted",
      "args": [
        [
          0.1,
          0.2,
          0.3
        ]
      ],
      "expected": [
        0.1,
        0.2,
        0.3
      ]
    },
    {
      "name": "Reversed",
      "args": [
        [
          0.9,
          0.5,
          0.1
        ]
      ],
      "expected": [
        0.1,
        0.5,
        0.9
      ]
    },
    {
      "name": "Duplicates",
      "args": [
        [
          0.3,
          0.3,
          0.1
        ]
      ],
      "expected": [
        0.1,
        0.3,
        0.3
      ]
    },
    {
      "name": "Close values",
      "args": [
        [
          0.51,
          0.5,
          0.52
        ]
      ],
      "expected": [
        0.5,
        0.51,
        0.52
      ]
    }
  ],
  "challenge": {
    "question": "With 7 numbers, which bucket does 0.47 go to? (index = floor(value × 7))",
    "input": "[0.42,0.32,0.23,0.52,0.25,0.47,0.51]",
    "options": [
      "2",
      "3",
      "4",
      "5"
    ],
    "answer": 1,
    "explanation": "floor(0.47 × 7) = floor(3.29) = 3, so 0.47 goes into bucket 3."
  },
  "memory": {
    "remember": "Spread into buckets, sort each tiny bucket,\nthen join them.",
    "pattern": "Buckets → Sort Each → Join"
  }
};

export default problem;
