// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H084",
  "number": 84,
  "slug": "serialize-deserialize-n-ary-tree",
  "title": "Serialize & Deserialize N-ary Tree",
  "category": "Trees",
  "definition": "Same idea for a tree where each node has many children.",
  "example": {
    "input": "1 → (3 → (5, 6), 2, 4)",
    "output": "\"1,3,3,2,5,0,6,0,2,0,4,0\""
  },
  "approach": "Write each node's value followed by how many children it has. That is enough to rebuild the shape.",
  "keyIdea": [
    "Preorder: write value, then child count",
    "Deserialize: read value, count, then build that many children"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "Each node is written and read once — already optimal.",
  "figure": [
    {
      "k": "nary",
      "t": [
        "1",
        [
          [
            "3",
            [
              [
                "5",
                []
              ],
              [
                "6",
                []
              ]
            ]
          ],
          [
            "2",
            []
          ],
          [
            "4",
            []
          ]
        ]
      ]
    },
    {
      "k": "txt",
      "lines": [
        "1,3 | 3,2 | 5,0 | 6,0 | 2,0 | 4,0"
      ]
    }
  ],
  "code": "class Node {\n  public int val;\n  public List<Node> children = new ArrayList<>();\n  public Node(int val) { this.val = val; }\n}\nclass Codec {\n  public String serialize(Node root) {\n    StringBuilder out = new StringBuilder();\n    if (root != null) write(root, out);\n    return out.toString();\n  }\n  private void write(Node node, StringBuilder out) {\n    if (out.length() > 0) out.append(',');\n    out.append(node.val).append(',').append(node.children.size());   // value, number of children\n    for (Node child : node.children) write(child, out);\n  }\n  private String[] nums;\n  private int pos;\n  public Node deserialize(String data) {\n    if (data.isEmpty()) return null;\n    nums = data.split(\",\");\n    pos = 0;\n    return build();\n  }\n  private Node build() {\n    Node node = new Node(Integer.parseInt(nums[pos++]));\n    int count = Integer.parseInt(nums[pos++]);\n    for (int k = 0; k < count; k++) node.children.add(build());\n    return node;\n  }\n}",
  "method": "Codec",
  "defaultInput": "[], [[\"serialize\",[1,[[3,[[5,[]],[6,[]]]],[2,[]],[4,[]]]]]]",
  "tests": [
    {
      "name": "Example: serialize",
      "args": [
        [],
        [
          [
            "serialize",
            [
              1,
              [
                [
                  3,
                  [
                    [
                      5,
                      []
                    ],
                    [
                      6,
                      []
                    ]
                  ]
                ],
                [
                  2,
                  []
                ],
                [
                  4,
                  []
                ]
              ]
            ]
          ]
        ]
      ],
      "expected": [
        "1,3,3,2,5,0,6,0,2,0,4,0"
      ]
    },
    {
      "name": "Example: deserialize",
      "args": [
        [],
        [
          [
            "deserialize",
            "1,3,3,2,5,0,6,0,2,0,4,0"
          ]
        ]
      ],
      "expected": [
        [
          1,
          [
            [
              3,
              [
                [
                  5,
                  []
                ],
                [
                  6,
                  []
                ]
              ]
            ],
            [
              2,
              []
            ],
            [
              4,
              []
            ]
          ]
        ]
      ]
    },
    {
      "name": "Single node",
      "args": [
        [],
        [
          [
            "serialize",
            [
              1,
              []
            ]
          ],
          [
            "deserialize",
            "1,0"
          ]
        ]
      ],
      "expected": [
        "1,0",
        [
          1,
          []
        ]
      ]
    },
    {
      "name": "Empty tree",
      "args": [
        [],
        [
          [
            "deserialize",
            ""
          ]
        ]
      ],
      "expected": [
        null
      ]
    },
    {
      "name": "Chain",
      "args": [
        [],
        [
          [
            "serialize",
            [
              1,
              [
                [
                  2,
                  [
                    [
                      3,
                      []
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ],
      "expected": [
        "1,1,2,1,3,0"
      ]
    },
    {
      "name": "Wide",
      "args": [
        [],
        [
          [
            "serialize",
            [
              1,
              [
                [
                  2,
                  []
                ],
                [
                  3,
                  []
                ],
                [
                  4,
                  []
                ],
                [
                  5,
                  []
                ]
              ]
            ]
          ]
        ]
      ],
      "expected": [
        "1,4,2,0,3,0,4,0,5,0"
      ]
    }
  ],
  "challenge": {
    "question": "What does serialize return? (the tree is 1 with children 2 and 3, and 3 has a child 4)",
    "input": "[], [[\"serialize\",[1,[[2,[]],[3,[[4,[]]]]]]]]",
    "options": [
      "\"1,2,2,0,3,1,4,0\"",
      "\"1,2,2,3,3,1,4,0\"",
      "\"1,3,2,0,3,1,4,0\"",
      "\"1,2,2,0,3,0,4,1\""
    ],
    "answer": 0,
    "explanation": "Every node writes its value and its number of children: 1 has 2 children, 2 has 0, 3 has 1 (the node 4, which has 0)."
  },
  "memory": {
    "remember": "Write each node as (value, child count) —\nthe count tells the reader when to stop.",
    "pattern": "Value + Child Count (Preorder)"
  }
};

export default problem;
