// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H142",
  "number": 142,
  "slug": "merge-k-sorted-lists",
  "title": "Merge K Sorted Lists",
  "category": "Heap / Priority Queue",
  "definition": "Merge k sorted linked lists into one sorted list.",
  "example": {
    "input": "[1→4→5, 1→3→4, 2→6]",
    "output": "1→1→2→3→4→4→5→6"
  },
  "approach": "Put the head of every list in a min-heap. Take the smallest and push its next node.",
  "keyIdea": [
    "Heap of the k list heads",
    "Poll the smallest and append it",
    "Push that node's next",
    "Repeat until the heap is empty"
  ],
  "time": "O(N log k)",
  "space": "O(k)",
  "complexityWhy": "Every node goes through the heap once.",
  "figure": [
    {
      "k": "list",
      "v": [
        1,
        4,
        5
      ]
    },
    {
      "k": "list",
      "v": [
        1,
        3,
        4
      ]
    },
    {
      "k": "list",
      "v": [
        2,
        6
      ]
    },
    {
      "k": "list",
      "v": [
        1,
        1,
        2,
        3,
        4,
        4,
        5,
        6
      ],
      "ok": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ],
      "cap": "The heap always holds the current head of each list."
    }
  ],
  "code": "class Solution {\n  public ListNode mergeKLists(ListNode[] lists) {\n    PriorityQueue<ListNode> heap = new PriorityQueue<>((a, b) -> a.val - b.val);\n    for (ListNode head : lists) if (head != null) heap.add(head);\n    ListNode dummy = new ListNode(0), tail = dummy;\n    while (!heap.isEmpty()) {\n      ListNode node = heap.poll();                            // smallest head among all lists\n      tail.next = node;\n      tail = node;\n      if (node.next != null) heap.add(node.next);             // that list offers its next node\n    }\n    return dummy.next;\n  }\n}",
  "method": "mergeKLists",
  "defaultInput": "[[1,4,5],[1,3,4],[2,6]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            1,
            4,
            5
          ],
          [
            1,
            3,
            4
          ],
          [
            2,
            6
          ]
        ]
      ],
      "expected": [
        1,
        1,
        2,
        3,
        4,
        4,
        5,
        6
      ]
    },
    {
      "name": "No lists",
      "args": [
        []
      ],
      "expected": null
    },
    {
      "name": "One empty list",
      "args": [
        [
          []
        ]
      ],
      "expected": null
    },
    {
      "name": "Single list",
      "args": [
        [
          [
            1
          ]
        ]
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "Two lists",
      "args": [
        [
          [
            1,
            2
          ],
          [
            3,
            4
          ]
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "name": "Single values",
      "args": [
        [
          [
            5
          ],
          [
            1
          ],
          [
            3
          ]
        ]
      ],
      "expected": [
        1,
        3,
        5
      ]
    }
  ],
  "challenge": {
    "question": "What is the merged list?",
    "input": "[[1,5],[2,3],[4]]",
    "options": [
      "[2,3,4,5,6]",
      "[1,2,3,4,5]",
      "[2,1,3,4,5]",
      "[1,2,3,4]"
    ],
    "answer": 1,
    "explanation": "The heap always holds the smallest front node of each list: 1, then 2, 3, 4 and finally 5."
  },
  "memory": {
    "remember": "A min-heap holds the front node of every list —\npop the smallest, push its successor.",
    "pattern": "Min-heap of the k list heads"
  }
};

export default problem;
