// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H066",
  "number": 66,
  "slug": "integer-square-root",
  "title": "Integer Square Root",
  "category": "Binary Search",
  "definition": "Find the square root of x, rounded down to a whole number, without a built-in sqrt.",
  "example": {
    "input": "x = 8",
    "output": "2"
  },
  "approach": "Binary search for the biggest number whose square is at most x.",
  "keyIdea": [
    "Search between 0 and x",
    "mid × mid ≤ x → remember mid and try bigger",
    "Otherwise try smaller",
    "Use long so mid × mid cannot overflow"
  ],
  "time": "O(log x)",
  "space": "O(1)",
  "complexityWhy": "The range halves every step.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "guess",
        "v": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "ok": [
          2
        ],
        "no": [
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "ix": 1
      }
    ],
    "cap": "2² = 4 ≤ 8 but 3² = 9 > 8, so the answer is 2."
  },
  "code": "class Solution {\n  public int mySqrt(int x) {\n    int lo = 0, hi = x, answer = 0;\n    while (lo <= hi) {\n      int mid = lo + (hi - lo) / 2;\n      if ((long) mid * mid <= x) { answer = mid; lo = mid + 1; }   // mid works, try bigger\n      else hi = mid - 1;\n    }\n    return answer;\n  }\n}",
  "method": "mySqrt",
  "defaultInput": "8",
  "tests": [
    {
      "name": "Example",
      "args": [
        8
      ],
      "expected": 2
    },
    {
      "name": "Perfect square",
      "args": [
        49
      ],
      "expected": 7
    },
    {
      "name": "Zero",
      "args": [
        0
      ],
      "expected": 0
    },
    {
      "name": "One",
      "args": [
        1
      ],
      "expected": 1
    },
    {
      "name": "Just below a square",
      "args": [
        99
      ],
      "expected": 9
    },
    {
      "name": "Large",
      "args": [
        2147395599
      ],
      "expected": 46339
    }
  ],
  "challenge": {
    "question": "What is the integer square root of 50?",
    "input": "50",
    "options": [
      "8",
      "6",
      "10",
      "7"
    ],
    "answer": 3,
    "explanation": "7 × 7 = 49 is not above 50, but 8 × 8 = 64 is, so the integer square root is 7."
  },
  "memory": {
    "remember": "Binary search the answer:\nthe largest m with m × m ≤ x.",
    "pattern": "Binary search on the answer"
  }
};

export default problem;
