// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H023",
  "number": 23,
  "slug": "first-missing-positive",
  "title": "First Missing Positive",
  "category": "Arrays",
  "definition": "Find the smallest missing positive integer.",
  "example": {
    "input": "[3,4,-1,1]",
    "output": "2"
  },
  "approach": "Put every number in a Set, then count 1, 2, 3… until one is missing.",
  "keyIdea": [
    "Put all numbers in a Set",
    "Check 1, 2, 3… in order",
    "The first one not in the Set is the answer"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "One pass to build the Set and at most n checks.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "before",
        "v": [
          3,
          4,
          -1,
          1
        ]
      },
      {
        "l": "placed",
        "v": [
          1,
          -1,
          3,
          4
        ],
        "ok": [
          0,
          2,
          3
        ],
        "no": [
          1
        ],
        "ix": 1
      }
    ],
    "cap": "Value v belongs at index v − 1. Index 1 is wrong → 2 is missing."
  },
  "better": {
    "name": "Cyclic sort (place n at index n−1)",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int firstMissingPositive(int[] nums) {\n    int n = nums.length;\n    for (int i = 0; i < n; i++) {\n      // keep swapping until nums[i] sits at its home index (or is useless)\n      while (nums[i] > 0 && nums[i] <= n && nums[nums[i] - 1] != nums[i]) {\n        int j = nums[i] - 1;\n        int t = nums[i]; nums[i] = nums[j]; nums[j] = t;\n      }\n    }\n    for (int i = 0; i < n; i++) if (nums[i] != i + 1) return i + 1;\n    return n + 1;\n  }\n}"
  },
  "code": "class Solution {\n  public int firstMissingPositive(int[] nums) {\n    Set<Integer> seen = new HashSet<>();\n    for (int n : nums) seen.add(n);\n    int candidate = 1;\n    while (seen.contains(candidate)) candidate++;\n    return candidate;\n  }\n}",
  "method": "firstMissingPositive",
  "defaultInput": "[3,4,-1,1]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          4,
          -1,
          1
        ]
      ],
      "expected": 2
    },
    {
      "name": "Starts at 1",
      "args": [
        [
          1,
          2,
          0
        ]
      ],
      "expected": 3
    },
    {
      "name": "Missing 1",
      "args": [
        [
          7,
          8,
          9
        ]
      ],
      "expected": 1
    },
    {
      "name": "Duplicates",
      "args": [
        [
          1,
          1,
          1
        ]
      ],
      "expected": 2
    },
    {
      "name": "Single 1",
      "args": [
        [
          1
        ]
      ],
      "expected": 2
    },
    {
      "name": "Negatives",
      "args": [
        [
          -1,
          -2
        ]
      ],
      "expected": 1
    }
  ],
  "challenge": {
    "question": "What is the smallest missing positive number?",
    "input": "[2,3,1,5,6]",
    "options": [
      "2",
      "5",
      "3",
      "4"
    ],
    "answer": 3,
    "explanation": "1, 2 and 3 are present but 4 is not — so 4 is the smallest missing positive."
  },
  "memory": {
    "remember": "The answer is between 1 and n+1 —\ncheck each in a Set.",
    "pattern": "Presence Check (Set)"
  }
};

export default problem;
