// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H051",
  "number": 51,
  "slug": "sieve-of-eratosthenes",
  "title": "Sieve of Eratosthenes",
  "category": "Math & Number Theory",
  "definition": "List all primes up to n.",
  "example": {
    "input": "n = 30",
    "output": "[2,3,5,7,11,13,17,19,23,29]"
  },
  "approach": "Assume everything is prime. Each time you meet a prime, cross out all of its multiples.",
  "keyIdea": [
    "boolean array composite[]",
    "i is not crossed out → prime",
    "Cross out i², i² + i, i² + 2i …"
  ],
  "time": "O(n log log n)",
  "space": "O(n)",
  "complexityWhy": "Very close to linear.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "2–13",
        "v": [
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13
        ],
        "ok": [
          0,
          1,
          3,
          5,
          9,
          11
        ],
        "no": [
          2,
          4,
          6,
          7,
          8,
          10
        ]
      }
    ],
    "cap": "Cross out multiples of 2, 3, … what remains is prime."
  },
  "code": "class Solution {\n  public List<Integer> primesUpTo(int n) {\n    boolean[] composite = new boolean[n + 1];\n    List<Integer> primes = new ArrayList<>();\n    for (int i = 2; i <= n; i++) {\n      if (composite[i]) continue;\n      primes.add(i);                                            // never crossed out -> prime\n      for (long j = (long) i * i; j <= n; j += i) composite[(int) j] = true;   // cross out its multiples\n    }\n    return primes;\n  }\n}",
  "method": "primesUpTo",
  "defaultInput": "30",
  "tests": [
    {
      "name": "Example",
      "args": [
        30
      ],
      "expected": [
        2,
        3,
        5,
        7,
        11,
        13,
        17,
        19,
        23,
        29
      ]
    },
    {
      "name": "Tiny",
      "args": [
        2
      ],
      "expected": [
        2
      ]
    },
    {
      "name": "One",
      "args": [
        1
      ],
      "expected": []
    },
    {
      "name": "Ten",
      "args": [
        10
      ],
      "expected": [
        2,
        3,
        5,
        7
      ]
    },
    {
      "name": "Twenty",
      "args": [
        20
      ],
      "expected": [
        2,
        3,
        5,
        7,
        11,
        13,
        17,
        19
      ]
    },
    {
      "name": "Prime bound",
      "args": [
        13
      ],
      "expected": [
        2,
        3,
        5,
        7,
        11,
        13
      ]
    }
  ],
  "challenge": {
    "question": "How many primes are there up to 50?",
    "input": "50",
    "options": [
      "13",
      "14",
      "15",
      "17"
    ],
    "answer": 2,
    "explanation": "The primes up to 50 are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47 — fifteen of them."
  },
  "memory": {
    "remember": "Cross out the multiples —\nwhat survives is prime.",
    "pattern": "Sieve: cross out multiples"
  }
};

export default problem;
