// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H132",
  "number": 132,
  "slug": "coin-change-minimum-coins",
  "title": "Coin Change — Minimum Coins",
  "category": "Dynamic Programming",
  "definition": "Fewest coins needed to make the amount (or −1).",
  "example": {
    "input": "coins [1,2,5], amount = 11",
    "output": "3  (5 + 5 + 1)"
  },
  "approach": "dp[a] = fewest coins to make amount a. Try each coin as the last coin.",
  "keyIdea": [
    "dp[0] = 0, all others = ∞",
    "For each amount a and each coin c ≤ a",
    "dp[a] = min(dp[a], dp[a − c] + 1)",
    "dp[amount] still ∞ → −1"
  ],
  "time": "O(amount·coins)",
  "space": "O(amount)",
  "complexityWhy": "amount × number of coins.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "amount",
        "v": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11
        ]
      },
      {
        "l": "coins",
        "v": [
          0,
          1,
          1,
          2,
          2,
          1,
          2,
          2,
          3,
          3,
          2,
          3
        ],
        "ok": [
          11
        ]
      }
    ],
    "cap": "dp[11] = 3 coins."
  },
  "code": "class Solution {\n  public int coinChange(int[] coins, int amount) {\n    int[] dp = new int[amount + 1];                         // dp[a]: fewest coins for amount a\n    Arrays.fill(dp, amount + 1);                            // \"infinity\"\n    dp[0] = 0;\n    for (int a = 1; a <= amount; a++) {\n      for (int coin : coins) {\n        if (coin <= a) dp[a] = Math.min(dp[a], dp[a - coin] + 1);\n      }\n    }\n    return dp[amount] > amount ? -1 : dp[amount];\n  }\n}",
  "method": "coinChange",
  "defaultInput": "[1,2,5], 11",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          5
        ],
        11
      ],
      "expected": 3
    },
    {
      "name": "Impossible",
      "args": [
        [
          2
        ],
        3
      ],
      "expected": -1
    },
    {
      "name": "Zero amount",
      "args": [
        [
          1
        ],
        0
      ],
      "expected": 0
    },
    {
      "name": "Large amount",
      "args": [
        [
          186,
          419,
          83,
          408
        ],
        6249
      ],
      "expected": 20
    },
    {
      "name": "Greedy fails",
      "args": [
        [
          1,
          3,
          4
        ],
        6
      ],
      "expected": 2
    },
    {
      "name": "Single coin",
      "args": [
        [
          5
        ],
        5
      ],
      "expected": 1
    }
  ],
  "challenge": {
    "question": "What is the fewest number of coins that make 6 with coins 1, 3 and 4?",
    "input": "[1,3,4], 6",
    "options": [
      "5",
      "2",
      "0",
      "4"
    ],
    "answer": 1,
    "explanation": "Greedy would take 4 + 1 + 1 (3 coins), but 3 + 3 needs only 2 coins."
  },
  "memory": {
    "remember": "Fewest coins for amount a =\n1 + the best answer for a − coin.",
    "pattern": "Bottom-up DP"
  }
};

export default problem;
