// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H089",
  "number": 89,
  "slug": "is-graph-bipartite",
  "title": "Is Graph Bipartite?",
  "category": "Graph",
  "definition": "Can the nodes be split into two groups with every edge going between the groups?",
  "example": {
    "input": "[[1,3],[0,2],[1,3],[0,2]]",
    "output": "true"
  },
  "approach": "Colour a node red, all its neighbours blue, their neighbours red… If a neighbour already has your colour, it fails.",
  "keyIdea": [
    "Colour the start node 0",
    "Give neighbours the opposite colour",
    "Same colour on both ends of an edge → not bipartite"
  ],
  "time": "O(V + E)",
  "space": "O(V)",
  "complexityWhy": "Every edge is checked once — already optimal.",
  "figure": {
    "k": "graph",
    "n": 4,
    "e": [
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        0
      ]
    ],
    "pos": [
      [
        1,
        0
      ],
      [
        9,
        0
      ],
      [
        9,
        6
      ],
      [
        1,
        6
      ]
    ],
    "ok": [
      0,
      2
    ],
    "hi": [
      1,
      3
    ],
    "cap": "Two colours alternate around the square → bipartite."
  },
  "code": "class Solution {\n  public boolean isBipartite(int[][] graph) {\n    int[] color = new int[graph.length];\n    Arrays.fill(color, -1);                              // -1 = not coloured yet\n    for (int start = 0; start < graph.length; start++) { // graph may be disconnected\n      if (color[start] != -1) continue;\n      color[start] = 0;\n      Queue<Integer> queue = new ArrayDeque<>();\n      queue.add(start);\n      while (!queue.isEmpty()) {\n        int node = queue.poll();\n        for (int next : graph[node]) {\n          if (color[next] == -1) { color[next] = 1 - color[node]; queue.add(next); }\n          else if (color[next] == color[node]) return false;   // clash!\n        }\n      }\n    }\n    return true;\n  }\n}",
  "method": "isBipartite",
  "defaultInput": "[[1,3],[0,2],[1,3],[0,2]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            1,
            3
          ],
          [
            0,
            2
          ],
          [
            1,
            3
          ],
          [
            0,
            2
          ]
        ]
      ],
      "expected": true
    },
    {
      "name": "Triangle",
      "args": [
        [
          [
            1,
            2
          ],
          [
            0,
            2
          ],
          [
            0,
            1
          ]
        ]
      ],
      "expected": false
    },
    {
      "name": "Single node",
      "args": [
        [
          []
        ]
      ],
      "expected": true
    },
    {
      "name": "Two components",
      "args": [
        [
          [
            1
          ],
          [
            0
          ],
          [
            3
          ],
          [
            2
          ]
        ]
      ],
      "expected": true
    },
    {
      "name": "Triangle plus a tail",
      "args": [
        [
          [
            1,
            2,
            3
          ],
          [
            0,
            2
          ],
          [
            0,
            1,
            3
          ],
          [
            0,
            2
          ]
        ]
      ],
      "expected": false
    },
    {
      "name": "Odd cycle of five",
      "args": [
        [
          [
            1,
            4
          ],
          [
            0,
            2
          ],
          [
            1,
            3
          ],
          [
            2,
            4
          ],
          [
            3,
            0
          ]
        ]
      ],
      "expected": false
    }
  ],
  "challenge": {
    "question": "Is the graph bipartite (can it be coloured with two colours)?",
    "input": "[[1,2,3],[0,2],[0,1,3],[0,2]]",
    "options": [
      "true",
      "false"
    ],
    "answer": 1,
    "explanation": "Nodes 0, 1 and 2 are all connected to each other — a triangle. A triangle can't be coloured with two colours, so the answer is false."
  },
  "memory": {
    "remember": "Colour a node, give its neighbours the opposite colour —\na clash means 'not bipartite'.",
    "pattern": "Two-colouring with BFS / DFS"
  }
};

export default problem;
