// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H025",
  "number": 25,
  "slug": "longest-palindromic-substring",
  "title": "Longest Palindromic Substring",
  "category": "Strings",
  "definition": "Find the longest substring that reads the same both ways.",
  "example": {
    "input": "\"babad\"",
    "output": "\"bab\" (or \"aba\")"
  },
  "approach": "Every palindrome mirrors around a centre. Try each letter (and each gap between letters) as a centre and grow outwards while both sides match.",
  "keyIdea": [
    "Pick a centre (odd length) or a gap (even length)",
    "Expand left and right while the letters match",
    "Remember the longest one"
  ],
  "time": "O(n²)",
  "space": "O(1)",
  "complexityWhy": "n centres, each expands at most n steps.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "b",
          "a",
          "b",
          "a",
          "d"
        ],
        "ok": [
          0,
          1,
          2
        ],
        "p": {
          "1": "centre"
        },
        "br": [
          [
            0,
            2,
            "bab"
          ]
        ]
      }
    ],
    "cap": "Grow outwards from the centre while both sides match."
  },
  "code": "class Solution {\n  public String longestPalindrome(String s) {\n    int start = 0, maxLen = 0;\n    for (int i = 0; i < s.length(); i++) {\n      int len = Math.max(expand(s, i, i), expand(s, i, i + 1));   // odd, even centre\n      if (len > maxLen) { maxLen = len; start = i - (len - 1) / 2; }\n    }\n    return s.substring(start, start + maxLen);\n  }\n  private int expand(String s, int l, int r) {\n    while (l >= 0 && r < s.length() && s.charAt(l) == s.charAt(r)) { l--; r++; }\n    return r - l - 1;                                   // palindrome length\n  }\n}",
  "method": "longestPalindrome",
  "defaultInput": "\"babad\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "babad"
      ],
      "expected": "bab"
    },
    {
      "name": "Single",
      "args": [
        "a"
      ],
      "expected": "a"
    },
    {
      "name": "Two same",
      "args": [
        "bb"
      ],
      "expected": "bb"
    },
    {
      "name": "Even palindrome",
      "args": [
        "cbbd"
      ],
      "expected": "bb"
    },
    {
      "name": "Whole string",
      "args": [
        "racecar"
      ],
      "expected": "racecar"
    },
    {
      "name": "No repeats",
      "args": [
        "abc"
      ],
      "expected": "a"
    },
    {
      "name": "Longer",
      "args": [
        "forgeeksskeegfor"
      ],
      "expected": "geeksskeeg"
    }
  ],
  "challenge": {
    "question": "What is the longest palindromic substring?",
    "input": "\"abacdfgdcaba\"",
    "options": [
      "\"ba\"",
      "\"ab\"",
      "\"abaa\"",
      "\"aba\""
    ],
    "answer": 3,
    "explanation": "\"aba\" is the longest palindrome here (length 3); the first one found is returned."
  },
  "memory": {
    "remember": "Every palindrome has a centre —\nexpand outward from each one.",
    "pattern": "Expand around every centre"
  }
};

export default problem;
