// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H083",
  "number": 83,
  "slug": "serialize-deserialize-binary-tree",
  "title": "Serialize & Deserialize Binary Tree",
  "category": "Trees",
  "definition": "Turn a tree into a string and rebuild it.",
  "example": {
    "input": "[1,2,3,null,null,4,5]",
    "output": "string → same tree"
  },
  "approach": "Write the tree in preorder and mark missing children with '#'. Reading it back in the same order rebuilds the tree.",
  "keyIdea": [
    "serialize: node value, then left, then right; null → #",
    "deserialize: read one token",
    "'#' → null, otherwise make a node and read left, then right"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "Each node is handled once.",
  "figure": [
    {
      "k": "tree",
      "v": [
        1,
        2,
        3,
        null,
        null,
        4,
        5
      ]
    },
    {
      "k": "txt",
      "lines": [
        "preorder: 1,2,#,#,3,4,#,#,5,#,#"
      ]
    }
  ],
  "code": "class Codec {\n  public String serialize(TreeNode root) {\n    StringBuilder out = new StringBuilder();\n    write(root, out);\n    return out.toString();\n  }\n  private void write(TreeNode node, StringBuilder out) {\n    if (node == null) { out.append(\"#,\"); return; }\n    out.append(node.val).append(',');\n    write(node.left, out);\n    write(node.right, out);\n  }\n  private String[] parts;\n  private int i;\n  public TreeNode deserialize(String data) {\n    parts = data.split(\",\");\n    i = 0;\n    return build();\n  }\n  private TreeNode build() {\n    String p = parts[i++];\n    if (p.equals(\"#\")) return null;\n    TreeNode node = new TreeNode(Integer.parseInt(p));\n    node.left = build();\n    node.right = build();\n    return node;\n  }\n}",
  "method": "Codec",
  "defaultInput": "[], [[\"serialize\",[1,2,3,null,null,4,5]]]",
  "tests": [
    {
      "name": "Example: serialize",
      "args": [
        [],
        [
          [
            "serialize",
            [
              1,
              2,
              3,
              null,
              null,
              4,
              5
            ]
          ]
        ]
      ],
      "expected": [
        "1,2,#,#,3,4,#,#,5,#,#,"
      ]
    },
    {
      "name": "Example: deserialize",
      "args": [
        [],
        [
          [
            "deserialize",
            "1,2,#,#,3,4,#,#,5,#,#,"
          ]
        ]
      ],
      "expected": [
        [
          1,
          2,
          3,
          null,
          null,
          4,
          5
        ]
      ]
    },
    {
      "name": "Empty tree",
      "args": [
        [],
        [
          [
            "serialize",
            []
          ],
          [
            "deserialize",
            "#,"
          ]
        ]
      ],
      "expected": [
        "#,",
        null
      ]
    },
    {
      "name": "Single node",
      "args": [
        [],
        [
          [
            "serialize",
            [
              7
            ]
          ],
          [
            "deserialize",
            "7,#,#,"
          ]
        ]
      ],
      "expected": [
        "7,#,#,",
        [
          7
        ]
      ]
    },
    {
      "name": "Left chain",
      "args": [
        [],
        [
          [
            "serialize",
            [
              3,
              2,
              null,
              1
            ]
          ]
        ]
      ],
      "expected": [
        "3,2,1,#,#,#,#,"
      ]
    },
    {
      "name": "Right chain",
      "args": [
        [],
        [
          [
            "serialize",
            [
              1,
              null,
              2,
              null,
              3
            ]
          ]
        ]
      ],
      "expected": [
        "1,#,2,#,3,#,#,"
      ]
    }
  ],
  "challenge": {
    "question": "What does serialize return for the tree [1,2,3]?",
    "input": "[], [[\"serialize\",[1,2,3]]]",
    "options": [
      "\"1,2,#,#,3,#,#,\"",
      "\"1,2,3,#,#,#,#,\"",
      "\"1,#,2,#,3,#,#,\"",
      "\"#,1,#,2,#,3,#,\""
    ],
    "answer": 0,
    "explanation": "Preorder with '#' for a missing child: 1, then the whole left subtree (2,#,#), then the whole right subtree (3,#,#)."
  },
  "memory": {
    "remember": "Preorder with '#' for empty children —\nthe string rebuilds the tree exactly.",
    "pattern": "Preorder with '#' markers"
  }
};

export default problem;
