// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H077",
  "number": 77,
  "slug": "lowest-common-ancestor",
  "title": "Lowest Common Ancestor",
  "category": "Trees",
  "definition": "Find the lowest node that has both p and q below it (a node counts as below itself).",
  "example": {
    "input": "tree [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1",
    "output": "3"
  },
  "approach": "Search both sides. If p and q are found on different sides, this node is the answer; otherwise the answer is on the side that found something.",
  "keyIdea": [
    "null, p or q → return the node",
    "Search left and right",
    "Both sides found something → this node",
    "Otherwise return the non-null side"
  ],
  "time": "O(n)",
  "space": "O(h)",
  "complexityWhy": "Each node is visited once.",
  "figure": {
    "k": "tree",
    "v": [
      3,
      5,
      1,
      6,
      2,
      0,
      8,
      null,
      null,
      7,
      4
    ],
    "hi": [
      5,
      1
    ],
    "ok": [
      3
    ],
    "cap": "5 and 1 are on different sides of 3, so 3 is their lowest common ancestor."
  },
  "code": "class Solution {\n  public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n    if (root == null || root == p || root == q) return root;\n    TreeNode left = lowestCommonAncestor(root.left, p, q);\n    TreeNode right = lowestCommonAncestor(root.right, p, q);\n    if (left != null && right != null) return root;   // p and q are on different sides\n    return (left != null) ? left : right;             // both are on the same side\n  }\n}",
  "method": "lowestCommonAncestor",
  "resultIndex": 0,
  "defaultInput": "[3,5,1,6,2,0,8,null,null,7,4], 5, 1",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          5,
          1,
          6,
          2,
          0,
          8,
          null,
          null,
          7,
          4
        ],
        5,
        1
      ],
      "expected": 3
    },
    {
      "name": "One is the ancestor",
      "args": [
        [
          3,
          5,
          1,
          6,
          2,
          0,
          8,
          null,
          null,
          7,
          4
        ],
        5,
        4
      ],
      "expected": 5
    },
    {
      "name": "Two nodes",
      "args": [
        [
          1,
          2
        ],
        1,
        2
      ],
      "expected": 1
    },
    {
      "name": "Same node twice",
      "args": [
        [
          3,
          5,
          1
        ],
        5,
        5
      ],
      "expected": 5
    },
    {
      "name": "Deep on one side",
      "args": [
        [
          3,
          5,
          1,
          6,
          2,
          0,
          8,
          null,
          null,
          7,
          4
        ],
        6,
        4
      ],
      "expected": 5
    },
    {
      "name": "Different sides",
      "args": [
        [
          3,
          5,
          1,
          6,
          2,
          0,
          8,
          null,
          null,
          7,
          4
        ],
        0,
        8
      ],
      "expected": 1
    }
  ],
  "challenge": {
    "question": "What is the value of the lowest common ancestor of the two nodes?",
    "input": "[6,2,8,0,4,7,9,null,null,3,5], 3, 5",
    "options": [
      "4",
      "5",
      "6",
      "3"
    ],
    "answer": 0,
    "explanation": "3 and 5 hang under 4 on opposite sides, so 4 is the lowest node that has both below it."
  },
  "memory": {
    "remember": "If p and q are on different sides,\nthis node is the answer.",
    "pattern": "One recursion"
  }
};

export default problem;
