// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H115",
  "number": 115,
  "slug": "evaluate-rpn",
  "title": "Evaluate Reverse Polish Notation (RPN)",
  "category": "Stack",
  "definition": "Calculate a postfix expression like 2 1 + 3 * (each operator comes after its numbers).",
  "example": {
    "input": "[\"2\",\"1\",\"+\",\"3\",\"*\"]",
    "output": "9"
  },
  "approach": "Read left to right. Numbers go on the stack. An operator takes the top two numbers, computes, and pushes the result.",
  "keyIdea": [
    "Push numbers",
    "On an operator pop b, then a",
    "Push a op b"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "Each token is handled once.",
  "figure": {
    "k": "stack",
    "s": [
      {
        "l": "2, 1",
        "v": [
          2,
          1
        ]
      },
      {
        "l": "+",
        "v": [
          3
        ]
      },
      {
        "l": "3",
        "v": [
          3,
          3
        ]
      },
      {
        "l": "*",
        "v": [
          9
        ]
      }
    ],
    "cap": "(2 + 1) × 3 = 9"
  },
  "code": "class Solution {\n  public int evalRPN(String[] tokens) {\n    Deque<Integer> stack = new ArrayDeque<>();\n    for (String token : tokens) {\n      if (token.equals(\"+\") || token.equals(\"-\") || token.equals(\"*\") || token.equals(\"/\")) {\n        int b = stack.pop();                 // second operand comes off first\n        int a = stack.pop();\n        if (token.equals(\"+\")) stack.push(a + b);\n        else if (token.equals(\"-\")) stack.push(a - b);\n        else if (token.equals(\"*\")) stack.push(a * b);\n        else stack.push(a / b);              // int division truncates toward zero\n      } else {\n        stack.push(Integer.parseInt(token));\n      }\n    }\n    return stack.pop();\n  }\n}",
  "method": "evalRPN",
  "defaultInput": "[\"2\",\"1\",\"+\",\"3\",\"*\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          "2",
          "1",
          "+",
          "3",
          "*"
        ]
      ],
      "expected": 9
    },
    {
      "name": "Division",
      "args": [
        [
          "4",
          "13",
          "5",
          "/",
          "+"
        ]
      ],
      "expected": 6
    },
    {
      "name": "Longer expression",
      "args": [
        [
          "10",
          "6",
          "9",
          "3",
          "+",
          "-11",
          "*",
          "/",
          "*",
          "17",
          "+",
          "5",
          "+"
        ]
      ],
      "expected": 22
    },
    {
      "name": "Single number",
      "args": [
        [
          "42"
        ]
      ],
      "expected": 42
    },
    {
      "name": "Negative number",
      "args": [
        [
          "3",
          "-4",
          "+"
        ]
      ],
      "expected": -1
    },
    {
      "name": "Division truncates toward zero",
      "args": [
        [
          "7",
          "-2",
          "/"
        ]
      ],
      "expected": -3
    }
  ],
  "challenge": {
    "question": "What does the expression evaluate to?",
    "input": "[\"5\",\"1\",\"2\",\"+\",\"4\",\"*\",\"+\",\"3\",\"-\"]",
    "options": [
      "28",
      "12",
      "15",
      "14"
    ],
    "answer": 3,
    "explanation": "1 2 + → 3, then 3 4 * → 12, then 5 12 + → 17, then 17 3 − → 14."
  },
  "memory": {
    "remember": "Numbers go on the stack;\nan operator pops two and pushes the result.",
    "pattern": "Stack of Numbers"
  }
};

export default problem;
