// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H009",
  "number": 9,
  "slug": "trapping-rain-water",
  "title": "Trapping Rain Water",
  "category": "Arrays",
  "definition": "Compute how much rain water the bars can trap.",
  "example": {
    "input": "[0,1,0,2,1,0,1,3,2,1,2,1]",
    "output": "6"
  },
  "approach": "Water above a bar is limited by the shorter of the tallest walls on its left and right.",
  "keyIdea": [
    "For each bar find the tallest bar to its left",
    "And the tallest bar to its right",
    "Water = min(leftMax, rightMax) − height"
  ],
  "time": "O(n²)",
  "space": "O(1)",
  "complexityWhy": "Each bar rescans both sides.",
  "figure": {
    "k": "bars",
    "r": [
      {
        "v": [
          0,
          1,
          0,
          2,
          1,
          0,
          1,
          3,
          2,
          1,
          2,
          1
        ],
        "w": [
          0,
          0,
          1,
          0,
          1,
          2,
          1,
          0,
          0,
          1,
          0,
          0
        ]
      }
    ],
    "cap": "Blue = trapped water. Total 6 units."
  },
  "better": {
    "name": "Two pointers with running maxes",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int trap(int[] height) {\n    int left = 0, right = height.length - 1;\n    int leftMax = 0, rightMax = 0, water = 0;\n    while (left < right) {\n      if (height[left] < height[right]) {\n        leftMax = Math.max(leftMax, height[left]);\n        water += leftMax - height[left++];\n      } else {\n        rightMax = Math.max(rightMax, height[right]);\n        water += rightMax - height[right--];\n      }\n    }\n    return water;\n  }\n}"
  },
  "code": "class Solution {\n  public int trap(int[] height) {\n    int water = 0;\n    for (int i = 0; i < height.length; i++) {\n      int leftMax = 0, rightMax = 0;\n      for (int l = 0; l <= i; l++) leftMax = Math.max(leftMax, height[l]);\n      for (int r = i; r < height.length; r++) rightMax = Math.max(rightMax, height[r]);\n      water += Math.min(leftMax, rightMax) - height[i];\n    }\n    return water;\n  }\n}",
  "method": "trap",
  "defaultInput": "[0,1,0,2,1,0,1,3,2,1,2,1]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          0,
          1,
          0,
          2,
          1,
          0,
          1,
          3,
          2,
          1,
          2,
          1
        ]
      ],
      "expected": 6
    },
    {
      "name": "No water",
      "args": [
        [
          1,
          2,
          3,
          4
        ]
      ],
      "expected": 0
    },
    {
      "name": "Valley",
      "args": [
        [
          3,
          0,
          3
        ]
      ],
      "expected": 3
    },
    {
      "name": "Single bar",
      "args": [
        [
          5
        ]
      ],
      "expected": 0
    },
    {
      "name": "Flat",
      "args": [
        [
          2,
          2,
          2
        ]
      ],
      "expected": 0
    },
    {
      "name": "Down then up",
      "args": [
        [
          4,
          2,
          0,
          3,
          2,
          5
        ]
      ],
      "expected": 9
    }
  ],
  "challenge": {
    "question": "How much rain water is trapped?",
    "input": "[3,0,2,0,4]",
    "options": [
      "3",
      "14",
      "7",
      "10"
    ],
    "answer": 2,
    "explanation": "Each cell holds min(tallest on its left, tallest on its right) − its own height: 3 + 1 + 3 = 7."
  },
  "memory": {
    "remember": "Water above a bar =\nmin(left max, right max) − height.",
    "pattern": "Per-bar Water Level"
  }
};

export default problem;
