// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H112",
  "number": 112,
  "slug": "lru-cache",
  "title": "LRU Cache (Design)",
  "category": "Linked List",
  "definition": "get and put with least-recently-used eviction when the cache is full.",
  "example": {
    "input": "capacity 2: put(1,1), put(2,2), get(1), put(3,3), get(2)",
    "output": "1, −1"
  },
  "approach": "Keep a list ordered from least to most recently used. Every access moves the item to the end.",
  "keyIdea": [
    "Array of {key, value}, newest at the end",
    "get/put: find the item, move it to the end",
    "When full, remove the first item"
  ],
  "time": "O(n) per call",
  "space": "O(capacity)",
  "complexityWhy": "Searching and removing in a list is linear.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "old->new",
        "v": [
          "1",
          "2"
        ]
      },
      {
        "l": "get(1)",
        "v": [
          "2",
          "1"
        ],
        "ok": [
          1
        ]
      },
      {
        "l": "put(3)",
        "v": [
          "1",
          "3"
        ],
        "ok": [
          1
        ],
        "no": [
          0
        ]
      }
    ],
    "cap": "Evict the front (least recent). Interviews may ask for HashMap + doubly linked list."
  },
  "better": {
    "name": "LinkedHashMap in access order -> O(1)",
    "time": "O(1) per call",
    "space": "O(capacity)",
    "code": "class LRUCache extends LinkedHashMap<Integer, Integer> {\n  private final int capacity;\n  public LRUCache(int capacity) {\n    super(capacity, 0.75f, true);                          // true = keep access order\n    this.capacity = capacity;\n  }\n  public int get(int key) { return super.getOrDefault(key, -1); }\n  @Override\n  protected boolean removeEldestEntry(Map.Entry<Integer, Integer> eldest) {\n    return size() > capacity;                              // evict the least recently used\n  }\n}"
  },
  "code": "class LRUCache {\n  private final int capacity;\n  private final List<int[]> items = new ArrayList<>();     // oldest first, newest last\n  public LRUCache(int capacity) { this.capacity = capacity; }\n  public int get(int key) {\n    for (int i = 0; i < items.size(); i++) {\n      if (items.get(i)[0] == key) {\n        int[] item = items.remove(i);\n        items.add(item);                                   // now the most recent\n        return item[1];\n      }\n    }\n    return -1;\n  }\n  public void put(int key, int value) {\n    for (int i = 0; i < items.size(); i++) {\n      if (items.get(i)[0] == key) { items.remove(i); break; }\n    }\n    if (items.size() == capacity) items.remove(0);         // evict oldest\n    items.add(new int[]{key, value});\n  }\n}",
  "method": "LRUCache",
  "defaultInput": "[2], [[\"put\",1,1],[\"put\",2,2],[\"get\",1],[\"put\",3,3],[\"get\",2]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          2
        ],
        [
          [
            "put",
            1,
            1
          ],
          [
            "put",
            2,
            2
          ],
          [
            "get",
            1
          ],
          [
            "put",
            3,
            3
          ],
          [
            "get",
            2
          ]
        ]
      ],
      "expected": [
        null,
        null,
        1,
        null,
        -1
      ]
    },
    {
      "name": "Capacity one",
      "args": [
        [
          1
        ],
        [
          [
            "put",
            1,
            1
          ],
          [
            "put",
            2,
            2
          ],
          [
            "get",
            1
          ],
          [
            "get",
            2
          ]
        ]
      ],
      "expected": [
        null,
        null,
        -1,
        2
      ]
    },
    {
      "name": "Updating a key",
      "args": [
        [
          2
        ],
        [
          [
            "put",
            1,
            1
          ],
          [
            "put",
            1,
            10
          ],
          [
            "get",
            1
          ]
        ]
      ],
      "expected": [
        null,
        null,
        10
      ]
    },
    {
      "name": "Missing key",
      "args": [
        [
          2
        ],
        [
          [
            "get",
            5
          ]
        ]
      ],
      "expected": [
        -1
      ]
    },
    {
      "name": "Reading refreshes a key",
      "args": [
        [
          2
        ],
        [
          [
            "put",
            1,
            1
          ],
          [
            "put",
            2,
            2
          ],
          [
            "get",
            1
          ],
          [
            "put",
            3,
            3
          ],
          [
            "get",
            1
          ],
          [
            "get",
            2
          ],
          [
            "get",
            3
          ]
        ]
      ],
      "expected": [
        null,
        null,
        1,
        null,
        1,
        -1,
        3
      ]
    },
    {
      "name": "Capacity three",
      "args": [
        [
          3
        ],
        [
          [
            "put",
            1,
            1
          ],
          [
            "put",
            2,
            2
          ],
          [
            "put",
            3,
            3
          ],
          [
            "put",
            4,
            4
          ],
          [
            "get",
            1
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        null,
        -1
      ]
    }
  ],
  "challenge": {
    "question": "After put(1,1), put(2,2), get(1) and put(3,3) with capacity 2 — what does get(2) return?",
    "input": "[2], [[\"put\",1,1],[\"put\",2,2],[\"get\",1],[\"put\",3,3],[\"get\",2]]",
    "options": [
      "0",
      "-2",
      "1",
      "-1"
    ],
    "answer": 3,
    "explanation": "get(1) made key 1 the most recently used. Adding key 3 then evicted the least recently used key, 2, so get(2) returns −1."
  },
  "memory": {
    "remember": "The least recently used goes first:\nevery get() or put() makes a key 'newest'.",
    "pattern": "LinkedHashMap in access order -> O(1)"
  }
};

export default problem;
