// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H119",
  "number": 119,
  "slug": "largest-rectangle-in-histogram",
  "title": "Largest Rectangle in Histogram",
  "category": "Stack",
  "definition": "Largest rectangular area inside a histogram.",
  "example": {
    "input": "[2,1,5,6,2,3]",
    "output": "10"
  },
  "approach": "For every bar, stretch left and right as long as the neighbours are at least as tall. Area = height × width.",
  "keyIdea": [
    "For each bar expand left and right",
    "Width = right − left + 1",
    "Area = height × width; keep the max"
  ],
  "time": "O(n²)",
  "space": "O(1)",
  "complexityWhy": "Each bar can expand across the whole array.",
  "figure": {
    "k": "bars",
    "r": [
      {
        "v": [
          2,
          1,
          5,
          6,
          2,
          3
        ],
        "ok": [
          2,
          3
        ],
        "hi": []
      }
    ],
    "h": 56,
    "cap": "Bars 5 and 6 → height 5 × width 2 = 10."
  },
  "better": {
    "name": "Monotonic stack (increasing heights)",
    "time": "O(n)",
    "space": "O(n)",
    "code": "class Solution {\n  public int largestRectangleArea(int[] heights) {\n    Deque<Integer> stack = new ArrayDeque<>();         // indices, heights increasing\n    int best = 0;\n    for (int i = 0; i <= heights.length; i++) {\n      int h = (i == heights.length) ? 0 : heights[i];  // 0 flushes the stack at the end\n      while (!stack.isEmpty() && heights[stack.peek()] > h) {\n        int height = heights[stack.pop()];\n        int width = stack.isEmpty() ? i : i - stack.peek() - 1;\n        best = Math.max(best, height * width);\n      }\n      stack.push(i);\n    }\n    return best;\n  }\n}"
  },
  "code": "class Solution {\n  public int largestRectangleArea(int[] heights) {\n    int best = 0;\n    for (int i = 0; i < heights.length; i++) {\n      int left = i, right = i;\n      while (left > 0 && heights[left - 1] >= heights[i]) left--;\n      while (right < heights.length - 1 && heights[right + 1] >= heights[i]) right++;\n      best = Math.max(best, heights[i] * (right - left + 1));\n    }\n    return best;\n  }\n}",
  "method": "largestRectangleArea",
  "defaultInput": "[2,1,5,6,2,3]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          2,
          1,
          5,
          6,
          2,
          3
        ]
      ],
      "expected": 10
    },
    {
      "name": "Two bars",
      "args": [
        [
          2,
          4
        ]
      ],
      "expected": 4
    },
    {
      "name": "Single bar",
      "args": [
        [
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Empty",
      "args": [
        []
      ],
      "expected": 0
    },
    {
      "name": "Classic",
      "args": [
        [
          6,
          2,
          5,
          4,
          5,
          1,
          6
        ]
      ],
      "expected": 12
    },
    {
      "name": "Flat",
      "args": [
        [
          3,
          3,
          3
        ]
      ],
      "expected": 9
    }
  ],
  "challenge": {
    "question": "What is the area of the largest rectangle?",
    "input": "[2,1,2]",
    "options": [
      "1",
      "4",
      "5",
      "3"
    ],
    "answer": 3,
    "explanation": "The shortest bar (1) can stretch across all three bars: 1 × 3 = 3, which beats any single bar of height 2."
  },
  "memory": {
    "remember": "For each bar: how far can it stretch left and right\nbefore a shorter bar blocks it?",
    "pattern": "Monotonic stack (increasing heights)"
  }
};

export default problem;
