// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H095",
  "number": 95,
  "slug": "word-ladder",
  "title": "Word Ladder (Length)",
  "category": "Graph",
  "definition": "Shortest transformation from beginWord to endWord changing one letter at a time (every step must be in the word list).",
  "example": {
    "input": "hit → cog, list [hot,dot,dog,lot,log,cog]",
    "output": "5"
  },
  "approach": "BFS from the begin word. Change each letter to a–z and see whether the new word is in the list. Removing a word from the set marks it visited.",
  "keyIdea": [
    "Put the word list in a set",
    "Queue starts with beginWord (steps = 1)",
    "Try all 26 letters at each position",
    "Found in the set → remove it and enqueue",
    "Reached endWord → return steps"
  ],
  "time": "O(N·L²·26)",
  "space": "O(N·L)",
  "complexityWhy": "BFS gives the shortest number of steps.",
  "figure": {
    "k": "graph",
    "n": 5,
    "e": [
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        4
      ]
    ],
    "pos": [
      [
        0,
        3
      ],
      [
        2.5,
        3
      ],
      [
        5,
        3
      ],
      [
        7.5,
        3
      ],
      [
        10,
        3
      ]
    ],
    "lab": [
      "hit",
      "hot",
      "dot",
      "dog",
      "cog"
    ],
    "ok": [
      0,
      1,
      2,
      3,
      4
    ],
    "cap": "hit → hot → dot → dog → cog = 5 words."
  },
  "code": "class Solution {\n  public int ladderLength(String beginWord, String endWord, List<String> wordList) {\n    Set<String> words = new HashSet<>(wordList);\n    if (!words.contains(endWord)) return 0;\n    Queue<String> queue = new ArrayDeque<>();\n    queue.add(beginWord);\n    int steps = 1;\n    while (!queue.isEmpty()) {\n      for (int size = queue.size(); size > 0; size--) {\n        String word = queue.poll();\n        if (word.equals(endWord)) return steps;\n        char[] chars = word.toCharArray();\n        for (int i = 0; i < chars.length; i++) {\n          char original = chars[i];\n          for (char c = 'a'; c <= 'z'; c++) {              // try a-z at position i\n            chars[i] = c;\n            String candidate = new String(chars);\n            if (words.remove(candidate)) queue.add(candidate);   // remove() = mark as visited\n          }\n          chars[i] = original;\n        }\n      }\n      steps++;\n    }\n    return 0;\n  }\n}",
  "method": "ladderLength",
  "defaultInput": "\"hit\", \"cog\", [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        "hit",
        "cog",
        [
          "hot",
          "dot",
          "dog",
          "lot",
          "log",
          "cog"
        ]
      ],
      "expected": 5
    },
    {
      "name": "No path",
      "args": [
        "hit",
        "cog",
        [
          "hot",
          "dot",
          "dog",
          "lot",
          "log"
        ]
      ],
      "expected": 0
    },
    {
      "name": "One step",
      "args": [
        "a",
        "c",
        [
          "a",
          "b",
          "c"
        ]
      ],
      "expected": 2
    },
    {
      "name": "Another example",
      "args": [
        "red",
        "tax",
        [
          "ted",
          "tex",
          "red",
          "tax",
          "tad",
          "den",
          "rex",
          "pee"
        ]
      ],
      "expected": 4
    },
    {
      "name": "Target not reachable",
      "args": [
        "hot",
        "dog",
        [
          "hot",
          "dog"
        ]
      ],
      "expected": 0
    },
    {
      "name": "Two words",
      "args": [
        "cat",
        "cot",
        [
          "cot"
        ]
      ],
      "expected": 2
    }
  ],
  "challenge": {
    "question": "How many words are in the shortest transformation sequence?",
    "input": "\"red\", \"tax\", [\"ted\",\"tex\",\"red\",\"tax\",\"tad\",\"den\",\"rex\",\"pee\"]",
    "options": [
      "2",
      "4",
      "6",
      "3"
    ],
    "answer": 1,
    "explanation": "red → ted → tad → tax: four words, changing exactly one letter at each step."
  },
  "memory": {
    "remember": "Every word is a node;\nBFS finds the fewest one-letter changes.",
    "pattern": "BFS generating neighbours (a–z per position)"
  }
};

export default problem;
