// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H147",
  "number": 147,
  "slug": "subsets",
  "title": "Subsets",
  "category": "Backtracking",
  "definition": "Return every possible subset, including the empty one.",
  "example": {
    "input": "[1,2,3]",
    "output": "[],[1],[1,2],[1,2,3],[1,3],[2],[2,3],[3]"
  },
  "approach": "For each number decide: take it or leave it. Every path you can walk is one subset.",
  "keyIdea": [
    "Every path is a valid subset — save it",
    "Choose a number",
    "Explore further numbers",
    "Un-choose (pop) and try the next"
  ],
  "time": "O(n·2ⁿ)",
  "space": "O(n)",
  "complexityWhy": "2ⁿ subsets, each copied in O(n).",
  "figure": {
    "k": "tree",
    "v": [
      "[]",
      "[1]",
      "[2]",
      "[1,2]",
      "[1,3]",
      "[2,3]",
      "[3]"
    ],
    "ok": [
      "[1,2]"
    ],
    "cap": "Each branch adds one more number."
  },
  "code": "class Solution {\n  public List<List<Integer>> subsets(int[] nums) {\n    List<List<Integer>> result = new ArrayList<>();\n    backtrack(nums, 0, new ArrayList<>(), result);\n    return result;\n  }\n  private void backtrack(int[] nums, int start, List<Integer> path, List<List<Integer>> result) {\n    result.add(new ArrayList<>(path));          // save a COPY of the current subset\n    for (int i = start; i < nums.length; i++) {\n      path.add(nums[i]);                        // choose\n      backtrack(nums, i + 1, path, result);     // explore\n      path.remove(path.size() - 1);             // un-choose\n    }\n  }\n}",
  "method": "subsets",
  "unordered": true,
  "defaultInput": "[1,2,3]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3
        ]
      ],
      "expected": [
        [],
        [
          1
        ],
        [
          1,
          2
        ],
        [
          1,
          2,
          3
        ],
        [
          1,
          3
        ],
        [
          2
        ],
        [
          2,
          3
        ],
        [
          3
        ]
      ]
    },
    {
      "name": "Empty input",
      "args": [
        []
      ],
      "expected": [
        []
      ]
    },
    {
      "name": "Single number",
      "args": [
        [
          1
        ]
      ],
      "expected": [
        [],
        [
          1
        ]
      ]
    },
    {
      "name": "Two numbers",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": [
        [],
        [
          1
        ],
        [
          1,
          2
        ],
        [
          2
        ]
      ]
    },
    {
      "name": "Zero",
      "args": [
        [
          0
        ]
      ],
      "expected": [
        [],
        [
          0
        ]
      ]
    },
    {
      "name": "Unsorted",
      "args": [
        [
          3,
          1
        ]
      ],
      "expected": [
        [],
        [
          3
        ],
        [
          3,
          1
        ],
        [
          1
        ]
      ]
    }
  ],
  "challenge": {
    "question": "How many subsets does [4,5,6,7] have (including the empty one)?",
    "input": "[4,5,6,7]",
    "options": [
      "15",
      "14",
      "16",
      "17"
    ],
    "answer": 2,
    "explanation": "Each of the 4 numbers is either in or out: 2 × 2 × 2 × 2 = 16 subsets."
  },
  "memory": {
    "remember": "For each number: in or out —\nrecurse on both choices.",
    "pattern": "Include / Exclude Recursion"
  }
};

export default problem;
