// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H150",
  "number": 150,
  "slug": "generate-parentheses",
  "title": "Generate Parentheses",
  "category": "Backtracking",
  "definition": "All valid strings with n pairs of parentheses.",
  "example": {
    "input": "n = 3",
    "output": "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]"
  },
  "approach": "Build the string one bracket at a time. Add '(' while some are left, and add ')' only if there is an unmatched '('.",
  "keyIdea": [
    "open < n → we can add '('",
    "close < open → we can add ')'",
    "Length 2n → save the string"
  ],
  "time": "O(4ⁿ/√n)",
  "space": "O(n)",
  "complexityWhy": "Only valid strings are ever built.",
  "figure": {
    "k": "tree",
    "v": [
      "(",
      "((",
      "()",
      "(((",
      "(()",
      "()("
    ],
    "ok": [
      "(()"
    ],
    "cap": "Never close more than you opened; never open more than n."
  },
  "code": "class Solution {\n  public List<String> generateParenthesis(int n) {\n    List<String> result = new ArrayList<>();\n    build(\"\", 0, 0, n, result);\n    return result;\n  }\n  private void build(String current, int open, int close, int n, List<String> result) {\n    if (current.length() == 2 * n) { result.add(current); return; }\n    if (open < n) build(current + \"(\", open + 1, close, n, result);        // can still open\n    if (close < open) build(current + \")\", open, close + 1, n, result);    // close only if something is open\n  }\n}",
  "method": "generateParenthesis",
  "unordered": true,
  "defaultInput": "3",
  "tests": [
    {
      "name": "Example",
      "args": [
        3
      ],
      "expected": [
        "((()))",
        "(()())",
        "(())()",
        "()(())",
        "()()()"
      ]
    },
    {
      "name": "One pair",
      "args": [
        1
      ],
      "expected": [
        "()"
      ]
    },
    {
      "name": "Two pairs",
      "args": [
        2
      ],
      "expected": [
        "(())",
        "()()"
      ]
    },
    {
      "name": "Zero pairs",
      "args": [
        0
      ],
      "expected": [
        ""
      ]
    },
    {
      "name": "Four pairs",
      "args": [
        4
      ],
      "expected": [
        "(((())))",
        "((()()))",
        "((())())",
        "((()))()",
        "(()(()))",
        "(()()())",
        "(()())()",
        "(())(())",
        "(())()()",
        "()((()))",
        "()(()())",
        "()(())()",
        "()()(())",
        "()()()()"
      ]
    },
    {
      "name": "Five pairs",
      "args": [
        5
      ],
      "expected": [
        "((((()))))",
        "(((()())))",
        "(((())()))",
        "(((()))())",
        "(((())))()",
        "((()(())))",
        "((()()()))",
        "((()())())",
        "((()()))()",
        "((())(()))",
        "((())()())",
        "((())())()",
        "((()))(())",
        "((()))()()",
        "(()((())))",
        "(()(()()))",
        "(()(())())",
        "(()(()))()",
        "(()()(()))",
        "(()()()())",
        "(()()())()",
        "(()())(())",
        "(()())()()",
        "(())((()))",
        "(())(()())",
        "(())(())()",
        "(())()(())",
        "(())()()()",
        "()(((())))",
        "()((()()))",
        "()((())())",
        "()((()))()",
        "()(()(()))",
        "()(()()())",
        "()(()())()",
        "()(())(())",
        "()(())()()",
        "()()((()))",
        "()()(()())",
        "()()(())()",
        "()()()(())",
        "()()()()()"
      ]
    }
  ],
  "challenge": {
    "question": "How many valid strings can be made with 4 pairs of parentheses?",
    "input": "4",
    "options": [
      "15",
      "13",
      "14",
      "17"
    ],
    "answer": 2,
    "explanation": "The number of valid arrangements of n pairs is the n-th Catalan number: for 4 pairs it is 14."
  },
  "memory": {
    "remember": "Add '(' while you still have some;\nadd ')' only when it closes an open one.",
    "pattern": "Backtracking with open / close counts"
  }
};

export default problem;
