// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H113",
  "number": 113,
  "slug": "valid-parentheses",
  "title": "Valid Parentheses",
  "category": "Stack",
  "definition": "Check that brackets are balanced and properly nested.",
  "example": {
    "input": "\"{[()]}\"",
    "output": "true"
  },
  "approach": "Push every opening bracket on a stack. A closing bracket must match the one on top.",
  "keyIdea": [
    "Opening bracket → push",
    "Closing bracket → pop and check that it matches",
    "At the end the stack must be empty"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "One pass.",
  "figure": {
    "k": "stack",
    "s": [
      {
        "l": "after {[(",
        "v": [
          "{",
          "[",
          "("
        ]
      },
      {
        "l": "after )",
        "v": [
          "{",
          "["
        ]
      },
      {
        "l": "end",
        "v": []
      }
    ],
    "cap": "Every closer pops its matching opener."
  },
  "code": "class Solution {\n  public boolean isValid(String s) {\n    Deque<Character> stack = new ArrayDeque<>();\n    for (char ch : s.toCharArray()) {\n      if (ch == '(' || ch == '[' || ch == '{') {\n        stack.push(ch);\n      } else {\n        if (stack.isEmpty()) return false;\n        char open = stack.pop();                       // closer must match the last opener\n        if ((ch == ')' && open != '(') || (ch == ']' && open != '[') || (ch == '}' && open != '{')) return false;\n      }\n    }\n    return stack.isEmpty();\n  }\n}",
  "method": "isValid",
  "defaultInput": "\"{[()]}\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "{[()]}"
      ],
      "expected": true
    },
    {
      "name": "Crossed brackets",
      "args": [
        "([)]"
      ],
      "expected": false
    },
    {
      "name": "Only an opener",
      "args": [
        "("
      ],
      "expected": false
    },
    {
      "name": "Empty string",
      "args": [
        ""
      ],
      "expected": true
    },
    {
      "name": "Three kinds in a row",
      "args": [
        "()[]{}"
      ],
      "expected": true
    },
    {
      "name": "Only a closer",
      "args": [
        "]"
      ],
      "expected": false
    }
  ],
  "challenge": {
    "question": "Is the bracket string valid?",
    "input": "\"{[(])}\"",
    "options": [
      "true",
      "false"
    ],
    "answer": 1,
    "explanation": "When ']' arrives, the most recent open bracket is '(' — the brackets cross instead of nesting, so the string is invalid."
  },
  "memory": {
    "remember": "Push every opener; each closer must match\nthe most recent opener.",
    "pattern": "Stack of open brackets"
  }
};

export default problem;
