// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H061",
  "number": 61,
  "slug": "binary-search",
  "title": "Binary Search",
  "category": "Binary Search",
  "definition": "Find target in a sorted array.",
  "example": {
    "input": "[1,3,5,7,9,11], target = 7",
    "output": "3"
  },
  "approach": "Look at the middle. If it is too small the target must be on the right, otherwise on the left. Halve the range every time.",
  "keyIdea": [
    "lo = 0, hi = n − 1",
    "mid = lo + (hi − lo) / 2",
    "Found → return mid",
    "Too small → lo = mid + 1; too big → hi = mid − 1"
  ],
  "time": "O(log n)",
  "space": "O(1)",
  "complexityWhy": "The range halves every step.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          1,
          3,
          5,
          7,
          9,
          11
        ],
        "hi": [
          2
        ],
        "p": {
          "2": "mid"
        }
      },
      {
        "v": [
          1,
          3,
          5,
          7,
          9,
          11
        ],
        "dim": [
          0,
          1,
          2
        ],
        "hi": [
          4
        ],
        "p": {
          "4": "mid"
        }
      },
      {
        "v": [
          1,
          3,
          5,
          7,
          9,
          11
        ],
        "dim": [
          0,
          1,
          2,
          4,
          5
        ],
        "ok": [
          3
        ],
        "p": {
          "3": "found"
        }
      }
    ],
    "cap": "5 < 7 → go right. 9 > 7 → go left. Found 7."
  },
  "code": "class Solution {\n  public int search(int[] arr, int target) {\n    int lo = 0, hi = arr.length - 1;\n    while (lo <= hi) {\n      int mid = lo + (hi - lo) / 2;         // middle index (safe from int overflow)\n      if (arr[mid] == target) return mid;\n      if (arr[mid] < target) lo = mid + 1;  // target is on the right\n      else hi = mid - 1;                    // target is on the left\n    }\n    return -1;\n  }\n}",
  "method": "search",
  "defaultInput": "[1,3,5,7,9,11], 7",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          3,
          5,
          7,
          9,
          11
        ],
        7
      ],
      "expected": 3
    },
    {
      "name": "Not found",
      "args": [
        [
          1,
          3,
          5,
          7,
          9,
          11
        ],
        4
      ],
      "expected": -1
    },
    {
      "name": "First element",
      "args": [
        [
          1,
          3,
          5,
          7
        ],
        1
      ],
      "expected": 0
    },
    {
      "name": "Last element",
      "args": [
        [
          1,
          3,
          5,
          7
        ],
        7
      ],
      "expected": 3
    },
    {
      "name": "Single element",
      "args": [
        [
          5
        ],
        5
      ],
      "expected": 0
    },
    {
      "name": "Empty array",
      "args": [
        [],
        3
      ],
      "expected": -1
    }
  ],
  "challenge": {
    "question": "At which index is the target?",
    "input": "[2,5,8,12,16,23,38], 23",
    "options": [
      "6",
      "4",
      "5",
      "7"
    ],
    "answer": 2,
    "explanation": "Middle (12) is smaller than 23 → search the right half; its middle is 23 → found at index 5."
  },
  "memory": {
    "remember": "Look at the middle, throw away\nthe half that can't contain the target.",
    "pattern": "Binary search (halve each step)"
  }
};

export default problem;
