// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H102",
  "number": 102,
  "slug": "middle-of-the-linked-list",
  "title": "Middle of the Linked List",
  "category": "Linked List",
  "definition": "Return the middle node (second middle if even length).",
  "example": {
    "input": "1 → 2 → 3 → 4 → 5",
    "output": "3"
  },
  "approach": "Move a slow pointer one step and a fast pointer two steps. When fast reaches the end, slow is in the middle.",
  "keyIdea": [
    "slow and fast start at head",
    "slow moves 1, fast moves 2",
    "Stop when fast reaches the end",
    "slow is the middle"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass.",
  "figure": {
    "k": "list",
    "v": [
      1,
      2,
      3,
      4,
      5
    ],
    "ok": [
      2
    ],
    "p": {
      "2": "slow"
    },
    "cap": "When fast reaches the end, slow is at the middle."
  },
  "code": "class Solution {\n  public ListNode middleNode(ListNode head) {\n    ListNode slow = head, fast = head;\n    while (fast != null && fast.next != null) {\n      slow = slow.next;            // 1 step\n      fast = fast.next.next;       // 2 steps\n    }\n    return slow;                   // fast is at the end -> slow is in the middle\n  }\n}",
  "method": "middleNode",
  "defaultInput": "[1,2,3,4,5]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        3,
        4,
        5
      ]
    },
    {
      "name": "Even length",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          6
        ]
      ],
      "expected": [
        4,
        5,
        6
      ]
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "Two nodes",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": [
        2
      ]
    },
    {
      "name": "Empty list",
      "args": [
        []
      ],
      "expected": null
    },
    {
      "name": "Three nodes",
      "args": [
        [
          7,
          8,
          9
        ]
      ],
      "expected": [
        8,
        9
      ]
    }
  ],
  "challenge": {
    "question": "What does middleNode return for 1 → 2 → 3 → 4 → 5 → 6 (the list from the middle node on)?",
    "input": "[1,2,3,4,5,6]",
    "options": [
      "[5,6,4]",
      "[6,5,4]",
      "[4,5,6]",
      "[5,4,6]"
    ],
    "answer": 2,
    "explanation": "Slow moves one step while fast moves two. When fast reaches the end, slow is on the second middle node (4), so we get 4 → 5 → 6."
  },
  "memory": {
    "remember": "Fast moves two steps, slow moves one —\nwhen fast finishes, slow is in the middle.",
    "pattern": "Fast & slow pointers"
  }
};

export default problem;
