// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H029",
  "number": 29,
  "slug": "minimum-window-substring",
  "title": "Minimum Window Substring",
  "category": "Strings",
  "definition": "Smallest substring of s that contains every character of t.",
  "example": {
    "input": "s = \"ADOBECODEBANC\", t = \"ABC\"",
    "output": "\"BANC\""
  },
  "approach": "Check every substring: does it contain all the letters we need? Keep the shortest one that does.",
  "keyIdea": [
    "Try every start and end",
    "Check if the window has all letters of t",
    "Keep the shortest"
  ],
  "time": "O(n²·m)",
  "space": "O(m)",
  "complexityWhy": "Every substring is re-checked from scratch.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "A",
          "D",
          "O",
          "B",
          "E",
          "C",
          "O",
          "D",
          "E",
          "B",
          "A",
          "N",
          "C"
        ],
        "ok": [
          9,
          10,
          11,
          12
        ],
        "br": [
          [
            9,
            12,
            "BANC"
          ]
        ]
      }
    ],
    "cap": "Grow until A, B, C are all inside, then shrink from the left."
  },
  "better": {
    "name": "Sliding window with counts",
    "time": "O(n)",
    "space": "O(m)",
    "code": "class Solution {\n  public String minWindow(String s, String t) {\n    int[] need = new int[128];\n    for (char ch : t.toCharArray()) need[ch]++;\n    int missing = t.length(), left = 0, bestStart = 0, bestLen = Integer.MAX_VALUE;\n    for (int right = 0; right < s.length(); right++) {\n      if (need[s.charAt(right)]-- > 0) missing--;\n      while (missing == 0) {                            // window is valid -> shrink it\n        if (right - left + 1 < bestLen) { bestLen = right - left + 1; bestStart = left; }\n        if (++need[s.charAt(left)] > 0) missing++;\n        left++;\n      }\n    }\n    return bestLen == Integer.MAX_VALUE ? \"\" : s.substring(bestStart, bestStart + bestLen);\n  }\n}"
  },
  "code": "class Solution {\n  public String minWindow(String s, String t) {\n    String best = \"\";\n    for (int start = 0; start < s.length(); start++) {\n      for (int end = start + t.length() - 1; end < s.length(); end++) {\n        String piece = s.substring(start, end + 1);\n        if (containsAll(piece, t) && (best.isEmpty() || piece.length() < best.length())) best = piece;\n      }\n    }\n    return best;\n  }\n  private boolean containsAll(String piece, String t) {\n    int[] need = new int[128];\n    for (char ch : t.toCharArray()) need[ch]++;\n    for (char ch : piece.toCharArray()) if (need[ch] > 0) need[ch]--;\n    for (int v : need) if (v != 0) return false;\n    return true;\n  }\n}",
  "method": "minWindow",
  "defaultInput": "\"ADOBECODEBANC\", \"ABC\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "ADOBECODEBANC",
        "ABC"
      ],
      "expected": "BANC"
    },
    {
      "name": "Whole string",
      "args": [
        "ab",
        "ab"
      ],
      "expected": "ab"
    },
    {
      "name": "No window",
      "args": [
        "a",
        "b"
      ],
      "expected": ""
    },
    {
      "name": "Single",
      "args": [
        "a",
        "a"
      ],
      "expected": "a"
    },
    {
      "name": "Repeats needed",
      "args": [
        "aa",
        "aa"
      ],
      "expected": "aa"
    },
    {
      "name": "At the start",
      "args": [
        "ABCDE",
        "AB"
      ],
      "expected": "AB"
    }
  ],
  "challenge": {
    "question": "What is the smallest window of s that contains all letters of t?",
    "input": "\"xyyzyzyx\", \"xyz\"",
    "options": [
      "\"zyx\"",
      "\"xyz\"",
      "\"yx\"",
      "\"zy\""
    ],
    "answer": 0,
    "explanation": "\"zyx\" at the end is the shortest piece (length 3) that contains x, y and z."
  },
  "memory": {
    "remember": "Grow the window until it's valid,\nthen shrink while it stays valid.",
    "pattern": "Sliding window with counts"
  }
};

export default problem;
