// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H072",
  "number": 72,
  "slug": "maximum-depth-of-binary-tree",
  "title": "Maximum Depth of Binary Tree",
  "category": "Trees",
  "definition": "Number of nodes on the longest root-to-leaf path.",
  "example": {
    "input": "[3,9,20,null,null,15,7]",
    "output": "3"
  },
  "approach": "Depth of a tree = 1 + the deeper of its two subtrees.",
  "keyIdea": [
    "Empty tree → 0",
    "1 + max(depth(left), depth(right))"
  ],
  "time": "O(n)",
  "space": "O(h)",
  "complexityWhy": "Visits each node once.",
  "figure": {
    "k": "tree",
    "v": [
      3,
      9,
      20,
      null,
      null,
      15,
      7
    ],
    "ok": [
      3,
      20,
      15
    ],
    "cap": "Longest path 3 → 20 → 15 has 3 nodes."
  },
  "code": "class Solution {\n  public int maxDepth(TreeNode root) {\n    if (root == null) return 0;\n    int left = maxDepth(root.left);\n    int right = maxDepth(root.right);\n    return 1 + Math.max(left, right);\n  }\n}",
  "method": "maxDepth",
  "defaultInput": "[3,9,20,null,null,15,7]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          9,
          20,
          null,
          null,
          15,
          7
        ]
      ],
      "expected": 3
    },
    {
      "name": "Empty tree",
      "args": [
        []
      ],
      "expected": 0
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Left chain",
      "args": [
        [
          1,
          2,
          null,
          3
        ]
      ],
      "expected": 3
    },
    {
      "name": "Balanced",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          6,
          7
        ]
      ],
      "expected": 3
    },
    {
      "name": "Uneven",
      "args": [
        [
          1,
          2,
          3,
          4,
          5,
          null,
          null,
          6
        ]
      ],
      "expected": 4
    }
  ],
  "challenge": {
    "question": "What is the maximum depth?",
    "input": "[1,2,3,4,null,null,5,6]",
    "options": [
      "5",
      "2",
      "7",
      "4"
    ],
    "answer": 3,
    "explanation": "The longest path 1 → 2 → 4 → 6 has 4 nodes, so the depth is 4."
  },
  "memory": {
    "remember": "Depth = 1 + the deeper of\nthe two subtrees.",
    "pattern": "Recursion: 1 + max(left, right)"
  }
};

export default problem;
