// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H031",
  "number": 31,
  "slug": "find-first-occurrence-of-a-string",
  "title": "Find First Occurrence of a String (KMP)",
  "category": "Strings",
  "definition": "Find where the small word (needle) first appears inside the big text (haystack), or −1.",
  "example": {
    "input": "haystack = \"sadbutsad\", needle = \"sad\"",
    "output": "0"
  },
  "approach": "Slide the needle along the haystack and check if it matches at each position.",
  "keyIdea": [
    "Try each starting position",
    "Compare letters one by one",
    "Return the first full match"
  ],
  "time": "O(n·m)",
  "space": "O(1)",
  "complexityWhy": "After a mismatch we restart from the next position.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "text",
        "v": [
          "s",
          "a",
          "d",
          "b",
          "u",
          "t",
          "s",
          "a",
          "d"
        ],
        "ok": [
          0,
          1,
          2
        ]
      },
      {
        "l": "needle",
        "v": [
          "s",
          "a",
          "d"
        ],
        "ok": [
          0,
          1,
          2
        ]
      }
    ],
    "cap": "Match found at index 0."
  },
  "better": {
    "name": "KMP (never re-reads the haystack)",
    "time": "O(n+m)",
    "space": "O(m)",
    "code": "class Solution {\n  public int strStr(String haystack, String needle) {\n    if (needle.isEmpty()) return 0;\n    int[] lps = new int[needle.length()];               // longest prefix that is also a suffix\n    for (int i = 1, len = 0; i < needle.length(); ) {\n      if (needle.charAt(i) == needle.charAt(len)) lps[i++] = ++len;\n      else if (len > 0) len = lps[len - 1];\n      else lps[i++] = 0;\n    }\n    for (int i = 0, j = 0; i < haystack.length(); ) {\n      if (haystack.charAt(i) == needle.charAt(j)) {\n        i++; j++;\n        if (j == needle.length()) return i - j;\n      } else if (j > 0) j = lps[j - 1];                 // fall back, don't restart\n      else i++;\n    }\n    return -1;\n  }\n}"
  },
  "code": "class Solution {\n  public int strStr(String haystack, String needle) {\n    for (int i = 0; i + needle.length() <= haystack.length(); i++) {\n      int j = 0;\n      while (j < needle.length() && haystack.charAt(i + j) == needle.charAt(j)) j++;\n      if (j == needle.length()) return i;               // every letter matched\n    }\n    return -1;\n  }\n}",
  "method": "strStr",
  "defaultInput": "\"sadbutsad\", \"sad\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "sadbutsad",
        "sad"
      ],
      "expected": 0
    },
    {
      "name": "Not found",
      "args": [
        "leetcode",
        "leeto"
      ],
      "expected": -1
    },
    {
      "name": "Middle",
      "args": [
        "hello",
        "ll"
      ],
      "expected": 2
    },
    {
      "name": "Empty needle",
      "args": [
        "abc",
        ""
      ],
      "expected": 0
    },
    {
      "name": "Needle longer",
      "args": [
        "a",
        "abc"
      ],
      "expected": -1
    },
    {
      "name": "Full match",
      "args": [
        "abc",
        "abc"
      ],
      "expected": 0
    }
  ],
  "challenge": {
    "question": "At which index does the needle first appear?",
    "input": "\"mississippi\", \"issip\"",
    "options": [
      "4",
      "6",
      "2",
      "5"
    ],
    "answer": 0,
    "explanation": "Index 4: m-i-s-s-[i-s-s-i-p]-p-i — the substring from 4 to 8 is \"issip\"."
  },
  "memory": {
    "remember": "Slide the needle along the haystack\nand compare at each start.",
    "pattern": "Brute-force String Match"
  }
};

export default problem;
