// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H081",
  "number": 81,
  "slug": "kth-smallest-element-in-bst",
  "title": "Kth Smallest Element in BST",
  "category": "Trees",
  "definition": "Return the kth smallest value in a BST.",
  "example": {
    "input": "[5,3,6,2,4,null,null,1], k = 3",
    "output": "3"
  },
  "approach": "Inorder of a BST is sorted. Write it into an array and pick the kth.",
  "keyIdea": [
    "Inorder traversal into an array",
    "Return values[k − 1]"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "Visits all nodes even when k is small.",
  "figure": {
    "k": "tree",
    "v": [
      5,
      3,
      6,
      2,
      4,
      null,
      null,
      1
    ],
    "ok": [
      1,
      2,
      3
    ],
    "cap": "Inorder: 1, 2, 3 … the 3rd smallest is 3."
  },
  "better": {
    "name": "Iterative inorder, stop at k",
    "time": "O(h + k)",
    "space": "O(h)",
    "code": "class Solution {\n  public int kthSmallest(TreeNode root, int k) {\n    Deque<TreeNode> stack = new ArrayDeque<>();\n    TreeNode node = root;\n    while (node != null || !stack.isEmpty()) {\n      while (node != null) { stack.push(node); node = node.left; }   // go as far left as possible\n      node = stack.pop();\n      if (--k == 0) return node.val;                                  // the kth visited node\n      node = node.right;\n    }\n    return -1;\n  }\n}"
  },
  "code": "class Solution {\n  public int kthSmallest(TreeNode root, int k) {\n    List<Integer> values = new ArrayList<>();\n    inorder(root, values);\n    return values.get(k - 1);\n  }\n  private void inorder(TreeNode node, List<Integer> values) {\n    if (node == null) return;\n    inorder(node.left, values);\n    values.add(node.val);\n    inorder(node.right, values);\n  }\n}",
  "method": "kthSmallest",
  "defaultInput": "[5,3,6,2,4,null,null,1], 3",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          5,
          3,
          6,
          2,
          4,
          null,
          null,
          1
        ],
        3
      ],
      "expected": 3
    },
    {
      "name": "k = 1",
      "args": [
        [
          5,
          3,
          6,
          2,
          4,
          null,
          null,
          1
        ],
        1
      ],
      "expected": 1
    },
    {
      "name": "Last value",
      "args": [
        [
          3,
          1,
          4,
          null,
          2
        ],
        4
      ],
      "expected": 4
    },
    {
      "name": "Single node",
      "args": [
        [
          7
        ],
        1
      ],
      "expected": 7
    },
    {
      "name": "Right chain",
      "args": [
        [
          1,
          null,
          2,
          null,
          3
        ],
        2
      ],
      "expected": 2
    },
    {
      "name": "Balanced",
      "args": [
        [
          4,
          2,
          6,
          1,
          3,
          5,
          7
        ],
        5
      ],
      "expected": 5
    }
  ],
  "challenge": {
    "question": "What is the k-th smallest value in the BST?",
    "input": "[7,3,9,1,5,8,10], 4",
    "options": [
      "7",
      "6",
      "5",
      "8"
    ],
    "answer": 0,
    "explanation": "Inorder traversal of a BST is sorted: 1, 3, 5, 7, 8, 9, 10 — the 4th smallest is 7."
  },
  "memory": {
    "remember": "Inorder of a BST is sorted —\nstop at the k-th node.",
    "pattern": "Inorder Traversal (Sorted Order)"
  }
};

export default problem;
