// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H047",
  "number": 47,
  "slug": "check-armstrong-number",
  "title": "Check Armstrong Number",
  "category": "Math & Number Theory",
  "definition": "Sum of each digit raised to the number of digits equals the number.",
  "example": {
    "input": "153",
    "output": "true  (1³ + 5³ + 3³ = 153)"
  },
  "approach": "Count the digits, raise each digit to that power and add. Use % 10 and / 10 to peel the digits off.",
  "keyIdea": [
    "digits = how many digits n has",
    "Take each last digit (n % 10)",
    "Add digit ^ digits",
    "Sum == n → Armstrong"
  ],
  "time": "O(d)",
  "space": "O(1)",
  "complexityWhy": "Only arithmetic, no String.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "digits",
        "v": [
          1,
          5,
          3
        ]
      },
      {
        "l": "cubes",
        "v": [
          1,
          125,
          27
        ],
        "ok": [
          0,
          1,
          2
        ]
      },
      {
        "l": "sum",
        "v": [
          153
        ],
        "ok": [
          0
        ]
      }
    ],
    "cap": "1 + 125 + 27 = 153"
  },
  "code": "class Solution {\n  public boolean isArmstrong(int n) {\n    int digits = 0;\n    for (int t = n; t > 0; t /= 10) digits++;                   // count digits\n    int sum = 0;\n    for (int t = n; t > 0; t /= 10) {\n      int d = t % 10, power = 1;                                // last digit\n      for (int k = 0; k < digits; k++) power *= d;\n      sum += power;\n    }\n    return sum == n;\n  }\n}",
  "method": "isArmstrong",
  "defaultInput": "153",
  "tests": [
    {
      "name": "Example",
      "args": [
        153
      ],
      "expected": true
    },
    {
      "name": "Not Armstrong",
      "args": [
        154
      ],
      "expected": false
    },
    {
      "name": "Single digit",
      "args": [
        5
      ],
      "expected": true
    },
    {
      "name": "Four digits",
      "args": [
        9474
      ],
      "expected": true
    },
    {
      "name": "Zero",
      "args": [
        0
      ],
      "expected": true
    },
    {
      "name": "Three digits",
      "args": [
        370
      ],
      "expected": true
    }
  ],
  "challenge": {
    "question": "Is it an Armstrong number?",
    "input": "371",
    "options": [
      "true",
      "false"
    ],
    "answer": 0,
    "explanation": "3³ + 7³ + 1³ = 27 + 343 + 1 = 371 — equal to the number itself."
  },
  "memory": {
    "remember": "Add each digit raised to the digit count;\nequal to n → Armstrong.",
    "pattern": "Arithmetic only (no string)"
  }
};

export default problem;
