// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H063",
  "number": 63,
  "slug": "search-in-rotated-sorted-array",
  "title": "Search in Rotated Sorted Array",
  "category": "Binary Search",
  "definition": "A sorted array was rotated (like 4,5,6,7,0,1,2). Find the position of target.",
  "example": {
    "input": "[4,5,6,7,0,1,2], target = 0",
    "output": "4"
  },
  "approach": "One half of the array is always sorted. Find that half, check whether the target lies in it, and throw the other half away.",
  "keyIdea": [
    "Find mid",
    "Left half sorted? Is target inside it?",
    "Otherwise the right half is sorted: is target inside it?",
    "Keep the half that can hold the target"
  ],
  "time": "O(log n)",
  "space": "O(1)",
  "complexityWhy": "The range halves every step.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          4,
          5,
          6,
          7,
          0,
          1,
          2
        ],
        "ok": [
          0,
          1,
          2,
          3
        ],
        "hi": [
          4,
          5,
          6
        ],
        "p": {
          "3": "mid"
        },
        "ix": 1
      }
    ],
    "cap": "Green half is sorted; check if the target is inside it."
  },
  "code": "class Solution {\n  public int searchRotated(int[] nums, int target) {\n    int lo = 0, hi = nums.length - 1;\n    while (lo <= hi) {\n      int mid = lo + (hi - lo) / 2;\n      if (nums[mid] == target) return mid;\n      if (nums[lo] <= nums[mid]) {                      // left half is sorted\n        if (nums[lo] <= target && target < nums[mid]) hi = mid - 1;\n        else lo = mid + 1;\n      } else {                                          // right half is sorted\n        if (nums[mid] < target && target <= nums[hi]) lo = mid + 1;\n        else hi = mid - 1;\n      }\n    }\n    return -1;\n  }\n}",
  "method": "searchRotated",
  "defaultInput": "[4,5,6,7,0,1,2], 0",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          4,
          5,
          6,
          7,
          0,
          1,
          2
        ],
        0
      ],
      "expected": 4
    },
    {
      "name": "Not found",
      "args": [
        [
          4,
          5,
          6,
          7,
          0,
          1,
          2
        ],
        3
      ],
      "expected": -1
    },
    {
      "name": "Not rotated",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ],
        4
      ],
      "expected": 3
    },
    {
      "name": "Single element",
      "args": [
        [
          1
        ],
        1
      ],
      "expected": 0
    },
    {
      "name": "Target in left part",
      "args": [
        [
          6,
          7,
          8,
          1,
          2,
          3,
          4,
          5
        ],
        7
      ],
      "expected": 1
    },
    {
      "name": "Two elements",
      "args": [
        [
          3,
          1
        ],
        1
      ],
      "expected": 1
    }
  ],
  "challenge": {
    "question": "At which index is the target in the rotated array?",
    "input": "[6,7,8,1,2,3,4,5], 3",
    "options": [
      "8",
      "10",
      "6",
      "5"
    ],
    "answer": 3,
    "explanation": "One half is always sorted. The right half [1,2,3,4,5] is sorted and contains 3, so the search goes there and finds 3 at index 5."
  },
  "memory": {
    "remember": "One half is always sorted —\ncheck whether the target lies inside it.",
    "pattern": "Modified binary search"
  }
};

export default problem;
