// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H032",
  "number": 32,
  "slug": "valid-palindrome",
  "title": "Valid Palindrome",
  "category": "Strings",
  "definition": "Ignoring punctuation and case, is the text a palindrome?",
  "example": {
    "input": "\"A man, a plan, a canal: Panama\"",
    "output": "true"
  },
  "approach": "Put one pointer at each end. Skip anything that is not a letter or digit, then compare the two letters ignoring case.",
  "keyIdea": [
    "left = 0, right = n − 1",
    "Skip non-letters and non-digits on both sides",
    "Compare the lower-case letters",
    "Move both pointers inwards"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass, no copy of the string.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "a",
          "m",
          "a",
          "n",
          "a",
          "p",
          "l",
          "a",
          "n"
        ],
        "hi": [
          0,
          8
        ],
        "p": {
          "0": "L",
          "8": "R"
        }
      }
    ],
    "cap": "Compare from both ends, skipping punctuation."
  },
  "code": "class Solution {\n  public boolean isPalindrome(String s) {\n    int l = 0, r = s.length() - 1;\n    while (l < r) {\n      while (l < r && !Character.isLetterOrDigit(s.charAt(l))) l++;   // skip punctuation\n      while (l < r && !Character.isLetterOrDigit(s.charAt(r))) r--;\n      if (Character.toLowerCase(s.charAt(l)) != Character.toLowerCase(s.charAt(r))) return false;\n      l++; r--;\n    }\n    return true;\n  }\n}",
  "method": "isPalindrome",
  "defaultInput": "\"A man, a plan, a canal: Panama\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "A man, a plan, a canal: Panama"
      ],
      "expected": true
    },
    {
      "name": "Not a palindrome",
      "args": [
        "race a car"
      ],
      "expected": false
    },
    {
      "name": "Only a space",
      "args": [
        " "
      ],
      "expected": true
    },
    {
      "name": "Digits",
      "args": [
        "0P"
      ],
      "expected": false
    },
    {
      "name": "Single",
      "args": [
        "a"
      ],
      "expected": true
    },
    {
      "name": "Only punctuation",
      "args": [
        ".,"
      ],
      "expected": true
    }
  ],
  "challenge": {
    "question": "Is it a palindrome (ignoring punctuation and case)?",
    "input": "\"No 'x' in Nixon\"",
    "options": [
      "true",
      "false"
    ],
    "answer": 0,
    "explanation": "Ignoring case and punctuation it reads \"noxinnixon\" — the same backwards, so true."
  },
  "memory": {
    "remember": "Skip non-letters,\ncompare from both ends.",
    "pattern": "Two pointers (no extra string)"
  }
};

export default problem;
