// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H017",
  "number": 17,
  "slug": "find-nth-largest-element",
  "title": "Find Nth Largest / Nth Smallest Element (sort-based)",
  "category": "Arrays",
  "definition": "Return the nth largest element.",
  "example": {
    "input": "[3,2,1,5,6,4], n = 2",
    "output": "5"
  },
  "approach": "Find the biggest number, cross it out, and repeat n times. The last biggest number you found is the nth largest.",
  "keyIdea": [
    "Keep a used[] flag for every number",
    "Repeat n times: find the largest unused number",
    "Cross it out (mark it used)",
    "The last one found is the answer"
  ],
  "time": "O(n · n)",
  "space": "O(n)",
  "complexityWhy": "n scans over the array.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "sorted",
        "v": [
          6,
          5,
          4,
          3,
          2,
          1
        ],
        "ok": [
          1
        ],
        "p": {
          "1": "n = 2"
        }
      }
    ],
    "cap": "The 2nd largest is 5."
  },
  "better": {
    "name": "QuickSelect (average O(n))",
    "time": "O(n) avg",
    "space": "O(1)",
    "code": "class Solution {\n  public int nthLargest(int[] nums, int n) {\n    int[] arr = nums.clone();\n    int target = arr.length - n;            // position in ascending order\n    int lo = 0, hi = arr.length - 1;\n    while (lo <= hi) {\n      int pivot = arr[hi], i = lo;\n      for (int j = lo; j < hi; j++) {\n        if (arr[j] < pivot) { int t = arr[i]; arr[i] = arr[j]; arr[j] = t; i++; }\n      }\n      int t = arr[i]; arr[i] = arr[hi]; arr[hi] = t;   // pivot lands in final place\n      if (i == target) return arr[i];\n      if (i < target) lo = i + 1; else hi = i - 1;\n    }\n    return -1;\n  }\n}"
  },
  "code": "class Solution {\n  public int nthLargest(int[] nums, int n) {\n    boolean[] used = new boolean[nums.length];\n    int answer = 0;\n    for (int round = 0; round < n; round++) {          // find the largest, cross it out, repeat\n      int best = -1;\n      for (int i = 0; i < nums.length; i++) {\n        if (!used[i] && (best == -1 || nums[i] > nums[best])) best = i;\n      }\n      used[best] = true;\n      answer = nums[best];\n    }\n    return answer;                                      // the nth largest we found\n  }\n}",
  "method": "nthLargest",
  "defaultInput": "[3,2,1,5,6,4], 2",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          2,
          1,
          5,
          6,
          4
        ],
        2
      ],
      "expected": 5
    },
    {
      "name": "n = 1",
      "args": [
        [
          7,
          3,
          9,
          1
        ],
        1
      ],
      "expected": 9
    },
    {
      "name": "n = size",
      "args": [
        [
          7,
          3,
          9,
          1
        ],
        4
      ],
      "expected": 1
    },
    {
      "name": "Duplicates",
      "args": [
        [
          5,
          5,
          4,
          4,
          3
        ],
        3
      ],
      "expected": 4
    },
    {
      "name": "Negatives",
      "args": [
        [
          -1,
          -5,
          -3
        ],
        2
      ],
      "expected": -3
    },
    {
      "name": "Single",
      "args": [
        [
          9
        ],
        1
      ],
      "expected": 9
    }
  ],
  "challenge": {
    "question": "What is the 3rd largest value?",
    "input": "[8,2,9,4,7], 3",
    "options": [
      "8",
      "6",
      "9",
      "7"
    ],
    "answer": 3,
    "explanation": "Sorted from largest: 9, 8, 7, … — the 3rd largest is 7."
  },
  "memory": {
    "remember": "Sort it, then count n places\nfrom the end.",
    "pattern": "Sort and Index"
  }
};

export default problem;
