// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H143",
  "number": 143,
  "slug": "find-median-from-data-stream",
  "title": "Find Median from Data Stream (Two Heaps)",
  "category": "Heap / Priority Queue",
  "definition": "Add numbers one by one and ask for the median at any time.",
  "example": {
    "input": "add 1, add 2 → 1.5, add 3 → 2",
    "output": "1.5, 2"
  },
  "approach": "Keep a sorted list. Insert each new number at its correct position; the median is in the middle.",
  "keyIdea": [
    "addNum: find the sorted position and insert",
    "findMedian: middle element (or average of two)"
  ],
  "time": "O(n) add",
  "space": "O(n)",
  "complexityWhy": "Inserting shifts items, so every add costs O(n).",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "small half",
        "v": [
          2,
          1
        ],
        "ok": [
          0
        ],
        "p": {
          "0": "max"
        }
      },
      {
        "l": "big half",
        "v": [
          3
        ],
        "hi": [
          0
        ],
        "p": {
          "0": "min"
        }
      }
    ],
    "cap": "The median sits at the top of the heaps: here 2."
  },
  "better": {
    "name": "Two heaps: small half & big half",
    "time": "O(log n) add, O(1) median",
    "space": "O(n)",
    "code": "class MedianFinder {\n  private final PriorityQueue<Integer> low = new PriorityQueue<>((a, b) -> Integer.compare(b, a));   // max-heap: smaller half\n  private final PriorityQueue<Integer> high = new PriorityQueue<>();                            // min-heap: bigger half\n  public void addNum(int num) {\n    low.add(num);\n    high.add(low.poll());                                     // balance: biggest of low goes to high\n    if (high.size() > low.size()) low.add(high.poll());\n  }\n  public double findMedian() {\n    if (low.size() > high.size()) return low.peek();\n    return (low.peek() + high.peek()) / 2.0;\n  }\n}"
  },
  "code": "class MedianFinder {\n  private final List<Integer> nums = new ArrayList<>();\n  public void addNum(int num) {\n    int i = 0;\n    while (i < nums.size() && nums.get(i) < num) i++;        // find the sorted position\n    nums.add(i, num);\n  }\n  public double findMedian() {\n    int n = nums.size(), mid = n / 2;\n    return (n % 2 == 1) ? nums.get(mid) : (nums.get(mid - 1) + nums.get(mid)) / 2.0;\n  }\n}",
  "method": "MedianFinder",
  "defaultInput": "[], [[\"addNum\",1],[\"addNum\",2],[\"findMedian\"],[\"addNum\",3],[\"findMedian\"]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [],
        [
          [
            "addNum",
            1
          ],
          [
            "addNum",
            2
          ],
          [
            "findMedian"
          ],
          [
            "addNum",
            3
          ],
          [
            "findMedian"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        1.5,
        null,
        2
      ]
    },
    {
      "name": "One number",
      "args": [
        [],
        [
          [
            "addNum",
            5
          ],
          [
            "findMedian"
          ]
        ]
      ],
      "expected": [
        null,
        5
      ]
    },
    {
      "name": "Unsorted input",
      "args": [
        [],
        [
          [
            "addNum",
            3
          ],
          [
            "addNum",
            1
          ],
          [
            "addNum",
            2
          ],
          [
            "findMedian"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        2
      ]
    },
    {
      "name": "Even count",
      "args": [
        [],
        [
          [
            "addNum",
            1
          ],
          [
            "addNum",
            2
          ],
          [
            "addNum",
            3
          ],
          [
            "addNum",
            4
          ],
          [
            "findMedian"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        null,
        null,
        2.5
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [],
        [
          [
            "addNum",
            -1
          ],
          [
            "addNum",
            -2
          ],
          [
            "findMedian"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        -1.5
      ]
    },
    {
      "name": "Duplicates",
      "args": [
        [],
        [
          [
            "addNum",
            2
          ],
          [
            "addNum",
            2
          ],
          [
            "findMedian"
          ]
        ]
      ],
      "expected": [
        null,
        null,
        2
      ]
    }
  ],
  "challenge": {
    "question": "After adding 5, 15 and 1 — what does findMedian() return?",
    "input": "[], [[\"addNum\",5],[\"addNum\",15],[\"addNum\",1],[\"findMedian\"]]",
    "options": [
      "4",
      "6",
      "5",
      "3"
    ],
    "answer": 2,
    "explanation": "Sorted: 1, 5, 15 — the middle value is 5."
  },
  "memory": {
    "remember": "Lower half in a max-heap, upper half in a min-heap —\nthe median sits at the tops.",
    "pattern": "Two heaps: small half & big half"
  }
};

export default problem;
