// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H140",
  "number": 140,
  "slug": "top-k-frequent-elements",
  "title": "Top K Frequent Elements",
  "category": "Heap / Priority Queue",
  "definition": "Return the k values that appear most often.",
  "example": {
    "input": "[1,1,1,2,2,3], k = 2",
    "output": "[1,2]"
  },
  "approach": "Count how many times each number appears, sort by count (biggest first) and take the first k.",
  "keyIdea": [
    "Count with a Map",
    "Sort the entries by count, descending",
    "Take the first k"
  ],
  "time": "O(n log n)",
  "space": "O(n)",
  "complexityWhy": "Sorting all distinct values.",
  "figure": {
    "k": "flow",
    "s": [
      "count → 1:3   2:2   3:1",
      "buckets by frequency → [3]: 1   [2]: 2   [1]: 3",
      "!read from the highest bucket down → 1, 2"
    ],
    "cap": "A heap of size k gives O(n log k) if you prefer that."
  },
  "better": {
    "name": "Bucket sort by frequency",
    "time": "O(n)",
    "space": "O(n)",
    "code": "class Solution {\n  public int[] topKFrequent(int[] nums, int k) {\n    Map<Integer, Integer> count = new HashMap<>();\n    for (int n : nums) count.put(n, count.getOrDefault(n, 0) + 1);\n    List<List<Integer>> buckets = new ArrayList<>();           // index = frequency\n    for (int i = 0; i <= nums.length; i++) buckets.add(new ArrayList<>());\n    for (Map.Entry<Integer, Integer> e : count.entrySet()) buckets.get(e.getValue()).add(e.getKey());\n    int[] result = new int[k];\n    int idx = 0;\n    for (int f = buckets.size() - 1; f >= 0 && idx < k; f--) {\n      for (int num : buckets.get(f)) if (idx < k) result[idx++] = num;\n    }\n    return result;\n  }\n}"
  },
  "code": "class Solution {\n  public int[] topKFrequent(int[] nums, int k) {\n    Map<Integer, Integer> count = new HashMap<>();\n    for (int n : nums) count.put(n, count.getOrDefault(n, 0) + 1);\n    List<Map.Entry<Integer, Integer>> entries = new ArrayList<>(count.entrySet());\n    entries.sort((a, b) -> b.getValue() - a.getValue());       // most frequent first\n    int[] result = new int[k];\n    for (int i = 0; i < k; i++) result[i] = entries.get(i).getKey();\n    return result;\n  }\n}",
  "method": "topKFrequent",
  "unordered": true,
  "defaultInput": "[1,1,1,2,2,3], 2",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          1,
          1,
          2,
          2,
          3
        ],
        2
      ],
      "expected": [
        1,
        2
      ]
    },
    {
      "name": "Single number",
      "args": [
        [
          1
        ],
        1
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "Clear winners",
      "args": [
        [
          4,
          4,
          4,
          5,
          5,
          6,
          6,
          6,
          6
        ],
        2
      ],
      "expected": [
        6,
        4
      ]
    },
    {
      "name": "All numbers",
      "args": [
        [
          1,
          2
        ],
        2
      ],
      "expected": [
        1,
        2
      ]
    },
    {
      "name": "Top three",
      "args": [
        [
          5,
          5,
          5,
          5,
          3,
          3,
          3,
          1,
          1,
          2
        ],
        3
      ],
      "expected": [
        5,
        3,
        1
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          -1,
          -1,
          2,
          2,
          2,
          3
        ],
        2
      ],
      "expected": [
        2,
        -1
      ]
    }
  ],
  "challenge": {
    "question": "Which 2 numbers are the most frequent?",
    "input": "[7,7,7,8,8,9,9,9,9,1], 2",
    "options": [
      "[9,7]",
      "[9,8]",
      "[7,8]",
      "[9,1]"
    ],
    "answer": 0,
    "explanation": "9 appears 4 times and 7 appears 3 times; 8 appears only twice, and 1 only once — so the top two are 9 and 7."
  },
  "memory": {
    "remember": "Count frequencies with a Map,\nthen keep only the k biggest counts.",
    "pattern": "Count with a Map, then Pick the Top k"
  }
};

export default problem;
