// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H021",
  "number": 21,
  "slug": "majority-element",
  "title": "Majority Element (Boyer–Moore Voting)",
  "category": "Arrays",
  "definition": "Find the element that appears more than n/2 times.",
  "example": {
    "input": "[2,2,1,1,1,2,2]",
    "output": "2"
  },
  "approach": "Count how often each number appears and pick the one with the most.",
  "keyIdea": [
    "Count each number in a Map",
    "Track the number with the highest count",
    "Return it"
  ],
  "time": "O(n)",
  "space": "O(n)",
  "complexityWhy": "One pass plus a Map of counts.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums",
        "v": [
          2,
          2,
          1,
          1,
          1,
          2,
          2
        ]
      },
      {
        "l": "cand",
        "v": [
          2,
          2,
          2,
          2,
          1,
          1,
          2
        ],
        "ok": [
          6
        ]
      },
      {
        "l": "count",
        "v": [
          1,
          2,
          1,
          0,
          1,
          0,
          1
        ]
      }
    ],
    "cap": "Different numbers cancel out. The majority survives."
  },
  "better": {
    "name": "Boyer–Moore voting",
    "time": "O(n)",
    "space": "O(1)",
    "code": "class Solution {\n  public int majorityElement(int[] nums) {\n    int candidate = 0, count = 0;\n    for (int n : nums) {\n      if (count == 0) candidate = n;                   // new candidate\n      count += (n == candidate) ? 1 : -1;              // vote for or against\n    }\n    return candidate;\n  }\n}"
  },
  "code": "class Solution {\n  public int majorityElement(int[] nums) {\n    Map<Integer, Integer> counts = new HashMap<>();\n    for (int n : nums) counts.put(n, counts.getOrDefault(n, 0) + 1);\n    int best = nums[0];\n    for (Map.Entry<Integer, Integer> e : counts.entrySet()) {\n      if (e.getValue() > counts.get(best)) best = e.getKey();\n    }\n    return best;\n  }\n}",
  "method": "majorityElement",
  "defaultInput": "[2,2,1,1,1,2,2]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          2,
          2,
          1,
          1,
          1,
          2,
          2
        ]
      ],
      "expected": 2
    },
    {
      "name": "All same",
      "args": [
        [
          3,
          3,
          3
        ]
      ],
      "expected": 3
    },
    {
      "name": "Single",
      "args": [
        [
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "At the end",
      "args": [
        [
          1,
          2,
          2
        ]
      ],
      "expected": 2
    },
    {
      "name": "Bare majority",
      "args": [
        [
          1,
          1,
          2,
          2,
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Negatives",
      "args": [
        [
          -1,
          -1,
          2
        ]
      ],
      "expected": -1
    }
  ],
  "challenge": {
    "question": "Which value appears more than half of the time?",
    "input": "[5,1,5,2,5,3,5]",
    "options": [
      "2",
      "6",
      "3",
      "5"
    ],
    "answer": 3,
    "explanation": "5 appears 4 times out of 7 — more than half, so it is the majority element."
  },
  "memory": {
    "remember": "The majority can't be cancelled out\nby all the others together.",
    "pattern": "Count with a Map"
  }
};

export default problem;
