// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H121",
  "number": 121,
  "slug": "climbing-stairs",
  "title": "Climbing Stairs",
  "category": "Dynamic Programming",
  "definition": "You can climb 1 or 2 steps at a time. How many ways to reach step n?",
  "example": {
    "input": "n = 5",
    "output": "8"
  },
  "approach": "The ways to reach step n = the ways to reach step n − 1 plus the ways to reach step n − 2. You only need the last two numbers.",
  "keyIdea": [
    "ways(1) = 1, ways(2) = 2",
    "next = prev + curr",
    "Slide prev and curr forward"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass, two variables.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "steps",
        "v": [
          1,
          2,
          3,
          4,
          5
        ],
        "ix": 0
      },
      {
        "l": "ways",
        "v": [
          1,
          2,
          3,
          5,
          8
        ],
        "ok": [
          4
        ]
      }
    ],
    "cap": "Each value is the sum of the two before it (Fibonacci)."
  },
  "code": "class Solution {\n  public int climbStairs(int n) {\n    if (n <= 2) return n;\n    int prev = 1, curr = 2;                                // ways for step 1 and step 2\n    for (int i = 3; i <= n; i++) {\n      int next = prev + curr;\n      prev = curr;\n      curr = next;\n    }\n    return curr;\n  }\n}",
  "method": "climbStairs",
  "defaultInput": "5",
  "tests": [
    {
      "name": "Example",
      "args": [
        5
      ],
      "expected": 8
    },
    {
      "name": "One stair",
      "args": [
        1
      ],
      "expected": 1
    },
    {
      "name": "Two stairs",
      "args": [
        2
      ],
      "expected": 2
    },
    {
      "name": "Three stairs",
      "args": [
        3
      ],
      "expected": 3
    },
    {
      "name": "Ten stairs",
      "args": [
        10
      ],
      "expected": 89
    },
    {
      "name": "Forty-five stairs",
      "args": [
        45
      ],
      "expected": 1836311903
    }
  ],
  "challenge": {
    "question": "In how many ways can you climb 6 stairs (steps of 1 or 2)?",
    "input": "6",
    "options": [
      "13",
      "14",
      "12",
      "15"
    ],
    "answer": 0,
    "explanation": "ways(n) = ways(n−1) + ways(n−2): 1, 2, 3, 5, 8, 13 → 13 ways for 6 stairs."
  },
  "memory": {
    "remember": "Ways to reach a stair = ways to reach the stair below\n+ ways to reach the one before that.",
    "pattern": "Bottom-up with two variables"
  }
};

export default problem;
