// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H069",
  "number": 69,
  "slug": "kth-smallest-element-in-sorted-matrix",
  "title": "Kth Smallest Element in Sorted Matrix",
  "category": "Binary Search",
  "definition": "Rows and columns are sorted. Find the kth smallest value.",
  "example": {
    "input": "[[1,5,9],[10,11,13],[12,13,15]], k = 8",
    "output": "13"
  },
  "approach": "Repeat k times: look at the first unused value of every row and take the smallest. The kth value taken is the answer.",
  "keyIdea": [
    "next[r] = first unused column of row r",
    "Each round pick the smallest front value",
    "Move that row's pointer forward",
    "After k rounds the last value taken is the answer"
  ],
  "time": "O(k · n)",
  "space": "O(n)",
  "complexityWhy": "k rounds, each scans n rows.",
  "figure": {
    "k": "grid",
    "v": [
      [
        1,
        5,
        9
      ],
      [
        10,
        11,
        13
      ],
      [
        12,
        13,
        15
      ]
    ],
    "ok": [
      [
        1,
        2
      ]
    ],
    "cap": "Sorted order: 1,5,9,10,11,12,13,13 → the 8th value is 13."
  },
  "better": {
    "name": "Binary search on the value",
    "time": "O(n log(max−min))",
    "space": "O(1)",
    "code": "class Solution {\n  public int kthSmallest(int[][] matrix, int k) {\n    int n = matrix.length;\n    int lo = matrix[0][0], hi = matrix[n - 1][n - 1];\n    while (lo < hi) {\n      int mid = lo + (hi - lo) / 2;\n      int count = 0, col = n - 1;                      // count values <= mid\n      for (int row = 0; row < n; row++) {\n        while (col >= 0 && matrix[row][col] > mid) col--;\n        count += col + 1;\n      }\n      if (count >= k) hi = mid; else lo = mid + 1;\n    }\n    return lo;\n  }\n}"
  },
  "code": "class Solution {\n  public int kthSmallest(int[][] matrix, int k) {\n    int n = matrix.length;\n    int[] next = new int[n];                           // next[r] = first unused column of row r\n    int answer = 0;\n    for (int step = 0; step < k; step++) {             // take the smallest front value, k times\n      int bestRow = -1;\n      for (int r = 0; r < n; r++) {\n        if (next[r] < n && (bestRow == -1 || matrix[r][next[r]] < matrix[bestRow][next[bestRow]])) bestRow = r;\n      }\n      answer = matrix[bestRow][next[bestRow]];\n      next[bestRow]++;\n    }\n    return answer;\n  }\n}",
  "method": "kthSmallest",
  "defaultInput": "[[1,5,9],[10,11,13],[12,13,15]], 8",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            1,
            5,
            9
          ],
          [
            10,
            11,
            13
          ],
          [
            12,
            13,
            15
          ]
        ],
        8
      ],
      "expected": 13
    },
    {
      "name": "k = 1",
      "args": [
        [
          [
            1,
            2
          ],
          [
            3,
            4
          ]
        ],
        1
      ],
      "expected": 1
    },
    {
      "name": "Last element",
      "args": [
        [
          [
            1,
            2
          ],
          [
            1,
            3
          ]
        ],
        4
      ],
      "expected": 3
    },
    {
      "name": "Single cell",
      "args": [
        [
          [
            7
          ]
        ],
        1
      ],
      "expected": 7
    },
    {
      "name": "Duplicates",
      "args": [
        [
          [
            1,
            1
          ],
          [
            1,
            1
          ]
        ],
        3
      ],
      "expected": 1
    },
    {
      "name": "Rows far apart",
      "args": [
        [
          [
            1,
            2,
            3
          ],
          [
            10,
            11,
            12
          ],
          [
            20,
            21,
            22
          ]
        ],
        5
      ],
      "expected": 11
    }
  ],
  "challenge": {
    "question": "What is the k-th smallest value?",
    "input": "[[1,3,5],[6,7,12],[11,14,14]], 6",
    "options": [
      "12",
      "9",
      "10",
      "11"
    ],
    "answer": 3,
    "explanation": "Sorted order is 1, 3, 5, 6, 7, 11, 12, 14, 14 — the 6th smallest is 11."
  },
  "memory": {
    "remember": "Every row and column is sorted —\nbut the whole grid is not, so collect and sort.",
    "pattern": "Collect → Sort → Pick k"
  }
};

export default problem;
