// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H075",
  "number": 75,
  "slug": "symmetric-tree",
  "title": "Symmetric Tree",
  "category": "Trees",
  "definition": "Is the tree a mirror image of itself?",
  "example": {
    "input": "[1,2,2,3,4,4,3]",
    "output": "true"
  },
  "approach": "Compare the left subtree with the right subtree as if one were a mirror of the other.",
  "keyIdea": [
    "Two nodes mirror if their values match",
    "a.left mirrors b.right",
    "a.right mirrors b.left"
  ],
  "time": "O(n)",
  "space": "O(h)",
  "complexityWhy": "Each node is compared once.",
  "figure": {
    "k": "tree",
    "v": [
      1,
      2,
      2,
      3,
      4,
      4,
      3
    ],
    "hi": [
      2
    ],
    "ok": [
      3,
      4
    ],
    "cap": "Left side reads 2,3,4 and right side 2,4,3 — mirrored."
  },
  "code": "class Solution {\n  public boolean isSymmetric(TreeNode root) {\n    if (root == null) return true;\n    return isMirror(root.left, root.right);\n  }\n  private boolean isMirror(TreeNode a, TreeNode b) {\n    if (a == null && b == null) return true;   // both empty\n    if (a == null || b == null) return false;  // only one empty\n    return a.val == b.val\n        && isMirror(a.left, b.right)           // outer pair\n        && isMirror(a.right, b.left);          // inner pair\n  }\n}",
  "method": "isSymmetric",
  "defaultInput": "[1,2,2,3,4,4,3]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          2,
          3,
          4,
          4,
          3
        ]
      ],
      "expected": true
    },
    {
      "name": "Not symmetric",
      "args": [
        [
          1,
          2,
          2,
          null,
          3,
          null,
          3
        ]
      ],
      "expected": false
    },
    {
      "name": "Empty tree",
      "args": [
        []
      ],
      "expected": true
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": true
    },
    {
      "name": "Different values",
      "args": [
        [
          1,
          2,
          3
        ]
      ],
      "expected": false
    },
    {
      "name": "Mirrored chain",
      "args": [
        [
          1,
          2,
          2,
          null,
          3,
          3
        ]
      ],
      "expected": true
    }
  ],
  "challenge": {
    "question": "Is the tree symmetric?",
    "input": "[1,2,2,null,3,null,3]",
    "options": [
      "true",
      "false"
    ],
    "answer": 1,
    "explanation": "The left subtree has 3 as a right child, but the right subtree has 3 as a right child too — a mirror would need it on the left. So it is not symmetric."
  },
  "memory": {
    "remember": "Mirror check: left.left ↔ right.right\nand left.right ↔ right.left.",
    "pattern": "Compare Two Subtrees as Mirrors"
  }
};

export default problem;
