// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H125",
  "number": 125,
  "slug": "word-break",
  "title": "Word Break",
  "category": "Dynamic Programming",
  "definition": "Can the string be split into words from the dictionary?",
  "example": {
    "input": "\"leetcode\", [\"leet\",\"code\"]",
    "output": "true"
  },
  "approach": "dp[i] = can the first i letters be built from dictionary words? It is true if some earlier dp[j] is true and s[j..i) is a word.",
  "keyIdea": [
    "dp[0] = true",
    "For each i and each j < i",
    "dp[j] is true and s[j..i) is a word → dp[i] = true",
    "Answer dp[n]"
  ],
  "time": "O(n²)",
  "space": "O(n)",
  "complexityWhy": "Two loops over the string.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          "l",
          "e",
          "e",
          "t",
          "c",
          "o",
          "d",
          "e"
        ],
        "ok": [
          0,
          1,
          2,
          3
        ],
        "hi": [
          4,
          5,
          6,
          7
        ],
        "br": [
          [
            0,
            3,
            "leet"
          ],
          [
            4,
            7,
            "code"
          ]
        ]
      }
    ],
    "cap": "Both pieces are dictionary words."
  },
  "code": "class Solution {\n  public boolean wordBreak(String s, List<String> wordDict) {\n    Set<String> words = new HashSet<>(wordDict);\n    boolean[] dp = new boolean[s.length() + 1];            // dp[i]: can s[0..i) be built?\n    dp[0] = true;\n    for (int i = 1; i <= s.length(); i++) {\n      for (int j = 0; j < i; j++) {\n        if (dp[j] && words.contains(s.substring(j, i))) { dp[i] = true; break; }\n      }\n    }\n    return dp[s.length()];\n  }\n}",
  "method": "wordBreak",
  "defaultInput": "\"leetcode\", [\"leet\",\"code\"]",
  "tests": [
    {
      "name": "Example",
      "args": [
        "leetcode",
        [
          "leet",
          "code"
        ]
      ],
      "expected": true
    },
    {
      "name": "Reused word",
      "args": [
        "applepenapple",
        [
          "apple",
          "pen"
        ]
      ],
      "expected": true
    },
    {
      "name": "Not possible",
      "args": [
        "catsandog",
        [
          "cats",
          "dog",
          "sand",
          "and",
          "cat"
        ]
      ],
      "expected": false
    },
    {
      "name": "Single letter",
      "args": [
        "a",
        [
          "a"
        ]
      ],
      "expected": true
    },
    {
      "name": "Missing letter",
      "args": [
        "ab",
        [
          "a"
        ]
      ],
      "expected": false
    },
    {
      "name": "Overlapping words",
      "args": [
        "aaaa",
        [
          "a",
          "aa"
        ]
      ],
      "expected": true
    }
  ],
  "challenge": {
    "question": "Can the string be split into dictionary words?",
    "input": "\"catsandog\", [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]",
    "options": [
      "true",
      "false"
    ],
    "answer": 1,
    "explanation": "\"cats\" + \"and\" or \"cat\" + \"sand\" both leave \"og\" at the end, and no word matches \"og\" — so it can't be split."
  },
  "memory": {
    "remember": "dp[i] is true if some word ends at i\nand dp is true just before that word.",
    "pattern": "DP: dp[i] = can s[0..i) be broken?"
  }
};

export default problem;
