// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H020",
  "number": 20,
  "slug": "prefix-sum-range-sum-query",
  "title": "Prefix Sum — Range Sum Query",
  "category": "Arrays",
  "definition": "Answer many questions like: what is the sum from index l to index r?",
  "example": {
    "input": "[1,2,3,4,5], sum(0,2), sum(1,3)",
    "output": "6, 9"
  },
  "approach": "prefix[i] is the sum of the first i numbers. After that, any range sum is a single subtraction.",
  "keyIdea": [
    "Build prefix[i + 1] = prefix[i] + nums[i]",
    "sum(l..r) = prefix[r + 1] − prefix[l]"
  ],
  "time": "O(1) per query",
  "space": "O(n)",
  "complexityWhy": "O(n) once to build, then O(1) per query.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "nums",
        "v": [
          1,
          2,
          3,
          4,
          5
        ]
      },
      {
        "l": "prefix",
        "v": [
          0,
          1,
          3,
          6,
          10,
          15
        ],
        "hi": [
          1,
          4
        ],
        "p": {
          "1": "−",
          "4": "+"
        }
      }
    ],
    "cap": "sum(1,3) = prefix[4] − prefix[1] = 10 − 1 = 9"
  },
  "code": "class NumArray {\n  private int[] prefix;                     // prefix[i] = sum of first i numbers\n  public NumArray(int[] nums) {\n    prefix = new int[nums.length + 1];\n    for (int i = 0; i < nums.length; i++) prefix[i + 1] = prefix[i] + nums[i];\n  }\n  public int sumRange(int l, int r) { return prefix[r + 1] - prefix[l]; }\n}",
  "method": "NumArray",
  "defaultInput": "[[1,2,3,4,5]], [[\"sumRange\",0,2],[\"sumRange\",1,3]]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          [
            1,
            2,
            3,
            4,
            5
          ]
        ],
        [
          [
            "sumRange",
            0,
            2
          ],
          [
            "sumRange",
            1,
            3
          ]
        ]
      ],
      "expected": [
        6,
        9
      ]
    },
    {
      "name": "Whole range",
      "args": [
        [
          [
            5,
            1,
            2
          ]
        ],
        [
          [
            "sumRange",
            0,
            2
          ]
        ]
      ],
      "expected": [
        8
      ]
    },
    {
      "name": "Single element",
      "args": [
        [
          [
            7,
            3,
            9
          ]
        ],
        [
          [
            "sumRange",
            1,
            1
          ]
        ]
      ],
      "expected": [
        3
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          [
            -2,
            0,
            3,
            -5,
            2,
            -1
          ]
        ],
        [
          [
            "sumRange",
            0,
            2
          ],
          [
            "sumRange",
            2,
            5
          ],
          [
            "sumRange",
            0,
            5
          ]
        ]
      ],
      "expected": [
        1,
        -1,
        -3
      ]
    },
    {
      "name": "Same range twice",
      "args": [
        [
          [
            4,
            4,
            4
          ]
        ],
        [
          [
            "sumRange",
            0,
            1
          ],
          [
            "sumRange",
            0,
            1
          ]
        ]
      ],
      "expected": [
        8,
        8
      ]
    }
  ],
  "challenge": {
    "question": "What do the two calls return? sumRange(0, 2) and sumRange(2, 4)",
    "input": "[[3,1,4,1,5]], [[\"sumRange\",0,2],[\"sumRange\",2,4]]",
    "options": [
      "[10,8]",
      "[8]",
      "[9,11]",
      "[8,10]"
    ],
    "answer": 3,
    "explanation": "sumRange(0,2) = 3+1+4 = 8 and sumRange(2,4) = 4+1+5 = 10 — each is one subtraction of prefix sums."
  },
  "memory": {
    "remember": "Build prefix sums once —\nevery range sum is one subtraction.",
    "pattern": "Prefix sum array"
  }
};

export default problem;
