// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H138",
  "number": 138,
  "slug": "distinct-subsequences",
  "title": "Distinct Subsequences",
  "category": "Dynamic Programming",
  "definition": "Count the ways to make t by deleting letters from s.",
  "example": {
    "input": "s = \"rabbbit\", t = \"rabbit\"",
    "output": "3"
  },
  "approach": "For each letter of s, either skip it, or (if it matches the current letter of t) use it. Count both paths.",
  "keyIdea": [
    "t fully matched → 1 way",
    "s used up → 0 ways",
    "skip s[i]; and if s[i] = t[j] also use it"
  ],
  "time": "O(2ⁿ)",
  "space": "O(n)",
  "complexityWhy": "Every skip/use combination is explored.",
  "figure": {
    "k": "flow",
    "s": [
      "rabbbit → use b₁ b₂ (skip b₃)",
      "rabbbit → use b₁ b₃ (skip b₂)",
      "rabbbit → use b₂ b₃ (skip b₁)",
      "!3 ways to pick two b's"
    ],
    "cap": "Which two of the three b's do we keep?"
  },
  "better": {
    "name": "1-D DP",
    "time": "O(m·n)",
    "space": "O(n)",
    "code": "class Solution {\n  public int numDistinct(String s, String t) {\n    int[] dp = new int[t.length() + 1];                     // dp[j]: ways to build t[0..j)\n    dp[0] = 1;\n    for (int i = 0; i < s.length(); i++) {\n      for (int j = t.length(); j >= 1; j--) {               // backwards so we don't reuse s[i]\n        if (s.charAt(i) == t.charAt(j - 1)) dp[j] += dp[j - 1];\n      }\n    }\n    return dp[t.length()];\n  }\n}"
  },
  "code": "class Solution {\n  public int numDistinct(String s, String t) { return count(s, t, 0, 0); }\n  private int count(String s, String t, int i, int j) {\n    if (j == t.length()) return 1;                          // all of t matched\n    if (i == s.length()) return 0;                          // ran out of s\n    int ways = count(s, t, i + 1, j);                       // skip s[i]\n    if (s.charAt(i) == t.charAt(j)) ways += count(s, t, i + 1, j + 1);   // or use it\n    return ways;\n  }\n}",
  "method": "numDistinct",
  "defaultInput": "\"rabbbit\", \"rabbit\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "rabbbit",
        "rabbit"
      ],
      "expected": 3
    },
    {
      "name": "Classic",
      "args": [
        "babgbag",
        "bag"
      ],
      "expected": 5
    },
    {
      "name": "Single letter",
      "args": [
        "a",
        "a"
      ],
      "expected": 1
    },
    {
      "name": "Target longer",
      "args": [
        "abc",
        "abcd"
      ],
      "expected": 0
    },
    {
      "name": "Repeated letters",
      "args": [
        "aaa",
        "aa"
      ],
      "expected": 3
    },
    {
      "name": "Empty target",
      "args": [
        "abc",
        ""
      ],
      "expected": 1
    }
  ],
  "challenge": {
    "question": "In how many ways does \"ab\" appear as a subsequence of \"aabb\"?",
    "input": "\"aabb\", \"ab\"",
    "options": [
      "2",
      "4",
      "8",
      "6"
    ],
    "answer": 1,
    "explanation": "Either of the 2 a's can pair with either of the 2 b's: 2 × 2 = 4 ways."
  },
  "memory": {
    "remember": "If the letters match you may use the match or skip it;\notherwise skip the letter of s.",
    "pattern": "DP over Prefixes of s and t"
  }
};

export default problem;
