// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H097",
  "number": 97,
  "slug": "bellman-ford",
  "title": "Bellman–Ford (Negative Weights)",
  "category": "Graph",
  "definition": "Shortest distances when edges may have negative weights. Detect negative cycles.",
  "example": {
    "input": "5 nodes, some negative edges, source 0",
    "output": "[0,2,7,4,-2]"
  },
  "approach": "Relax every edge, over and over. After V − 1 rounds all shortest paths are found.",
  "keyIdea": [
    "dist[source] = 0, others = ∞",
    "Repeat V − 1 times: relax every edge",
    "One more round still improves something → negative cycle"
  ],
  "time": "O(V·E)",
  "space": "O(V)",
  "complexityWhy": "V − 1 rounds over all E edges.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "start",
        "v": [
          0,
          "∞",
          "∞",
          "∞",
          "∞"
        ]
      },
      {
        "l": "round 1",
        "v": [
          0,
          2,
          7,
          4,
          2
        ]
      },
      {
        "l": "round 2",
        "v": [
          0,
          2,
          7,
          4,
          -2
        ],
        "ok": [
          4
        ]
      }
    ],
    "cap": "Distances to nodes 0–4 improve until nothing changes."
  },
  "code": "class Solution {\n  public int[] bellmanFord(int n, int[][] edges, int source) {\n    final int INF = Integer.MAX_VALUE;\n    int[] dist = new int[n];\n    Arrays.fill(dist, INF);\n    dist[source] = 0;\n    for (int round = 1; round < n; round++) {\n      for (int[] e : edges) {\n        if (dist[e[0]] != INF && dist[e[0]] + e[2] < dist[e[1]]) dist[e[1]] = dist[e[0]] + e[2];   // relax\n      }\n    }\n    for (int[] e : edges) {\n      if (dist[e[0]] != INF && dist[e[0]] + e[2] < dist[e[1]]) return null;   // still improving -> negative cycle\n    }\n    return dist;\n  }\n}",
  "method": "bellmanFord",
  "defaultInput": "5, [[0,1,6],[0,2,7],[1,2,8],[1,3,5],[1,4,-4],[2,3,-3],[2,4,9],[3,1,-2],[4,0,2],[4,3,7]], 0",
  "tests": [
    {
      "name": "Example",
      "args": [
        5,
        [
          [
            0,
            1,
            6
          ],
          [
            0,
            2,
            7
          ],
          [
            1,
            2,
            8
          ],
          [
            1,
            3,
            5
          ],
          [
            1,
            4,
            -4
          ],
          [
            2,
            3,
            -3
          ],
          [
            2,
            4,
            9
          ],
          [
            3,
            1,
            -2
          ],
          [
            4,
            0,
            2
          ],
          [
            4,
            3,
            7
          ]
        ],
        0
      ],
      "expected": [
        0,
        2,
        7,
        4,
        -2
      ]
    },
    {
      "name": "Negative cycle",
      "args": [
        3,
        [
          [
            0,
            1,
            1
          ],
          [
            1,
            2,
            -3
          ],
          [
            2,
            0,
            1
          ]
        ],
        0
      ],
      "expected": null
    },
    {
      "name": "No negative edges",
      "args": [
        3,
        [
          [
            0,
            1,
            2
          ],
          [
            1,
            2,
            2
          ]
        ],
        0
      ],
      "expected": [
        0,
        2,
        4
      ]
    },
    {
      "name": "Unreachable node",
      "args": [
        3,
        [
          [
            0,
            1,
            1
          ]
        ],
        0
      ],
      "expected": [
        0,
        1,
        2147483647
      ]
    },
    {
      "name": "Single node",
      "args": [
        1,
        [],
        0
      ],
      "expected": [
        0
      ]
    },
    {
      "name": "One negative edge",
      "args": [
        3,
        [
          [
            0,
            1,
            4
          ],
          [
            0,
            2,
            5
          ],
          [
            1,
            2,
            -3
          ]
        ],
        0
      ],
      "expected": [
        0,
        4,
        1
      ]
    }
  ],
  "challenge": {
    "question": "What are the shortest distances from node 0 (negative edges are allowed)?",
    "input": "4, [[0,1,4],[0,2,5],[1,2,-3],[2,3,2]], 0",
    "options": [
      "[4,1,3,0]",
      "[4,3,1,0]",
      "[0,4,1,3]",
      "[4,0,1,3]"
    ],
    "answer": 2,
    "explanation": "The negative edge 1→2 (−3) makes 0→1→2 cost 4 − 3 = 1, cheaper than the direct 5. Then node 3 costs 1 + 2 = 3 → [0,4,1,3]."
  },
  "memory": {
    "remember": "Relax every edge n − 1 times.\nIf one more round still improves — negative cycle.",
    "pattern": "Relax All Edges n − 1 Times"
  }
};

export default problem;
