// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H015",
  "number": 15,
  "slug": "find-largest-smallest-element-in-array",
  "title": "Find Largest / Smallest Element in Array",
  "category": "Arrays",
  "definition": "Return the smallest and largest values.",
  "example": {
    "input": "[3,9,2,7,5]",
    "output": "min 2, max 9"
  },
  "approach": "Walk through the array once and keep the smallest and the largest value seen so far.",
  "keyIdea": [
    "min = max = first element",
    "For each number update min and max",
    "Return both"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "One pass.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          3,
          9,
          2,
          7,
          5
        ],
        "ok": [
          1
        ],
        "no": [
          2
        ],
        "p": {
          "1": "max",
          "2": "min"
        }
      }
    ],
    "cap": "Scan once, remembering the biggest and smallest."
  },
  "code": "class Solution {\n  public int[] findMinMax(int[] nums) {\n    int min = nums[0], max = nums[0];\n    for (int n : nums) {\n      if (n < min) min = n;\n      if (n > max) max = n;\n    }\n    return new int[]{min, max};\n  }\n}",
  "method": "findMinMax",
  "defaultInput": "[3,9,2,7,5]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          3,
          9,
          2,
          7,
          5
        ]
      ],
      "expected": [
        2,
        9
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          4
        ]
      ],
      "expected": [
        4,
        4
      ]
    },
    {
      "name": "All same",
      "args": [
        [
          6,
          6,
          6
        ]
      ],
      "expected": [
        6,
        6
      ]
    },
    {
      "name": "Negatives",
      "args": [
        [
          -3,
          -9,
          -1
        ]
      ],
      "expected": [
        -9,
        -1
      ]
    },
    {
      "name": "Sorted",
      "args": [
        [
          1,
          2,
          3,
          4
        ]
      ],
      "expected": [
        1,
        4
      ]
    },
    {
      "name": "Two",
      "args": [
        [
          8,
          2
        ]
      ],
      "expected": [
        2,
        8
      ]
    }
  ],
  "challenge": {
    "question": "What are the smallest and largest values? (min, max)",
    "input": "[7,2,9,4,5]",
    "options": [
      "[9,2]",
      "[2]",
      "[2,9]",
      "[3,10]"
    ],
    "answer": 2,
    "explanation": "One pass is enough: keep the smallest and largest value seen so far → 2 and 9."
  },
  "memory": {
    "remember": "One pass is enough —\nkeep a min and a max.",
    "pattern": "Single pass"
  }
};

export default problem;
