// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H065",
  "number": 65,
  "slug": "find-peak-element",
  "title": "Find Peak Element",
  "category": "Binary Search",
  "definition": "Find an index whose value is bigger than both neighbours.",
  "example": {
    "input": "[1,2,3,1]",
    "output": "2"
  },
  "approach": "Look at mid and its right neighbour. If the numbers go up, a peak is on the right; if they go down, a peak is here or on the left.",
  "keyIdea": [
    "Compare nums[mid] with nums[mid + 1]",
    "Going up → lo = mid + 1",
    "Going down → hi = mid",
    "lo == hi is a peak"
  ],
  "time": "O(log n)",
  "space": "O(1)",
  "complexityWhy": "The range halves every step.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "v": [
          1,
          2,
          3,
          1
        ],
        "ok": [
          2
        ],
        "p": {
          "2": "peak"
        },
        "ix": 1
      }
    ],
    "cap": "If the slope goes up, a peak must be ahead."
  },
  "code": "class Solution {\n  public int findPeakElement(int[] nums) {\n    int lo = 0, hi = nums.length - 1;\n    while (lo < hi) {\n      int mid = lo + (hi - lo) / 2;\n      if (nums[mid] < nums[mid + 1]) lo = mid + 1;   // going up -> peak on the right\n      else hi = mid;                                  // going down -> peak here or left\n    }\n    return lo;\n  }\n}",
  "method": "findPeakElement",
  "defaultInput": "[1,2,3,1]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          2,
          3,
          1
        ]
      ],
      "expected": 2
    },
    {
      "name": "Peak at the start",
      "args": [
        [
          5,
          3,
          2,
          1
        ]
      ],
      "expected": 0
    },
    {
      "name": "Peak at the end",
      "args": [
        [
          1,
          2,
          3,
          4
        ]
      ],
      "expected": 3
    },
    {
      "name": "Single element",
      "args": [
        [
          9
        ]
      ],
      "expected": 0
    },
    {
      "name": "One clear peak",
      "args": [
        [
          1,
          2,
          4,
          7,
          5,
          3
        ]
      ],
      "expected": 3
    },
    {
      "name": "Two elements",
      "args": [
        [
          1,
          2
        ]
      ],
      "expected": 1
    }
  ],
  "challenge": {
    "question": "Which index holds the peak?",
    "input": "[1,2,4,7,5,3]",
    "options": [
      "4",
      "2",
      "1",
      "3"
    ],
    "answer": 3,
    "explanation": "7 is bigger than both neighbours (4 and 5) — it is the only peak, at index 3."
  },
  "memory": {
    "remember": "Walk toward the bigger neighbour —\na peak has to be that way.",
    "pattern": "Binary search: climb uphill"
  }
};

export default problem;
