// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H043",
  "number": 43,
  "slug": "radix-sort",
  "title": "Radix Sort",
  "category": "Sorting Algorithms",
  "definition": "Sort integers digit by digit, from the last digit to the first.",
  "example": {
    "input": "[170,45,75,90,802,24,2,66]",
    "output": "[2,24,45,66,75,90,170,802]"
  },
  "approach": "Sort by the ones digit, then by the tens digit, then hundreds. Each pass keeps the previous order for ties.",
  "keyIdea": [
    "For each digit place (1, 10, 100…)",
    "Drop numbers into 10 buckets by that digit",
    "Read the buckets in order"
  ],
  "time": "O(d·(n + 10))",
  "space": "O(n)",
  "complexityWhy": "d = number of digits of the largest number.",
  "figure": {
    "k": "arr",
    "r": [
      {
        "l": "ones",
        "v": [
          170,
          90,
          802,
          2,
          24,
          45,
          75,
          66
        ]
      },
      {
        "l": "tens",
        "v": [
          802,
          2,
          24,
          45,
          66,
          170,
          75,
          90
        ]
      },
      {
        "l": "hundreds",
        "v": [
          2,
          24,
          45,
          66,
          75,
          90,
          170,
          802
        ],
        "ok": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7
        ]
      }
    ],
    "cap": "Three passes, one per digit."
  },
  "code": "class Solution {\n  public int[] radixSort(int[] arr) {\n    int max = 0;\n    for (int n : arr) max = Math.max(max, n);\n    for (int place = 1; max / place > 0; place *= 10) {\n      List<List<Integer>> buckets = new ArrayList<>();\n      for (int d = 0; d < 10; d++) buckets.add(new ArrayList<>());\n      for (int n : arr) buckets.get(n / place % 10).add(n);   // bucket by this digit\n      int k = 0;\n      for (List<Integer> bucket : buckets)                     // read buckets in order\n        for (int n : bucket) arr[k++] = n;\n    }\n    return arr;\n  }\n}",
  "method": "radixSort",
  "defaultInput": "[170,45,75,90,802,24,2,66]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          170,
          45,
          75,
          90,
          802,
          24,
          2,
          66
        ]
      ],
      "expected": [
        2,
        24,
        45,
        66,
        75,
        90,
        170,
        802
      ]
    },
    {
      "name": "Single digits",
      "args": [
        [
          5,
          3,
          9,
          1
        ]
      ],
      "expected": [
        1,
        3,
        5,
        9
      ]
    },
    {
      "name": "Already sorted",
      "args": [
        [
          10,
          20,
          30
        ]
      ],
      "expected": [
        10,
        20,
        30
      ]
    },
    {
      "name": "Single",
      "args": [
        [
          42
        ]
      ],
      "expected": [
        42
      ]
    },
    {
      "name": "Same digits",
      "args": [
        [
          11,
          22,
          33,
          11
        ]
      ],
      "expected": [
        11,
        11,
        22,
        33
      ]
    },
    {
      "name": "With zero",
      "args": [
        [
          0,
          100,
          10,
          1
        ]
      ],
      "expected": [
        0,
        1,
        10,
        100
      ]
    }
  ],
  "challenge": {
    "question": "After sorting only by the ones digit, the order is…",
    "input": "[170,45,75,90,802,24,2,66]",
    "options": [
      "[170,90,802,2,24,45,75,66]",
      "[802,2,24,45,66,170,75,90]",
      "[2,24,45,66,75,90,170,802]",
      "[170,45,75,90,802,24,2,66]"
    ],
    "answer": 0,
    "explanation": "By the last digit: 0 (170, 90), 2 (802, 2), 4 (24), 5 (45, 75), 6 (66) — equal digits keep their original order."
  },
  "memory": {
    "remember": "Sort by ones, then tens, then hundreds —\nkeep the order within each pass.",
    "pattern": "Digit by Digit (Stable)"
  }
};

export default problem;
