// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H070",
  "number": 70,
  "slug": "tree-traversals",
  "title": "Tree Traversals (In / Pre / Post — recursive & iterative)",
  "category": "Trees",
  "definition": "Visit every node in inorder, preorder and postorder.",
  "example": {
    "input": "tree: 1 → right 2 → left 3",
    "output": "in [1,3,2] · pre [1,2,3] · post [3,2,1]"
  },
  "approach": "Visit a node before its children (pre), between them (in) or after them (post). Recursion does the walking for us.",
  "keyIdea": [
    "Recursive DFS: visit(node)",
    "Pre: record before recursing",
    "In: record between left and right",
    "Post: record after both"
  ],
  "time": "O(n)",
  "space": "O(h)",
  "complexityWhy": "h = tree height (recursion depth). Very deep trees can cause a StackOverflowError.",
  "figure": [
    {
      "k": "tree",
      "v": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "k": "txt",
      "lines": [
        "preorder  1 2 4 5 3",
        "inorder   4 2 5 1 3",
        "postorder 4 5 2 3 1"
      ]
    }
  ],
  "better": {
    "name": "Iterative with an explicit stack",
    "time": "O(n)",
    "space": "O(h)",
    "code": "class Solution {\n  public List<List<Integer>> traversals(TreeNode root) {\n    List<Integer> inorder = new ArrayList<>(), preorder = new ArrayList<>();\n    LinkedList<Integer> postorder = new LinkedList<>();     // addFirst builds the reversed order\n    Deque<TreeNode> stack = new ArrayDeque<>();\n    TreeNode node = root;\n    while (node != null || !stack.isEmpty()) {           // inorder\n      while (node != null) { stack.push(node); node = node.left; }\n      node = stack.pop();\n      inorder.add(node.val);\n      node = node.right;\n    }\n    if (root != null) stack.push(root);                  // preorder\n    while (!stack.isEmpty()) {\n      node = stack.pop();\n      preorder.add(node.val);\n      if (node.right != null) stack.push(node.right);\n      if (node.left != null) stack.push(node.left);\n    }\n    if (root != null) stack.push(root);                  // postorder = reverse of (root, right, left)\n    while (!stack.isEmpty()) {\n      node = stack.pop();\n      postorder.addFirst(node.val);\n      if (node.left != null) stack.push(node.left);\n      if (node.right != null) stack.push(node.right);\n    }\n    return Arrays.asList(inorder, preorder, postorder);\n  }\n}"
  },
  "code": "class Solution {\n  private List<Integer> inorder, preorder, postorder;\n  public List<List<Integer>> traversals(TreeNode root) {\n    inorder = new ArrayList<>(); preorder = new ArrayList<>(); postorder = new ArrayList<>();\n    visit(root);\n    return Arrays.asList(inorder, preorder, postorder);\n  }\n  private void visit(TreeNode node) {\n    if (node == null) return;\n    preorder.add(node.val);       // 1) before the children\n    visit(node.left);\n    inorder.add(node.val);        // 2) between the children\n    visit(node.right);\n    postorder.add(node.val);      // 3) after the children\n  }\n}",
  "method": "traversals",
  "defaultInput": "[1,null,2,3]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          null,
          2,
          3
        ]
      ],
      "expected": [
        [
          1,
          3,
          2
        ],
        [
          1,
          2,
          3
        ],
        [
          3,
          2,
          1
        ]
      ]
    },
    {
      "name": "Empty tree",
      "args": [
        []
      ],
      "expected": [
        [],
        [],
        []
      ]
    },
    {
      "name": "Single node",
      "args": [
        [
          1
        ]
      ],
      "expected": [
        [
          1
        ],
        [
          1
        ],
        [
          1
        ]
      ]
    },
    {
      "name": "Balanced",
      "args": [
        [
          4,
          2,
          6,
          1,
          3,
          5,
          7
        ]
      ],
      "expected": [
        [
          1,
          2,
          3,
          4,
          5,
          6,
          7
        ],
        [
          4,
          2,
          1,
          3,
          6,
          5,
          7
        ],
        [
          1,
          3,
          2,
          5,
          7,
          6,
          4
        ]
      ]
    },
    {
      "name": "Left chain",
      "args": [
        [
          3,
          2,
          null,
          1
        ]
      ],
      "expected": [
        [
          1,
          2,
          3
        ],
        [
          3,
          2,
          1
        ],
        [
          1,
          2,
          3
        ]
      ]
    },
    {
      "name": "Small tree",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": [
        [
          4,
          2,
          5,
          1,
          3
        ],
        [
          1,
          2,
          4,
          5,
          3
        ],
        [
          4,
          5,
          2,
          3,
          1
        ]
      ]
    }
  ],
  "challenge": {
    "question": "What is the inorder traversal?",
    "input": "[4,2,7,1,3,6,9]",
    "options": [
      "[9,7,6,4,3,2,1]",
      "[2,3,4,6,7,9,1]",
      "[2,3,4,5,7,8,10]",
      "[1,2,3,4,6,7,9]"
    ],
    "answer": 3,
    "explanation": "Inorder visits the left subtree, then the node, then the right subtree: 1, 2, 3, 4, 6, 7, 9 — sorted, because this is a BST."
  },
  "memory": {
    "remember": "Pre: node first.  In: node in between.\nPost: node last.",
    "pattern": "Recursive DFS: Pre / In / Post"
  }
};

export default problem;
