// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H010",
  "number": 10,
  "slug": "container-with-most-water",
  "title": "Container With Most Water",
  "category": "Arrays",
  "definition": "Choose two lines that hold the most water with the x-axis.",
  "example": {
    "input": "[1,8,6,2,5,4,8,3,7]",
    "output": "49"
  },
  "approach": "Start with the widest container. The shorter line limits the water, so move the shorter side inwards and hope for a taller line.",
  "keyIdea": [
    "left = 0, right = n − 1",
    "area = shorter height × width",
    "Move the pointer at the shorter line",
    "Keep the biggest area"
  ],
  "time": "O(n)",
  "space": "O(1)",
  "complexityWhy": "Each pointer moves inwards once.",
  "figure": {
    "k": "bars",
    "r": [
      {
        "v": [
          1,
          8,
          6,
          2,
          5,
          4,
          8,
          3,
          7
        ],
        "ok": [
          1,
          8
        ]
      }
    ],
    "cap": "Lines 8 and 7, width 7 → 7 × 7 = 49."
  },
  "code": "class Solution {\n  public int maxArea(int[] height) {\n    int left = 0, right = height.length - 1, best = 0;\n    while (left < right) {\n      int h = Math.min(height[left], height[right]);\n      best = Math.max(best, h * (right - left));\n      if (height[left] < height[right]) left++;        // shorter side limits area\n      else right--;\n    }\n    return best;\n  }\n}",
  "method": "maxArea",
  "defaultInput": "[1,8,6,2,5,4,8,3,7]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          1,
          8,
          6,
          2,
          5,
          4,
          8,
          3,
          7
        ]
      ],
      "expected": 49
    },
    {
      "name": "Two bars",
      "args": [
        [
          1,
          1
        ]
      ],
      "expected": 1
    },
    {
      "name": "Tall ends",
      "args": [
        [
          8,
          1,
          1,
          1,
          8
        ]
      ],
      "expected": 32
    },
    {
      "name": "Increasing",
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ]
      ],
      "expected": 6
    },
    {
      "name": "Decreasing",
      "args": [
        [
          5,
          4,
          3,
          2,
          1
        ]
      ],
      "expected": 6
    },
    {
      "name": "All equal",
      "args": [
        [
          4,
          4,
          4
        ]
      ],
      "expected": 8
    }
  ],
  "challenge": {
    "question": "What is the largest amount of water a container can hold?",
    "input": "[2,5,4,1,6]",
    "options": [
      "13",
      "17",
      "15",
      "30"
    ],
    "answer": 2,
    "explanation": "The bars of height 5 and 6 are 3 apart: min(5, 6) × 3 = 15 — the biggest area."
  },
  "memory": {
    "remember": "Width only shrinks,\nso always move the shorter wall.",
    "pattern": "Two pointers, move the shorter side"
  }
};

export default problem;
