// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H118",
  "number": 118,
  "slug": "stock-span-problem",
  "title": "Stock Span Problem",
  "category": "Stack",
  "definition": "For each day, count how many days in a row (ending today) the price was less than or equal to today's price.",
  "example": {
    "input": "[100,80,60,70,60,75,85]",
    "output": "[1,1,1,2,1,4,6]"
  },
  "approach": "For every day, walk left while the earlier prices are not higher than today's.",
  "keyIdea": [
    "For day i, go left",
    "Stop at the first higher price",
    "Span = i − that index"
  ],
  "time": "O(n²)",
  "space": "O(1)",
  "complexityWhy": "Each day may scan back to the start.",
  "figure": {
    "k": "bars",
    "r": [
      {
        "v": [
          100,
          80,
          60,
          70,
          60,
          75,
          85
        ],
        "ok": [
          1,
          2,
          3,
          4,
          5,
          6
        ],
        "hi": [
          6
        ]
      }
    ],
    "h": 56,
    "cap": "On the last day (85) the span reaches back to just after 100 → 6 days."
  },
  "better": {
    "name": "Monotonic stack of indices",
    "time": "O(n)",
    "space": "O(n)",
    "code": "class Solution {\n  public int[] stockSpan(int[] prices) {\n    int[] spans = new int[prices.length];\n    Deque<Integer> stack = new ArrayDeque<>();         // indices of higher prices\n    for (int i = 0; i < prices.length; i++) {\n      while (!stack.isEmpty() && prices[stack.peek()] <= prices[i]) stack.pop();\n      spans[i] = stack.isEmpty() ? i + 1 : i - stack.peek();\n      stack.push(i);\n    }\n    return spans;\n  }\n}"
  },
  "code": "class Solution {\n  public int[] stockSpan(int[] prices) {\n    int[] spans = new int[prices.length];\n    for (int i = 0; i < prices.length; i++) {\n      int span = 1;\n      while (i - span >= 0 && prices[i - span] <= prices[i]) span++;\n      spans[i] = span;\n    }\n    return spans;\n  }\n}",
  "method": "stockSpan",
  "defaultInput": "[100,80,60,70,60,75,85]",
  "tests": [
    {
      "name": "Example",
      "args": [
        [
          100,
          80,
          60,
          70,
          60,
          75,
          85
        ]
      ],
      "expected": [
        1,
        1,
        1,
        2,
        1,
        4,
        6
      ]
    },
    {
      "name": "Single day",
      "args": [
        [
          10
        ]
      ],
      "expected": [
        1
      ]
    },
    {
      "name": "Rising prices",
      "args": [
        [
          1,
          2,
          3,
          4
        ]
      ],
      "expected": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "name": "Falling prices",
      "args": [
        [
          4,
          3,
          2,
          1
        ]
      ],
      "expected": [
        1,
        1,
        1,
        1
      ]
    },
    {
      "name": "Equal prices",
      "args": [
        [
          5,
          5,
          5
        ]
      ],
      "expected": [
        1,
        2,
        3
      ]
    },
    {
      "name": "Empty",
      "args": [
        []
      ],
      "expected": []
    }
  ],
  "challenge": {
    "question": "What is the span on the 5th day (price 120)?",
    "input": "[10,4,5,90,120,80]",
    "options": [
      "7",
      "3",
      "8",
      "5"
    ],
    "answer": 3,
    "explanation": "The span counts consecutive days up to today with price ≤ today's. 120 is at least as high as every earlier price, so the span covers all 5 days."
  },
  "memory": {
    "remember": "Pop every price that isn't higher;\nthe span reaches back to what remains.",
    "pattern": "Monotonic stack of indices"
  }
};

export default problem;
