// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H053",
  "number": 53,
  "slug": "reverse-integer-with-overflow-check",
  "title": "Reverse Integer (with overflow check)",
  "category": "Math & Number Theory",
  "definition": "Reverse the digits of a 32-bit signed integer. Return 0 if the result doesn't fit.",
  "example": {
    "input": "123 → 321,  1534236469 → 0",
    "output": "321, 0"
  },
  "approach": "Peel the digits off with % 10 and build the reversed number in a long. If it does not fit in an int, return 0.",
  "keyIdea": [
    "Use a long so nothing overflows while building",
    "digit = x % 10, then x = x / 10",
    "reversed = reversed × 10 + digit",
    "Outside −2³¹ … 2³¹ − 1 → return 0"
  ],
  "time": "O(d)",
  "space": "O(1)",
  "complexityWhy": "One pass over the digits.",
  "figure": {
    "k": "flow",
    "s": [
      "123 → 3 → 32 → 321",
      "1534236469 → … → 9646324351",
      "!9646324351 > 2147483647 → return 0"
    ],
    "cap": "The check must happen BEFORE the multiplication overflows (in fixed-size languages)."
  },
  "code": "class Solution {\n  public int reverseInteger(int x) {\n    long reversed = 0;                                          // long has room for the overflow\n    while (x != 0) {\n      reversed = reversed * 10 + x % 10;                        // last digit goes to the back\n      x /= 10;\n    }\n    if (reversed > Integer.MAX_VALUE || reversed < Integer.MIN_VALUE) return 0;   // does not fit in an int\n    return (int) reversed;\n  }\n}",
  "method": "reverseInteger",
  "defaultInput": "123",
  "tests": [
    {
      "name": "Example",
      "args": [
        123
      ],
      "expected": 321
    },
    {
      "name": "Negative",
      "args": [
        -123
      ],
      "expected": -321
    },
    {
      "name": "Trailing zero",
      "args": [
        120
      ],
      "expected": 21
    },
    {
      "name": "Zero",
      "args": [
        0
      ],
      "expected": 0
    },
    {
      "name": "Overflow",
      "args": [
        1534236469
      ],
      "expected": 0
    },
    {
      "name": "Max int",
      "args": [
        2147483647
      ],
      "expected": 0
    },
    {
      "name": "Min int",
      "args": [
        -2147483648
      ],
      "expected": 0
    }
  ],
  "challenge": {
    "question": "What does reverseInteger return for 1463847412?",
    "input": "1463847412",
    "options": [
      "0",
      "2147483641",
      "1463847412",
      "-2147483641"
    ],
    "answer": 1,
    "explanation": "The reverse, 2147483641, is just below 2³¹ − 1 = 2147483647, so it still fits in an int (1534236469 would overflow and return 0)."
  },
  "memory": {
    "remember": "Build the answer in a long,\nthen check that it fits in an int.",
    "pattern": "Use a Wider Type to Detect Overflow"
  }
};

export default problem;
