// Generated by scripts/generate.ts from the DSA handbook + scripts/authoring.mjs — edit those, then re-run the generator.
import type { Problem } from "../types";

const problem: Problem = {
  "id": "DSA-H151",
  "number": 151,
  "slug": "palindrome-partitioning",
  "title": "Palindrome Partitioning",
  "category": "Backtracking",
  "definition": "Split a string so every piece is a palindrome. Return all ways.",
  "example": {
    "input": "\"aab\"",
    "output": "[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]"
  },
  "approach": "Cut off a first piece. If it's a palindrome, partition the rest the same way.",
  "keyIdea": [
    "Try every first piece",
    "Keep it only if it is a palindrome",
    "Recurse on the remaining text"
  ],
  "time": "O(n²·2ⁿ)",
  "space": "O(n)",
  "complexityWhy": "Palindrome check costs O(n) each time.",
  "figure": {
    "k": "flow",
    "s": [
      "a | ab ?  → 'a' is a palindrome",
      "a | a | b  ✓",
      "aa | b  ✓",
      "![a,a,b]  and  [aa,b]"
    ],
    "cap": "Cut, test the piece, continue with the rest."
  },
  "code": "class Solution {\n  public List<List<String>> partition(String s) {\n    List<List<String>> result = new ArrayList<>();\n    backtrack(s, 0, new ArrayList<>(), result);\n    return result;\n  }\n  private void backtrack(String s, int start, List<String> path, List<List<String>> result) {\n    if (start == s.length()) { result.add(new ArrayList<>(path)); return; }\n    for (int end = start + 1; end <= s.length(); end++) {\n      String piece = s.substring(start, end);\n      if (isPalindrome(piece)) {   // palindrome?\n        path.add(piece);\n        backtrack(s, end, path, result);\n        path.remove(path.size() - 1);\n      }\n    }\n  }\n  private boolean isPalindrome(String p) {\n    int l = 0, r = p.length() - 1;\n    while (l < r) if (p.charAt(l++) != p.charAt(r--)) return false;\n    return true;\n  }\n}",
  "method": "partition",
  "unordered": true,
  "defaultInput": "\"aab\"",
  "tests": [
    {
      "name": "Example",
      "args": [
        "aab"
      ],
      "expected": [
        [
          "a",
          "a",
          "b"
        ],
        [
          "aa",
          "b"
        ]
      ]
    },
    {
      "name": "Single letter",
      "args": [
        "a"
      ],
      "expected": [
        [
          "a"
        ]
      ]
    },
    {
      "name": "Two equal letters",
      "args": [
        "aa"
      ],
      "expected": [
        [
          "a",
          "a"
        ],
        [
          "aa"
        ]
      ]
    },
    {
      "name": "No repeats",
      "args": [
        "abc"
      ],
      "expected": [
        [
          "a",
          "b",
          "c"
        ]
      ]
    },
    {
      "name": "Odd palindrome",
      "args": [
        "aba"
      ],
      "expected": [
        [
          "a",
          "b",
          "a"
        ],
        [
          "aba"
        ]
      ]
    },
    {
      "name": "Even palindrome",
      "args": [
        "abba"
      ],
      "expected": [
        [
          "a",
          "b",
          "b",
          "a"
        ],
        [
          "a",
          "bb",
          "a"
        ],
        [
          "abba"
        ]
      ]
    }
  ],
  "challenge": {
    "question": "In how many ways can \"aabb\" be cut into palindromes?",
    "input": "\"aabb\"",
    "options": [
      "2",
      "8",
      "4",
      "7"
    ],
    "answer": 2,
    "explanation": "a|a|b|b, aa|b|b, a|a|bb and aa|bb → 4 ways."
  },
  "memory": {
    "remember": "Try every palindromic prefix,\nthen partition the rest of the string.",
    "pattern": "Cut a Palindrome Prefix, Recurse on the Rest"
  }
};

export default problem;
